Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2023-10, with the labels that each got.

#9 Adding Spy and Investigating Leads
  Modules/CustomRolesHelper.cs
  Modules/GameState.cs
  Modules/NameColorManager.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Data/en.json
  Resources/Data/zh-CN.json
  Roles/Crewmate/CopyCat.cs
  Roles/Crewmate/Divinator.cs
  Roles/Crewmate/Spy.cs
  Roles/Crewmate/Swapper.cs
  main.cs
Labels: New Role/Add-on

#13 Custom translation file automatically updates.
  Modules/Translator.cs
Labels: Enhancement

#15 Possible fix to president wrongfully revealed?
  Modules/ExtendedPlayerControl.cs
Labels: Fix bug

#16 Update Ru Translation
  Resources/Data/en.json
  Resources/Data/ru.json
Labels: Add/Update Translation

#17 Fixed Bug When Tracefinder See Arrows When No One Was Dead
  Modules/Utils.cs
  Roles/Crewmate/Tracefinder.cs
Labels: Fix bug

#18 few fix for president
  Modules/RPC.cs
  Patches/PlayerControlPatch.cs
  Resources/Data/en.json
Labels: Fix bug

#19 added patreon /up access
  Modules/DevManager.cs
Labels: Some change

#22 added portuguese (Brazil) translations
  Resources/Data/pt-BR.json
Labels: Add/Update Translation

#23 Add some TChinese Translation and add my name on dev manger
  Modules/DevManager.cs
  Resources/Data/zh-TW.json
Labels: Add/Update Translation

#24 Updated translations and updated translator tags
  Modules/DevManager.cs
  Resources/Data/es-ES.json
Labels: Some change, Add/Update Translation

#25 Rework CheckGameEndPatch.cs for nks (needs ti be reviewd)
  Patches/CheckGameEndPatch.cs
Labels: Enhancement

#26 fixed missing }
  Patches/CheckGameEndPatch.cs
Labels: Fix bug

#27 Add FodyWeavers.xsd
  FodyWeavers.xsd
Labels: Some change

#28 add TChinese welcome lobby message template and Banwords for TChinese also give me debug perms
  Modules/DevManager.cs
  Resources/Config/BanWords/TChinese.txt
  Resources/Config/template/TChinese.txt
Labels: Add/Update Translation

#31 President fix and changed display plugin version to 2.1
  Modules/RPC.cs
  Patches/onGameStartedPatch.cs
  Roles/Crewmate/President.cs
  main.cs
Labels: Fix bug

#14 Updated mini, custom eviction text and Chinese announcements
  Modules/NameColorManager.cs
  Patches/AnnouncementPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Resources/Data/en.json
  Resources/Data/zh-CN.json
  Roles/Double/Mini.cs
  Roles/Neutral/Executioner.cs
Labels: Some change, Add/Update Translation

#32 Update Announcement & Fix Build Error
  Modules/RPC.cs
  Patches/AnnouncementPatch.cs
  Patches/PlayerControlPatch.cs
Labels: Some change, Add/Update Translation

#33 Fix Position Auto Re-join & Some Fix
  Patches/ChatCommandPatch.cs
  Patches/EndGameManagerPatch.cs
Labels: Some change

#34 Fix White List
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#35 Bloodhound/Coroner: Inform killer about being tracked
  Resources/Data/en.json
  Roles/Crewmate/Bloodhound.cs
Labels: New Setting

#36 Rework Check Game End Patch & Fix President
  Modules/RPC.cs
  Patches/CheckGameEndPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/Crewmate/President.cs
  main.cs
Labels: Enhancement

#37 Twister: Hide who the players swap places with
  Resources/Data/en.json
  Roles/Impostor/Twister.cs
Labels: New Setting

#38 Updated shaman, reworked Reverie, removed glow and some other changes
  Modules/ChatManager.cs
  Modules/CustomRolesHelper.cs
  Modules/GuessManager.cs
  Modules/NameColorManager.cs
  Modules/OptionHolder.cs
  Modules/ServerAddManager.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/PlayerControlPatch.cs
  Resources/Data/en.json
  Roles/Crewmate/Merchant.cs
  Roles/Crewmate/ParityCop.cs
  Roles/Crewmate/Reverie.cs
  main.cs
Labels: Fix bug, Some change, Rework Role/Add-on, Add/Update Translation

#39 added 2 settings for reverie and updated text strings
  Patches/PlayerControlPatch.cs
  Resources/Data/en.json
  Roles/Crewmate/Reverie.cs
Labels: Add/Update Translation, New Setting

#41 Updated president, infectious, and some changes
  Modules/ChatManager.cs
  Modules/DevManager.cs
  Patches/ChatCommandPatch.cs
  Resources/Data/en.json
  Roles/Crewmate/President.cs
  Roles/Neutral/Infectious.cs
  Roles/Neutral/Pirate.cs
Labels: Some change, Add/Update Translation, New Setting

#43 Fix Text In Json
  Resources/Data/en.json
  Resources/Data/ru.json
Labels: Add/Update Translation

#42 Added new Lobby game, fixed /rps and fixed reverie textstring
  Patches/ChatCommandPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Resources/Data/en.json
  main.cs
Labels: Fix bug, Enhancement, Add/Update Translation

#44 Remove Сoven Roles (Shade, Coven Leader, Ritualist, Banshee)
  Modules/AntiBlackout.cs
  Modules/ChatManager.cs
  Modules/CustomRoleSelector.cs
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/GuessManager.cs
  Modules/NameColorManager.cs
  Modules/OptionHolder.cs
  Modules/OptionItem/OptionItem.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/HudPatch.cs
  Patches/HudSpritePatch.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Data/en.json
  Resources/Data/es-ES.json
  Resources/Data/pt-BR.json
  Resources/Data/ru.json
  Resources/Data/zh-CN.json
  Resources/Data/zh-TW.json
  Resources/Images/TabIcon_CovenRoles.png
  Roles/Crewmate/CopyCat.cs
  Roles/Crewmate/Divinator.cs
  Roles/Crewmate/Oracle.cs
  Roles/Crewmate/Sheriff.cs
  Roles/Neutral/Banshee.cs
  Roles/Neutral/CovenLeader.cs
  Roles/Neutral/Shade.cs
  main.cs
Labels: Some change, Remove Role/Add-on

#46 readded gradient tags, new setting for spy and some other change
  Modules/OptionHolder.cs
  Modules/TemplateManager.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/MainMenuManagerPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Resources/Config/template/Brazilian.txt
  Resources/Config/template/English.txt
  Resources/Config/template/Russian.txt
  Resources/Config/template/SChinese.txt
  Resources/Config/template/TChinese.txt
  Resources/Data/en.json
  Roles/Crewmate/Spy.cs
  main.cs
Labels: Some change, Add/Update Translation, New Setting

#49 Synchronize and update announcements in Chinese
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#50 Ported rebound from SLE, added bandit setting and some change in /coinflip
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GuessManager.cs
  Modules/OptionHolder.cs
  Patches/ChatCommandPatch.cs
  Resources/Data/en.json
  Roles/Crewmate/Judge.cs
  Roles/Crewmate/Merchant.cs
  Roles/Impostor/Councillor.cs
  Roles/Neutral/Bandit.cs
  main.cs
Labels: Some change, New Role/Add-on, Add/Update Translation, New Setting

#51 Fix Missing PrefixB.Onbound
  Resources/Data/en.json
Labels: Add/Update Translation

#52 Trickster Now Appears In Remaining Impostors
  Patches/ChatCommandPatch.cs
  Patches/MeetingHudPatch.cs
Labels: Some change

#53 Add Check Null For Tracker
  Roles/Crewmate/Tracker.cs
Labels: Some change

#54 Some Fix For Setting "Remove Pets At Dead Players"
  Modules/OptionHolder.cs
  Patches/PetsPatch.cs
Labels: Some change

#55 changed pyromaniac color
  main.cs
Labels: Some change

#56 Rename Agent To Evil Tracker
  Resources/Data/en.json
Labels: Some change

#57 Improve «FixedUpdatePatch»
  Modules/BanManager.cs
  Modules/DoubleTrigger.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/Crewmate/Addict.cs
  Roles/Crewmate/Alchemist.cs
  Roles/Crewmate/Chameleon.cs
  Roles/Crewmate/Divinator.cs
  Roles/Crewmate/Farseer.cs
  Roles/Crewmate/Monitor.cs
  Roles/Crewmate/Oracle.cs
  Roles/Crewmate/ParityCop.cs
  Roles/Crewmate/Spy.cs
  Roles/Crewmate/Tracefinder.cs
  Roles/Crewmate/Tracker.cs
  Roles/Impostor/AntiAdminer.cs
  Roles/Impostor/BallLightning.cs
  Roles/Impostor/BountyHunter.cs
  Roles/Impostor/Deathpact.cs
  Roles/Impostor/Eraser.cs
  Roles/Impostor/Mastermind.cs
  Roles/Impostor/Pitfall.cs
  Roles/Impostor/Puppeteer.cs
  Roles/Impostor/SerialKiller.cs
  Roles/Impostor/Swooper.cs
  Roles/Impostor/Vampire.cs
  Roles/Impostor/Vampiress.cs
  Roles/Impostor/Wildling.cs
  Roles/Neutral/Agitater.cs
  Roles/Neutral/Bandit.cs
  Roles/Neutral/BloodKnight.cs
  Roles/Neutral/Doomsayer.cs
  Roles/Neutral/Glitch.cs
  Roles/Neutral/Huntsman.cs
  Roles/Neutral/NWitch.cs
  Roles/Neutral/Pelican.cs
  Roles/Neutral/PlagueBearer.cs
  Roles/Neutral/Poisoner.cs
  Roles/Neutral/Seeker.cs
  Roles/Neutral/Shroud.cs
  Roles/Neutral/Spiritcaller.cs
  Roles/Neutral/Wraith.cs
  main.cs
Labels: Fix bug, Enhancement

#58 Added settings for CP, Deceiver and a new camo skin (lol)
  Modules/Camouflague.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Resources/Data/en.json
  Roles/Crewmate/Counterfeiter.cs
Labels: Fix bug, Add/Update Translation, New Setting

#59 fix vip gradient tag and President x Doppelganger interaction
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#60 Fixed vigi and rebound in main, and some changes
  Modules/CustomRolesHelper.cs
  Roles/Crewmate/CopyCat.cs
  main.cs
Labels: Improve Role/Add-on, Some change

#61 made spy compatible with Copycat and CP setting (CP needs testing)
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/onGameStartedPatch.cs
  Resources/Data/en.json
  Roles/Crewmate/CopyCat.cs
  main.cs
Labels: Improve Role/Add-on, Add/Update Translation, New Setting

#63 Add "try {} catch () {}" In GetProgressText()
  Modules/Utils.cs
  Roles/Crewmate/Spy.cs
  main.cs
Labels: Some change

#64 Try Fix Null Spams
  Roles/Crewmate/President.cs
Labels: Fix bug

#65 Rename Disruptor To Anti Adminer
  Resources/Data/en.json
Labels: Some change

#69 merged bweilder and sunglasses
  Modules/CustomRolesHelper.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/OptionHolder.cs
  Patches/ChatCommandPatch.cs
  Resources/Data/en.json
  Roles/Crewmate/Merchant.cs
  main.cs
Labels: Add/Update Translation, New Setting, Remove Role/Add-on

#66 Deathpact players can call meeting
  Patches/PlayerControlPatch.cs
  Resources/Data/en.json
  Roles/Impostor/Deathpact.cs
Labels: New Setting

#70 commented out occultist
  Modules/AntiBlackout.cs
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/NameColorManager.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ExilePatch.cs
  Patches/HudPatch.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/Crewmate/Divinator.cs
  Roles/Neutral/Amnesiac.cs
  Roles/Neutral/Imitator.cs
  Roles/Neutral/Occultist.cs
  main.cs
Labels: Remove Role/Add-on

#71 More Сode Improvements In "FixedUpdatePatch" & Fix Bugs
  Patches/PlayerControlPatch.cs
  Roles/Impostor/Vampire.cs
  Roles/Impostor/Vampiress.cs
  Roles/Neutral/Agitater.cs
  Roles/Neutral/Poisoner.cs
  Roles/Neutral/Spiritcaller.cs
Labels: Fix bug, Enhancement

#72 Made a default template file and added Spanish in default templates
  Modules/TemplateManager.cs
  Resources/Config/template/Brazilian.txt
  Resources/Config/template/English.txt
  Resources/Config/template/Russian.txt
  Resources/Config/template/SChinese.txt
  Resources/Config/template/Spanish.txt
  Resources/Config/template/TChinese.txt
Labels: Some change

#77 Fix Build Error & Fix Loading Translations
  Modules/Translator.cs
  TOHE.csproj
Labels: Fix bug

#80 added sponsor
  Modules/DevManager.cs
Labels: Some change

#81 Fix Bug Where Cyber Settings Not Working
  Modules/CustomRolesHelper.cs
Labels: Fix bug

#82 update of AnnouncementPatch
  .gitignore
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#87 added sponsors; fixed Copycat, snitch and bandit
  Modules/CustomRolesHelper.cs
  Modules/DevManager.cs
  Roles/Crewmate/CopyCat.cs
  Roles/Neutral/Bandit.cs
Labels: Fix bug, Some change

#76 New Crowdin updates
  Resources/Lang/es_ES.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#90 fix huntsman wrong win screen
  Patches/CheckGameEndPatch.cs
Labels: Fix bug

#91 Recode Imitator, Amnesiac. Fix admirer in copycat
  Roles/Crewmate/Admirer.cs
  Roles/Crewmate/CopyCat.cs
  Roles/Neutral/Amnesiac.cs
  Roles/Neutral/Imitator.cs
Labels: Fix bug, Rework Role/Add-on

#93 .transform.position => .GetTruePosition()
  Modules/GameState.cs
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Roles/Crewmate/Alchemist.cs
  Roles/Impostor/Twister.cs
  Roles/Impostor/Undertaker.cs
  Roles/Neutral/Pelican.cs
Labels: Some change

#92 Try Fix "/death" command
  Patches/ChatCommandPatch.cs
Labels: Fix bug

#95 added sponsors, new setting for cursedwolf and jinx and some fix
  Modules/CustomRolesHelper.cs
  Modules/DevManager.cs
  Modules/OptionHolder.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Resources/Lang/zh_TW.json
  Roles/Neutral/Jinx.cs
Labels: Fix bug, Some change, Add/Update Translation, New Setting

#89 Hater no longer ignores shields & Code improvement
  Patches/CheckGameEndPatch.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Neutral/FFF.cs
Labels: Some change

#83 Make Mini unable to be recruited and special kills
  Modules/CustomRolesHelper.cs
  Modules/DevManager.cs
  Patches/CheckGameEndPatch.cs
  Patches/PlayerControlPatch.cs
  Resources/Config/template/SChinese.txt
  Resources/Lang/en_US.json
  Resources/Lang/zh_CN.json
  Roles/Crewmate/Admirer.cs
  Roles/Crewmate/Monarch.cs
  Roles/Impostor/Gangster.cs
  Roles/Neutral/CursedSoul.cs
  Roles/Neutral/Infectious.cs
  Roles/Neutral/Jackal.cs
  Roles/Neutral/Pelican.cs
  Roles/Neutral/Romantic.cs
  Roles/Neutral/Succubus.cs
Labels: Improve Role/Add-on

#99 added sponsor, temporary delayed spam fix, fix wrong name shown for bait reveal and /id, and admirer fix, and spy fix
  Modules/ChatManager.cs
  Modules/DevManager.cs
  Modules/GameState.cs
  Modules/GuessManager.cs
  Modules/RPC.cs
  Patches/ChatCommandPatch.cs
  Patches/MeetingHudPatch.cs
  Roles/Crewmate/Admirer.cs
  Roles/Crewmate/Judge.cs
  Roles/Crewmate/ParityCop.cs
  Roles/Crewmate/President.cs
  Roles/Crewmate/Spy.cs
  Roles/Crewmate/Swapper.cs
  Roles/Impostor/Councillor.cs
  Roles/Neutral/Pirate.cs
Labels: Fix bug

#100 added sponsor, fix huntsman
  Modules/DevManager.cs
  Roles/Neutral/Huntsman.cs
Labels: Fix bug, Some change

#101 Merchant setting
  Resources/Lang/en_US.json
  Roles/Crewmate/Merchant.cs
Labels: Add/Update Translation, New Setting

#102 Credited TOHEX & Stellar Roles in README.md
  README.md
Labels: Update README

#105 fix shrouded player die even after shroud dead in meeting
  Roles/Neutral/Shroud.cs
Labels: Fix bug

#107 Fix mini bug
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GuessManager.cs
  Modules/MafiaRevengeManager.cs
  Modules/RetributionistRevengeManager.cs
  Patches/PlayerControlPatch.cs
  Resources/Config/template/SChinese.txt
  Roles/Crewmate/Judge.cs
  Roles/Double/Mini.cs
Labels: Fix bug

#110 fix berserker unable to die and spamming error
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#111 Fix bug when NiceMini can be Madmate & Fix conflict Void & Tiebreaker
  Modules/CustomRolesHelper.cs
Labels: Fix bug

#103 Code Improvements (Part 1)
  Modules/ChatManager.cs
  Modules/CustomRoleSelector.cs
  Modules/EAC.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/GameOptionsSender.cs
  Modules/GameOptionsSender/NormalGameOptionsSender.cs
  Modules/OptionBackup/OptionBackupData.cs
  Modules/OptionBackup/OptionBackupValue.cs
  Modules/RPC.cs
  Patches/CheckGameEndPatch.cs
  Patches/ControlPatch.cs
  Patches/ExilePatch.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/Crewmate/Farseer.cs
  Roles/Impostor/BountyHunter.cs
  Roles/Impostor/Chronomancer.cs
  Roles/Impostor/Councillor.cs
  Roles/Impostor/Deathpact.cs
  Roles/Impostor/SerialKiller.cs
  Roles/Impostor/Vampire.cs
  Roles/Impostor/Vampiress.cs
  Roles/Neutral/Agitater.cs
  Roles/Neutral/PlagueBearer.cs
  Roles/Neutral/Poisoner.cs
  Roles/Neutral/Seeker.cs
  TOHE.csproj
  main.cs
Labels: Enhancement

#108 rework check game end patch
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Patches/CheckGameEndPatch.cs
  Patches/PlayerControlPatch.cs
  Roles/Neutral/Huntsman.cs
Labels: Enhancement

#98 New Crowdin updates
  Resources/Lang/es_ES.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#109 Fix swapper (From TOHEX)
  Modules/OptionHolder.cs
  Patches/MeetingHudPatch.cs
  Resources/Lang/en_US.json
  Resources/Lang/zh_CN.json
  Roles/Crewmate/Swapper.cs
Labels: Fix bug

#113 merged with main and resolved conflicts
  Modules/Camouflague.cs
  Modules/ChatManager.cs
  Modules/CustomRoleSelector.cs
  Modules/CustomRolesHelper.cs
  Modules/EAC.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/GameOptionsSender.cs
  Modules/GameOptionsSender/NormalGameOptionsSender.cs
  Modules/GuessManager.cs
  Modules/MafiaRevengeManager.cs
  Modules/OptionBackup/OptionBackupData.cs
  Modules/OptionBackup/OptionBackupValue.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/RetributionistRevengeManager.cs
  Patches/AnnouncementPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ControlPatch.cs
  Patches/ExilePatch.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PetsPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  README.md
  Resources/Config/template/SChinese.txt
  Resources/Lang/en_US.json
  Resources/Lang/es_ES.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
  Roles/Crewmate/Farseer.cs
  Roles/Crewmate/Judge.cs
  Roles/Crewmate/Swapper.cs
  Roles/Double/Mini.cs
  Roles/Impostor/BountyHunter.cs
  Roles/Impostor/Chronomancer.cs
  Roles/Impostor/Councillor.cs
  Roles/Impostor/Deathpact.cs
  Roles/Impostor/OverKiller.cs
  Roles/Impostor/SerialKiller.cs
  Roles/Impostor/Vampire.cs
  Roles/Impostor/Vampiress.cs
  Roles/Neutral/Agitater.cs
  Roles/Neutral/PlagueBearer.cs
  Roles/Neutral/Poisoner.cs
  Roles/Neutral/Seeker.cs
  TOHE.csproj
  main.cs
Labels: Some change

#114 lurker incompatible with circumvent, butcher incompatoble with swift and removed sponsor
  Modules/CustomRolesHelper.cs
  Modules/DevManager.cs
Labels: Some change

#118 changed discord rich presence for modded servers
  Patches/DiscordPatch.cs
Labels: Some change

#117 fixed recruiting roles showing up twice in end screen
  Modules/CustomRolesHelper.cs
  Modules/DevManager.cs
  Patches/CheckGameEndPatch.cs
Labels: Fix bug

#119 Fix Reset Settings?
  Modules/OptionBackup/OptionBackupData.cs
  Modules/OptionBackup/OptionBackupValue.cs
  Modules/RPC.cs
Labels: Fix bug

#120 Fix BoolOptionNames.GhostsDoTasks
  Modules/OptionBackup/OptionBackupData.cs
Labels: Fix bug

#122 Return Сode
  Modules/OptionBackup/OptionBackupData.cs
  Modules/OptionBackup/OptionBackupValue.cs
Labels: Some change

#124 Feat: Add AutoMuteUs option to fix an issue with the Host Name
  Modules/Utils.cs
  Patches/ClientOptionsPatch.cs
  Resources/Lang/en_US.json
  main.cs
Labels: Fix bug, New Setting

#125 added french translator
  Modules/DevManager.cs
Labels: Some change

#126 Fix AutoMuteUs For Tag
  Modules/Utils.cs
Labels: Fix bug

#123 Updated SChinese Announcement
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#128 Fix Id Announcements
  Patches/AnnouncementPatch.cs
Labels: Some change

#131 Fix some errors
  Modules/DoorsReset.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/GameOptionsSender.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Patches/ChatCommandPatch.cs
  Patches/ControlPatch.cs
  Patches/HudPatch.cs
  Patches/LadderPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/SabotageSystemPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/TaskAssignPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/AddOns/Common/Repairman.cs
  Roles/Crewmate/Alchemist.cs
  Roles/Crewmate/SabotageMaster.cs
  Roles/Impostor/OverKiller.cs
  Roles/Neutral/Agitater.cs
  Roles/Neutral/DarkHide.cs
  Roles/Neutral/Glitch.cs
  TOHE.csproj.DotSettings
Labels: Update Mod

#115 Add dlekS ehT (mirrored Skeld) support
  Modules/Camouflague.cs
  Modules/DisableDevice.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/ExilePatch.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/IntroPatch.cs
  Patches/MainMenuManagerPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/RandomSpawnPatch.cs
  Patches/ShipStatusPatch.cs
  Resources/Lang/en_US.json
  Resources/Lang/es_ES.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_TW.json
  Roles/Crewmate/Monitor.cs
  Roles/Impostor/AntiAdminer.cs
  Roles/Neutral/Pelican.cs
Labels: Enhancement, Add/Update Translation, In Progress

#134 Add blackroom position for fungle
  Roles/Neutral/Pelican.cs
Labels: Some change, Update Mod

#135 announcementpatch.cs update
  Patches/AnnouncementPatch.cs
  Resources/Config/template/TChinese.txt
Labels: Add/Update Translation

#139 Try Fix Teleport Players & RpcMurderPlayer => RpcMurderPlayerV3
  Modules/ExtendedPlayerControl.cs
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Patches/ServerVersionPatch.cs
  Roles/Crewmate/Spy.cs
  Roles/Neutral/Agitater.cs
  Roles/Neutral/Pelican.cs
Labels: Fix bug, Some change, Update Mod

#138 Add Fungle to "Anti Adminer", "Monitor" and add the posibility to disable devices on the fungle
  Modules/DisableDevice.cs
  Modules/OptionHolder.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Monitor.cs
  Roles/Impostor/AntiAdminer.cs
Labels: New Setting, Update Mod

#143 Build Selection Version
  Patches/CredentialsPatch.cs
  TOHE.csproj
Labels: Some change

#145 Add disable comms on fungle
  Modules/Camouflague.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
Labels: Some change, New Setting, Update Mod

#146 Fix SabotageMaster & Alchemist
  Patches/ShipStatusPatch.cs
Labels: Fix bug, Update Mod

#147 Update RU Announcement
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#133 Support AU v2023.10.24
  .gitignore
  Modules/Camouflague.cs
  Modules/CustomRpcSender.cs
  Modules/DebugModeManager.cs
  Modules/DisableDevice.cs
  Modules/DoorsReset.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/GameOptionsSender.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/GameState.cs
  Modules/MeetingTimeManager.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ControlPatch.cs
  Patches/CredentialsPatch.cs
  Patches/ExilePatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/HudPatch.cs
  Patches/IntroPatch.cs
  Patches/LadderPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PetsPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/RandomSpawnPatch.cs
  Patches/SabotageSystemPatch.cs
  Patches/ServerVersionPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/TaskAssignPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/AddOns/Common/Repairman.cs
  Roles/Crewmate/Alchemist.cs
  Roles/Crewmate/Monitor.cs
  Roles/Crewmate/SabotageMaster.cs
  Roles/Crewmate/Spy.cs
  Roles/Impostor/AntiAdminer.cs
  Roles/Impostor/OverKiller.cs
  Roles/Impostor/Twister.cs
  Roles/Impostor/Undertaker.cs
  Roles/Impostor/Vampire.cs
  Roles/Neutral/Agitater.cs
  Roles/Neutral/DarkHide.cs
  Roles/Neutral/Glitch.cs
  Roles/Neutral/Pelican.cs
  TOHE.csproj
  TOHE.csproj.DotSettings
  TOHE.sln
  main.cs
  nuget.config
Labels: Update Mod

#141 [Feature]Temp Ban those who keep quitting
  Modules/BanManager.cs
  Modules/OptionHolder.cs
  Patches/OutroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Resources/Lang/en_US.json
  main.cs
Labels: New Setting

#152 TownOfHostEdited =>TownofHost-Enhanced
  Resources/Lang/en_US.json
Labels: Some change

#153 added french translator and sponsor
  Modules/DevManager.cs
Labels: Some change

#154 updated main code in the branch
  Modules/DevManager.cs
  Patches/AnnouncementPatch.cs
  Resources/Lang/en_US.json
Labels: Other

#155 fix wrong /gno message and typo in text strings
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
Labels: Some change

#157 fix preset settings overwritten, fix copycat, seeker and added japanese translator
  Modules/DevManager.cs
  Modules/OptionHolder.cs
  Modules/OptionSaver.cs
  Roles/Crewmate/Judge.cs
  Roles/Neutral/Seeker.cs
Labels: Fix bug, Some change

#158 update announcementpatch.cs
  Patches/AnnouncementPatch.cs
  Resources/Config/template/TChinese.txt
Labels: Add/Update Translation

#159 Add niko to dev manager
  Modules/DevManager.cs
Labels: Some change

#161 Added 1.2.0 version SChinese announcement
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#162 Fixing the mini bug again
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Roles/Double/Mini.cs
Labels: Fix bug

#164 GetBlackRoomPosition()
  Modules/ExtendedPlayerControl.cs
  Patches/PlayerControlPatch.cs
  Roles/Impostor/Undertaker.cs
  Roles/Neutral/Pelican.cs
Labels: Fix bug

#165 Fix Unlucky Again
  Modules/CustomRoleSelector.cs
  Modules/GameState.cs
  Patches/PlayerControlPatch.cs
  Patches/ShipStatusPatch.cs
Labels: Fix bug

#166 added default french template
  Modules/TemplateManager.cs
  Resources/Config/template/French.txt
Labels: Some change

#163 update with latest main branch
  Modules/CustomRoleSelector.cs
  Modules/DevManager.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Modules/OptionSaver.cs
  Modules/RPC.cs
  Modules/TemplateManager.cs
  Modules/Utils.cs
  Patches/AnnouncementPatch.cs
  Patches/ChatCommandPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/ShipStatusPatch.cs
  Resources/Config/template/French.txt
  Resources/Config/template/TChinese.txt
  Resources/Lang/en_US.json
  Roles/Crewmate/Judge.cs
  Roles/Double/Mini.cs
  Roles/Impostor/Undertaker.cs
  Roles/Neutral/Pelican.cs
  Roles/Neutral/Seeker.cs
Labels: Other

#167 Fix Imitator
  Resources/Lang/en_US.json
  Roles/Neutral/Imitator.cs
Labels: Fix bug

#160 Dev Manager role should show in every TOHE lobby :trollface:
  Modules/Utils.cs
Labels: Some change

#168 Try Fix "/xf" Command
  Patches/ChatCommandPatch.cs
Labels: Fix bug

#169 Change version
  main.cs
Labels: Some change

#170 French In Announcements
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#173 Improved Seeker and added default japanese template
  Modules/NameColorManager.cs
  Modules/TemplateManager.cs
  Resources/Config/template/Japanese.txt
Labels: Improve Role/Add-on, Some change

#172 updated with main branch
  Modules/Utils.cs
  Patches/AnnouncementPatch.cs
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
  Roles/Neutral/Imitator.cs
  main.cs
Labels: Some change

#174 updated with main
  Modules/NameColorManager.cs
  Modules/TemplateManager.cs
  Resources/Config/template/Japanese.txt
Labels: Some change

#177 added players in eac list
  Resources/Config/EACList.txt
Labels: Some change

#179 admirer fix
  Roles/Crewmate/Admirer.cs
Labels: Fix bug

#180 Fix admirer, jackal, succubus, mario. Update string. Improve /changerole
  Modules/DebugModeManager.cs
  Modules/RPC.cs
  Patches/ChatCommandPatch.cs
  Patches/ClientOptionsPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Admirer.cs
  Roles/Neutral/Jackal.cs
  Roles/Neutral/Succubus.cs
  main.cs
Labels: Fix bug, Some change, Add/Update Translation

#182 Fix taskbar always invisible
  Patches/onGameStartedPatch.cs
Labels: Some change

#183 updated divinator text string, added sponsor, latam translator, default latam template, removed /up from translator
  Modules/DevManager.cs
  Modules/TemplateManager.cs
  Resources/Config/template/Latam.txt
  Resources/Lang/en_US.json
Labels: Some change, Add/Update Translation
