Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2023-12, with the labels that each got.

#288 Update RU Announcement & Fix text in English Announcement
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#287 Update SChinese announcement
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#289 Update SChinese announcement
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#291 Correct chinese strings in announcement
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#292 annoucementpatch.cs TChinese update
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#297 Fix Visual Bug With Negative Task
  Patches/IntroPatch.cs
Labels: Fix bug

#275 added new crew role Mole
  Modules/CustomRolesHelper.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/HudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/Crewmate/Divinator.cs
  Roles/Crewmate/Mole.cs
  main.cs
Labels: New Role/Add-on, Add/Update Translation

#298 Return Add-on Flash (Greater speed is now possible)
  Modules/CustomRolesHelper.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/GuessManager.cs
  Modules/OptionHolder.cs
  Patches/ChatCommandPatch.cs
  Resources/Lang/de_DE.json
  Resources/Lang/en_US.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/ga_IE.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
  Resources/roleColor.json
  Roles/AddOns/Common/Flash.cs
  main.cs
Labels: New Role/Add-on

#194 Support map dlekS ehT
  Modules/Camouflague.cs
  Modules/DisableDevice.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/ExilePatch.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/IntroPatch.cs
  Patches/MainMenuManagerPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/RandomSpawnPatch.cs
  Patches/SabotageSystemPatch.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Monitor.cs
  Roles/Impostor/AntiAdminer.cs
  Roles/Neutral/Pelican.cs
Labels: Enhancement

#299 added isAlive check before killing necromancer
  Roles/Neutral/Necromancer.cs
Labels: Fix bug

#300 Fix Neutrals Can Be Madmate
  Modules/CustomRolesHelper.cs
  Modules/Utils.cs
Labels: Fix bug

#301 Delay send message for invalid color player
  Modules/Utils.cs
Labels: Some change

#303 Add File "DleksPatch" & "HorseModePatch"
  Patches/DleksPatch.cs
  Patches/HorseModePatch.cs
  Patches/MainMenuManagerPatch.cs
Labels: Some change

#309 removed option of reset doors from FFA
  Modules/OptionHolder.cs
  main.cs
Labels: Some change

#304 Some Roles Will Not Spawn On Dleks Map
  Modules/CustomRoleSelector.cs
  Modules/ExtendedPlayerControl.cs
  Patches/DleksPatch.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
Labels: Some change

#315 Add Modded SA (MSA)
  Modules/ServerAddManager.cs
Labels: Some change

#316 fix fool string and made it incompatible with repairman
  Modules/CustomRolesHelper.cs
  Resources/Lang/en_US.json
Labels: Fix bug, Add/Update Translation

#320 Improve Anti first kill Host
  Modules/OptionHolder.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
Labels: New Setting

#321 Update with github (complete)
  Modules/ModUpdater.cs
  Patches/MainMenuManagerPatch.cs
  Resources/Lang/en_US.json
  main.cs
Labels: Enhancement

#318 Add solsticer
  Modules/CustomRolesHelper.cs
  Modules/DebugModeManager.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/GameState.cs
  Modules/GuessManager.cs
  Modules/MafiaRevengeManager.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/RetributionistRevengeManager.cs
  Modules/Utils.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/TaskAssignPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/Crewmate/Judge.cs
  Roles/Impostor/Councillor.cs
  Roles/Neutral/Solsticer.cs
  main.cs
Labels: New Role/Add-on

#322 Fix HGK bug
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  main.cs
Labels: Fix bug

#311 Update EAC
  Modules/EAC.cs
  Modules/OptionHolder.cs
  Patches/HorseModePatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
Labels: Enhancement

#324 fix taskinator killing already dead player
  Roles/Neutral/Taskinator.cs
Labels: Fix bug

#325 change version
  main.cs
Labels: Some change

#323 Fix ChatCommandPatch
  Patches/ChatCommandPatch.cs
Labels: Some change

#326 New crew role captain and fixed romantic bug
  Modules/CustomRolesHelper.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/Crewmate/Captain.cs
  Roles/Crewmate/Divinator.cs
  Roles/Neutral/Romantic.cs
  main.cs
Labels: Fix bug, New Role/Add-on, Add/Update Translation

#331 Fix eac patchs button event
  Modules/EAC.cs
Labels: Fix bug

#333 make workaholic unable to get doubleshot
  Modules/CustomRolesHelper.cs
Labels: Fix bug

#334 change version and fix captain text string
  Resources/Lang/en_US.json
  main.cs
Labels: Some change, Add/Update Translation

#330 new role benefactor and missing berserker string
  Modules/CustomRolesHelper.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/Crewmate/Benefactor.cs
  Roles/Crewmate/CopyCat.cs
  Roles/Crewmate/Divinator.cs
  Roles/Neutral/Taskinator.cs
  main.cs
Labels: New Role/Add-on, Add/Update Translation

#332 fix zombie text string
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#335 Exclude non dlls
  Modules/ModUpdater.cs
Labels: Fix bug

#329 Improve meeting hud check
  Patches/MeetingHudPatch.cs
Labels: Fix bug, Some change

#339 Fix eac sabotage check
  Modules/CustomRolesHelper.cs
  Modules/EAC.cs
  Patches/onGameStartedPatch.cs
Labels: Fix bug

#340 Fix Solsticer Bug
  Modules/GuessManager.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Neutral/Solsticer.cs
Labels: Fix bug

#341 new crew role Keeper and bug fixes
  Modules/CustomRolesHelper.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/Crewmate/CopyCat.cs
  Roles/Crewmate/Divinator.cs
  Roles/Crewmate/Keeper.cs
  Roles/Crewmate/ParityCop.cs
  TOHE.csproj
  main.cs
Labels: Fix bug, New Role/Add-on, Add/Update Translation

#342 Addon Silent
  Modules/CustomRolesHelper.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/MeetingHudPatch.cs
  Patches/ShipStatusPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/AddOns/Common/Repairman.cs
  Roles/AddOns/Common/Silent.cs
  main.cs
Labels: New Role/Add-on

#345 Fix players can vote a disconnect player
  Modules/GameState.cs
  Modules/GuessManager.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Fix bug

#347 some bug fixes
  Roles/Crewmate/Captain.cs
  Roles/Impostor/BountyHunter.cs
  Roles/Neutral/Romantic.cs
Labels: Fix bug

#349 new role guess master and added doomsayer and solsticer to divinator check list
  Modules/CustomRolesHelper.cs
  Modules/GuessManager.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/Crewmate/CopyCat.cs
  Roles/Crewmate/Divinator.cs
  Roles/Crewmate/GuessMaster.cs
  main.cs
Labels: Some change, New Role/Add-on

#351 updated EAC List and made masochiost unable to get fragile
  Modules/CustomRolesHelper.cs
  Resources/Config/EACList.txt
Labels: Some change

#276 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/en_US.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/ga_IE.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#352 canary
  Patches/ClientPatch.cs
  dbConnect.cs
Labels: Some change

#353 remove unreachable code
  Modules/CustomRolesHelper.cs
Labels: Some change

#354 fix json
  Resources/Lang/en_US.json
Labels: Fix bug

#355 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/en_US.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/ga_IE.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#356 Update eac list
  Patches/VoteBanSystemPatch.cs
  Resources/Config/EACList.txt
Labels: Some change

#357 Fix updater
  Modules/ModUpdater.cs
Labels: Fix bug

#360 New Setting: "Change Decontamination Time"
  Modules/OptionHolder.cs
  Patches/DeconSystemPatch.cs
  Resources/Lang/en_US.json
  main.cs
Labels: Some change, New Setting

#359 Add a skill icon and role in ChatCommandPatch
  Patches/ChatCommandPatch.cs
  Patches/HudSpritePatch.cs
  Resources/Images/Skills/Clean.png
  Resources/Images/Skills/Eat.png
  Resources/Images/Skills/Pursuer.png
Labels: Some change, Add/Update Translation

#361 Fix Decont Time & Fix Tag For Vanilla Players
  Modules/Utils.cs
  Patches/DeconSystemPatch.cs
  Patches/onGameStartedPatch.cs
Labels: Fix bug

#362 Clear Notice Message In Meeting
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#364 Name All "LateTask"
  Modules/ChatManager.cs
  Modules/CustomRoleSelector.cs
  Modules/MafiaRevengeManager.cs
  Modules/RPC.cs
  Modules/RetributionistRevengeManager.cs
  Modules/Utils.cs
  Patches/ClientPatch.cs
  Patches/EndGameManagerPatch.cs
  Patches/ExilePatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/IntroPatch.cs
  Patches/LadderPatch.cs
  Patches/MainMenuManagerPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Roles/Crewmate/Alchemist.cs
  Roles/Crewmate/Jailer.cs
  Roles/Crewmate/ParityCop.cs
  Roles/Crewmate/Swapper.cs
  Roles/Impostor/Pitfall.cs
  Roles/Impostor/Undertaker.cs
  Roles/Neutral/Agitater.cs
  Roles/Neutral/Huntsman.cs
  Roles/Neutral/Necromancer.cs
  Roles/Neutral/Pirate.cs
  Roles/Neutral/Pyromaniac.cs
  Roles/Neutral/Romantic.cs
  Roles/Neutral/Seeker.cs
  Roles/Neutral/Spiritcaller.cs
  Roles/Neutral/Vulture.cs
Labels: Some change

#366 Return Setting: "Remove Pets At Dead Players"
  Modules/Camouflague.cs
  Modules/OptionHolder.cs
  Patches/ExilePatch.cs
  Patches/PetsPatch.cs
  Patches/PlayerControlPatch.cs
Labels: Some change, New Setting

#365 Fix system messages sometimes wont appear after rejoining lobby
  Patches/ChatCommandPatch.cs
  Patches/TextBoxPatch.cs
Labels: Fix bug, Some change

#367 Fix Disable Task for The Fungle
  Modules/OptionHolder.cs
Labels: Fix bug

#369 Fix Critical Bug When Game Cannot Be End By Sabotage & By Done Task
  Patches/CheckGameEndPatch.cs
Labels: Fix bug

#368 Some fix
  Modules/EAC.cs
  Patches/ChatCommandPatch.cs
  Patches/ChatControlPatch.cs
  Patches/ClientPatch.cs
  Patches/ControlPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/TextBoxPatch.cs
  Resources/Config/EACList.txt
Labels: Fix bug

#370 Improve Game Options Code
  Modules/Extensions/IGameManagerEx.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/OptionBackup/OptionBackupData.cs
  Modules/OptionBackup/OptionBackupValue.cs
  Modules/OptionItem/OptionItem.cs
  Modules/Utils.cs
  Patches/GameOptionsMenuPatch.cs
Labels: Improve Code

#371 Use Count/Length instead of "Any()" in List/Array
  GameModes/FFAManager.cs
  Modules/CustomRoleSelector.cs
  Modules/CustomRolesHelper.cs
  Modules/ErrorText.cs
  Modules/ExtendedPlayerControl.cs
  Modules/LocateArrow.cs
  Modules/MeetingTimeManager.cs
  Modules/NameNotifyManager.cs
  Modules/TemplateManager.cs
  Modules/Translator.cs
  Modules/Utils.cs
  Patches/AirShipElectricalDoors.cs
  Patches/AnnouncementPatch.cs
  Patches/ChatCommandPatch.cs
  Patches/ChatControlPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ControlPatch.cs
  Patches/DeconSystemPatch.cs
  Patches/ExilePatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/AddOns/Common/Influenced.cs
  Roles/Crewmate/Alchemist.cs
  Roles/Crewmate/Benefactor.cs
  Roles/Crewmate/Bloodhound.cs
  Roles/Crewmate/Captain.cs
  Roles/Crewmate/Merchant.cs
  Roles/Crewmate/Spy.cs
  Roles/Impostor/BallLightning.cs
  Roles/Impostor/BountyHunter.cs
  Roles/Impostor/Deathpact.cs
  Roles/Impostor/EvilTracker.cs
  Roles/Impostor/Hacker.cs
  Roles/Impostor/Instigator.cs
  Roles/Impostor/Mare.cs
  Roles/Impostor/Mastermind.cs
  Roles/Impostor/Puppeteer.cs
  Roles/Neutral/Agitater.cs
  Roles/Neutral/Bandit.cs
  Roles/Neutral/Collector.cs
  Roles/Neutral/NWitch.cs
  Roles/Neutral/Necromancer.cs
  Roles/Neutral/Pelican.cs
  Roles/Neutral/Pixie.cs
  Roles/Neutral/Shroud.cs
Labels: Some change, Improve Code

#372 Fix the bug that NiceMini can be guessed to death by Guesser
  Modules/GuessManager.cs
Labels: Fix bug

#373 Fix bug when Cleansed Flash still have speed & Merchant sometimes didn't work
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/GameState.cs
  Roles/AddOns/Common/Flash.cs
  Roles/Crewmate/Merchant.cs
Labels: Fix bug

#374 Fix <Invalid:BenefactorTargetGotShield>
  Resources/Lang/en_US.json
  Roles/Crewmate/Benefactor.cs
Labels: Fix bug

#375 Fix Taskless Crewmate Can Get Mundane
  Modules/CustomRolesHelper.cs
Labels: Fix bug

#378 Change flags in rpcguardandkill
  Modules/ExtendedPlayerControl.cs
Labels: Some change

#379 Small improve for guard and kill [Part 2]
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Patches/GameStartManagerPatch.cs
  Patches/PlayerControlPatch.cs
Labels: Some change

#380 EAC by API
  Modules/BanManager.cs
  Resources/Config/EACList.txt
  dbConnect.cs
  main.cs
Labels: Some change

#382 <INVALID:AlchemistPotionDidNothing>
  Resources/Lang/en_US.json
  Roles/Crewmate/Alchemist.cs
Labels: Fix bug

#381 Fix tohe in vanilla rooom
  Modules/ChatManager.cs
  Patches/ChatCommandPatch.cs
  Patches/PlayerControlPatch.cs
Labels: Fix bug, Some change

#376 Add Kamikaze
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/HudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Divinator.cs
  Roles/Impostor/Kamikaze.cs
  main.cs
Labels: New Role/Add-on
