Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2023-11, with the labels that each got.

#189 Dead bodies patch & Fix my bruh error in Imitator
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Neutral/Imitator.cs
Labels: Fix bug

#188 Rework game end patch
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Patches/CheckGameEndPatch.cs
  Roles/Neutral/Huntsman.cs
Labels: Enhancement

#184 Add Influenced
  Modules/CustomRolesHelper.cs
  Modules/OptionHolder.cs
  Patches/MeetingHudPatch.cs
  Resources/Lang/en_US.json
  Roles/AddOns/Common/Influenced.cs
  main.cs
Labels: New Role/Add-on

#85 Add oiiai
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Patches/ChatCommandPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/AddOns/Common/Oiiai.cs
  Roles/Crewmate/CopyCat.cs
  Roles/Crewmate/Counterfeiter.cs
  Roles/Crewmate/Crusader.cs
  Roles/Crewmate/Jailer.cs
  Roles/Crewmate/Sheriff.cs
  Roles/Impostor/Eraser.cs
  Roles/Impostor/Mastermind.cs
  Roles/Neutral/Pursuer.cs
  main.cs
Labels: New Role/Add-on

#193 Add Skins In Camouflague (Me & @Gurge44)
  Modules/Camouflague.cs
  Modules/OptionHolder.cs
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
Labels: Some change

#195 changed a few count type and some changes in game end
  Modules/CustomRolesHelper.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Patches/CheckGameEndPatch.cs
  Resources/Lang/en_US.json
Labels: Fix bug, Enhancement

#185 Add Hurried
  Modules/CustomRolesHelper.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/CheckGameEndPatch.cs
  Resources/Lang/en_US.json
  Roles/AddOns/Crewmate/Hurried.cs
  Roles/Crewmate/Admirer.cs
  Roles/Neutral/Jackal.cs
  Roles/Neutral/Succubus.cs
  Roles/Neutral/Virus.cs
  main.cs
Labels: New Role/Add-on

#197 Sabotage Duration For All Map & Fix Disable Devices
  Modules/DisableDevice.cs
  Modules/OptionHolder.cs
  Patches/SabotageSystemPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
Labels: Fix bug, New Setting

#181 Add some pt-br translations on code(colors, commands, etc)
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
Labels: Add/Update Translation

#198 auto copy build
  Modules/SpamManager.cs
  Patches/ChatCommandPatch.cs
  TOHE.csproj
Labels: Some change, Add/Update Translation

#196 F ix converted win
  Modules/CustomWinnerHolder.cs
  Modules/GameState.cs
  Modules/GuessManager.cs
  Modules/Utils.cs
  Patches/CheckGameEndPatch.cs
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Roles/Crewmate/Admirer.cs
  Roles/Impostor/Gangster.cs
  Roles/Neutral/Collector.cs
  Roles/Neutral/Doomsayer.cs
  Roles/Neutral/Executioner.cs
  Roles/Neutral/Pirate.cs
  Roles/Neutral/Seeker.cs
  Roles/Neutral/SoulCollector.cs
  Roles/Neutral/Succubus.cs
Labels: Some change

#200 Disable Tasks In Fungle & Some Сhanges
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/ControlPatch.cs
  Patches/TaskAssignPatch.cs
  Resources/Lang/en_US.json
  TOHE.sln
Labels: Some change, New Setting

#201 Fix Doomsayer
  Modules/GuessManager.cs
Labels: Fix bug

#192 Apply Puid Ban System
  Modules/BanManager.cs
  Modules/CustomRoleSelector.cs
  Modules/EAC.cs
  Patches/ChatCommandPatch.cs
  Patches/ControlPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Resources/Config/EACList.txt
Labels: Some change

#202 template&DevManger.cs update
  Modules/DevManager.cs
  Resources/Config/template/TChinese.txt
Labels: Some change, Add/Update Translation

#203 Fix Pomelo's tag
  Modules/DevManager.cs
Labels: Some change

#204 New role Taskinator and made mario incompatible with unlucky
  Modules/CustomRolesHelper.cs
  Modules/DevManager.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/CheckGameEndPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Divinator.cs
  Roles/Neutral/Taskinator.cs
  main.cs
Labels: Some change, New Role/Add-on, Add/Update Translation

#205 fix taskinator postion, some roles seeing double id with guesser addon
  Modules/DevManager.cs
  Modules/Utils.cs
  Roles/Neutral/Taskinator.cs
Labels: Fix bug, Some change

#207 Trickster improvement and cyber incompatible with Doppelganger
  Modules/CustomRolesHelper.cs
  Patches/PlayerControlPatch.cs
  Roles/Crewmate/Reverie.cs
Labels: Fix bug, Improve Role/Add-on

#67 Enigma
  Modules/CustomRolesHelper.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Divinator.cs
  Roles/Crewmate/Enigma.cs
  main.cs
Labels: New Role/Add-on

#84 Instigator
  Modules/CustomRolesHelper.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/ExilePatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Divinator.cs
  Roles/Impostor/Instigator.cs
  main.cs
Labels: New Role/Add-on

#199 Add Randomizer (from: Night , Improvements: LezaiYa)
  Modules/CustomRolesHelper.cs
  Modules/OptionHolder.cs
  Patches/PlayerControlPatch.cs
  Resources/Config/EACList.txt
  Resources/Lang/en_US.json
  Resources/Lang/zh_CN.json
  Roles/Crewmate/Swapper.cs
  main.cs
Labels: New Role/Add-on, Add/Update Translation

#209 Role color from json
  Resources/roleColor.json
  main.cs
Labels: Some change

#210 Fixes and some changes
  Modules/OptionHolder.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Divinator.cs
  Roles/Crewmate/President.cs
  Roles/Crewmate/Spy.cs
  Roles/Crewmate/Swapper.cs
  Roles/Double/Mini.cs
  Roles/Impostor/Blackmailer.cs
  Roles/Impostor/Councillor.cs
  Roles/Impostor/Instigator.cs
  Roles/Impostor/Mastermind.cs
  Roles/Neutral/Bandit.cs
  Roles/Neutral/Doppelganger.cs
  Roles/Neutral/Pyromaniac.cs
Labels: Fix bug, Some change

#212 Role color from json
  Modules/DevManager.cs
  Patches/ControlPatch.cs
  main.cs
Labels: Some change, Enhancement

#213 Remove "Incompatible" role assign
  Modules/CustomRoleSelector.cs
  Modules/CustomRolesHelper.cs
  Modules/Utils.cs
  Resources/Lang/en_US.json
Labels: Fix bug, Some change

#217 Fix Killing Machine Vision & Try Fix /death Command For Host
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Patches/ChatCommandPatch.cs
Labels: Fix bug

#218 Fix Killing Machine Can Sabotage
  Patches/SabotageSystemPatch.cs
Labels: Fix bug

#219 New role Pixie, taskinator RPC fix
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/NameColorManager.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/CheckGameEndPatch.cs
  Patches/ExilePatch.cs
  Patches/IntroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/Crewmate/Divinator.cs
  Roles/Neutral/Pixie.cs
  Roles/Neutral/Taskinator.cs
  main.cs
Labels: Fix bug, New Role/Add-on

#221 Fix Bugs During Mushroom Mixup
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Patches/SabotageSystemPatch.cs
Labels: Fix bug

#222 changed some settings for reverie, egoist and paritycop
  Modules/CustomRolesHelper.cs
  Modules/OptionHolder.cs
  Resources/Lang/en_US.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fr_FR.json
  Resources/Lang/ja_JP.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
  Roles/Crewmate/ParityCop.cs
  Roles/Crewmate/Reverie.cs
Labels: Add/Update Translation, New Setting

#223 Fix Desync Impostor Reset Cooldown Sabotages
  Patches/SabotageSystemPatch.cs
Labels: Fix bug

#227 Fix Name In Meeting During Mushroom Mixup
  Modules/Utils.cs
Labels: Fix bug

#215 Recode Gangster
  Roles/Crewmate/Admirer.cs
  Roles/Impostor/Gangster.cs
Labels: Fix bug, Some change

#229 fix witness and innocent getting tasks after death and bait seting reworded
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
Labels: Fix bug, Add/Update Translation

#230 fix bloodlust not working
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
Labels: Fix bug, Add/Update Translation

#231 fix TOHE not loading when Language folder doesn't exist
  main.cs
Labels: Fix bug

#232 Update en_US.json
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#233 fix few RPC added italian translators & updated sponsor
  Modules/DevManager.cs
  Modules/GameState.cs
  Modules/RPC.cs
  Patches/CredentialsPatch.cs
  Roles/Crewmate/Bloodhound.cs
  Roles/Crewmate/Chameleon.cs
  Roles/Crewmate/Divinator.cs
  Roles/Crewmate/Mediumshiper.cs
  Roles/Crewmate/Oracle.cs
  Roles/Crewmate/ParityCop.cs
  Roles/Crewmate/Tracker.cs
  Roles/Neutral/Pixie.cs
Labels: Fix bug, Some change

#234 try fix OIIAI changed NK not able to copy role
  Roles/AddOns/Common/Oiiai.cs
Labels: Fix bug

#235 Improve overkiller
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/Impostor/OverKiller.cs
Labels: Improve Role/Add-on

#236 Fix Overseer Error
  Roles/Crewmate/Farseer.cs
Labels: Fix bug

#237 Mare No Longer Can Spawn On The Fungle Map
  Modules/CustomRoleSelector.cs
Labels: Some change

#238 Fix Executioner
  Modules/Utils.cs
  Patches/ExilePatch.cs
  Roles/Neutral/Executioner.cs
Labels: Fix bug

#240 Update en-US.json
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#187 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/ga_IE.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#244 Fix Necroview Cant See Cyber Team
  Modules/NameColorManager.cs
Labels: Fix bug

#245 Stalker No Longer Can Spawn On The Fungle Map
  Modules/CustomRoleSelector.cs
Labels: Fix bug

#243 Adding new settings and fixing bugs for mini
  Modules/ExtendedPlayerControl.cs
  Modules/RPC.cs
  Patches/ExilePatch.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Resources/Lang/zh_CN.json
  Roles/Double/Mini.cs
  main.cs
Labels: Fix bug

#246 Update en_US.json
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#251 Fix some bug
  Patches/ChatCommandPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Fix bug

#250 Again again improve overkiller
  Modules/ExtendedPlayerControl.cs
  Patches/PlayerControlPatch.cs
  Resources/Config/EACList.txt
  Roles/Impostor/OverKiller.cs
Labels: Fix bug, Improve Role/Add-on, Some change

#253 Patch system message from chat manager
  Modules/BanManager.cs
  Modules/ChatManager.cs
  Modules/GuessManager.cs
  Modules/MafiaRevengeManager.cs
  Modules/RetributionistRevengeManager.cs
  Modules/Utils.cs
  Patches/OutroPatch.cs
  Roles/Crewmate/Judge.cs
  Roles/Impostor/Councillor.cs
Labels: Fix bug

#255 Who dont like horses
  Patches/ClientOptionsPatch.cs
  Resources/Lang/en_US.json
  main.cs
Labels: New Setting

#256 Make influenced incompatible with collector
  Modules/CustomRolesHelper.cs
  Resources/Lang/en_US.json
Labels: Fix bug

#259 db to main
  .gitignore
  Patches/ClientPatch.cs
  Patches/MainMenuManagerPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Resources/Lang/en_US.json
  TOHE.csproj
  dbConnect.cs
  main.cs
Labels: Enhancement

#262 ver
  main.cs
Labels: Some change

#264 Remove overkiller latekill in afterreporttasks
  Modules/ExtendedPlayerControl.cs
  Patches/ClientOptionsPatch.cs
  Patches/MainMenuManagerPatch.cs
  Patches/PlayerControlPatch.cs
Labels: Fix bug, Some change

#268 Fix influenced and swapper
  Patches/MeetingHudPatch.cs
  Resources/Lang/en_US.json
  Roles/AddOns/Common/Influenced.cs
Labels: Fix bug

#269 updated dev manager to be handled by api
  Modules/DevManager.cs
  dbConnect.cs
  main.cs
Labels: Enhancement

#267 LavaChat fix
  Modules/ChatManager.cs
  Modules/GameState.cs
Labels: Fix bug

#265 Added /rand
  Patches/ChatCommandPatch.cs
Labels: Enhancement

#270 mini ejection screen
  Patches/MeetingHudPatch.cs
Labels: Some change

#271 actually add the strings for /rand
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#272 imitator CanUseKillButton error
  Roles/Neutral/Imitator.cs
Labels: Fix bug

#273 change ver
  main.cs
Labels: Some change

#274 fix non imp soulless wins with imps
  Patches/CheckGameEndPatch.cs
Labels: Fix bug

#278 Fix OIIAI neutral assign
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Roles/AddOns/Common/Oiiai.cs
Labels: Fix bug

#279 fix exile chat spam and option to not do it
  Modules/ChatManager.cs
  Modules/OptionHolder.cs
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
Labels: Fix bug, New Setting

#280 changed command check conditions for multiple roles
  Modules/GuessManager.cs
  Roles/Crewmate/Judge.cs
  Roles/Crewmate/ParityCop.cs
  Roles/Crewmate/President.cs
  Roles/Crewmate/Swapper.cs
  Roles/Impostor/Councillor.cs
  Roles/Neutral/Pirate.cs
Labels: Fix bug, Some change

#282 updated default template and some bug fixes
  Modules/DevManager.cs
  Modules/GameState.cs
  Modules/TemplateManager.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/ControlPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/ShipStatusPatch.cs
  Resources/Config/template/Brazilian.txt
  Resources/Config/template/Dutch.txt
  Resources/Config/template/English.txt
  Resources/Config/template/French.txt
  Resources/Config/template/Japanese.txt
  Resources/Config/template/Latam.txt
  Resources/Config/template/Russian.txt
  Resources/Config/template/SChinese.txt
  Resources/Config/template/Spanish.txt
  Resources/Config/template/TChinese.txt
  Resources/Lang/en_US.json
  Roles/Crewmate/Alchemist.cs
  Roles/Impostor/Puppeteer.cs
  Roles/Neutral/Agitater.cs
  Roles/Neutral/FFF.cs
  Roles/Neutral/Infectious.cs
  Roles/Neutral/Shroud.cs
Labels: Fix bug, Some change

#281 Rewriting ChatCommandPatch
  Patches/ChatCommandPatch.cs
Labels: Some change

#284 fix dev access
  dbConnect.cs
Labels: Fix bug
