Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2024-06, with the labels that each got.

#967 Add missing rpc
  Roles/Impostor/EvilTracker.cs
  Roles/Impostor/Kamikaze.cs
  Roles/Neutral/Virus.cs
Labels: Fix bug

#966 Fix some bugs in dev24
  Roles/Crewmate/Knight.cs
  Roles/Crewmate/Sheriff.cs
  Roles/Impostor/Eraser.cs
  Roles/Impostor/Gangster.cs
  Roles/Impostor/Vampire.cs
Labels: Fix bug

#970 Delay & remove chats for green beans
  Patches/ChatCommandPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Fix bug

#962 Display Role Info For Vanilla on intro
  Modules/Utils.cs
Labels: Enhancement

#964 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/it_IT.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#955 Fix else statement in last pr
  Patches/InnerNetClientPatch.cs
Labels: Fix bug

#972 Players Know All Roles When Game End
  Modules/ExtendedPlayerControl.cs
  Patches/CheckGameEndPatch.cs
  Patches/onGameStartedPatch.cs
Labels: Enhancement

#975 Try fix black screen during assign roles
  Patches/onGameStartedPatch.cs
Labels: Fix bug

#976 Make /s show the sender's name
  Modules/ExtendedPlayerControl.cs
  Patches/ChatCommandPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Some change

#977 Update a lot of Descriptions in en_US.json
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#961 Doppelganger Code Overhaul
  Modules/ExtendedPlayerControl.cs
  Modules/NameColorManager.cs
  Modules/Utils.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Core/CustomRoleManager.cs
  Roles/Crewmate/FortuneTeller.cs
  Roles/Crewmate/Lookout.cs
  Roles/Impostor/DollMaster.cs
  Roles/Neutral/Doppelganger.cs
Labels: Improve Role/Add-on

#980 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#963 Add rpcsetoutfit method and some Dollmaster fix
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/Utils.cs
  Patches/IntroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/Impostor/DollMaster.cs
  main.cs
Labels: Fix bug

#981 Update en_US.json once more
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#984 Host Info in Meeting Fix For Doppelganger & Comms
  Patches/ShowHostMeetingPatch.cs
Labels: Fix bug

#986 Doppelganger Host Fixes
  Modules/ExtendedPlayerControl.cs
Labels: Fix bug

#982 Ghastly stuff and kamikaze fix
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/CheckGameEndPatch.cs
  Patches/IntroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/(Ghosts)/Crewmate/Ghastly.cs
  Roles/Core/AssignManager/GhostRoleAssign.cs
  Roles/Core/RoleBase.cs
  Roles/Impostor/Chronomancer.cs
  Roles/Impostor/Kamikaze.cs
Labels: Fix bug

#983 Fix "*" for role descriptions.
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#988 New PlayerControl function to get vent ID
  Modules/ExtendedPlayerControl.cs
  Modules/GuessManager.cs
  Roles/Impostor/DollMaster.cs
Labels: Some change

#987 New Crowdin updates
  Resources/Announcements/modNews-ja_JP.json
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#991 Medic RPC Sync Fix
  Roles/Crewmate/Medic.cs
Labels: Fix bug

#994 Get rid of strings for unused roles
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#997 Fixed DollMaster being killed by ImpTeam
  Roles/Impostor/DollMaster.cs
Labels: Fix bug

#1001 Some improvements
  Modules/ExtendedPlayerControl.cs
  Patches/PlayerControlPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/AddOns/Common/Unlucky.cs
  Roles/Core/CustomRoleManager.cs
  Roles/Neutral/Bandit.cs
Labels: Improve Code

#998 Updated More Stuff for en_US.json.
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#1000 "We can't lose the TOHE-Background-Old.jpg".jpg
  Resources/Background/TOHE-Background-Old.jpg
Labels: Fix bug, Improve Role/Add-on, Some change, Enhancement, New Role/Add-on, invalid, Rework Role/Add-on, wontfix, Add/Update Translation, New Setting, Remove Role/Add-on, In Progress, Update README, Update Mod (v2023.10.24), Other, Improve Code, Ask, Bug Report, idk what it is, Merge to main, Port from TOH, Port from EHR, Port from TOH-Y, Update Mod (v2024.3.5), Some improvements, New command

#1007 Side kick can kill jackal setting not working
  Roles/Neutral/Jackal.cs
Labels: Fix bug

#1006 Rename some harmony functions and enums to bypass Dotfuscator renaming
  Modules/DoorsReset.cs
  Modules/ModUpdater.cs
  Modules/OptionHolder.cs
  Patches/AnnouncementPatch.cs
  Patches/AprilFoolsModePatch.cs
  Patches/MainMenuManagerPatch.cs
  Patches/MovingPlatformBehaviourPatch.cs
  Patches/ShowHostMeetingPatch.cs
  Roles/AddOns/Common/Oiiai.cs
  Roles/Crewmate/Medic.cs
  Roles/Crewmate/Sheriff.cs
  Roles/Impostor/Godfather.cs
  Roles/Impostor/Vampire.cs
  Roles/Impostor/Witch.cs
  Roles/Neutral/Amnesiac.cs
  Roles/Neutral/Bandit.cs
  Roles/Neutral/Cultist.cs
  Roles/Neutral/Executioner.cs
  Roles/Neutral/HexMaster.cs
  Roles/Neutral/Imitator.cs
  Roles/Neutral/Jackal.cs
  Roles/Neutral/Lawyer.cs
  Roles/Neutral/Virus.cs
Labels: Some change

#1004 allow players to be banned by only using first name
  Modules/BanManager.cs
Labels: Enhancement

#1009 Change Role Name Size
  Modules/Utils.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
Labels: Some change

#1008 Fix swift & berserker interaction(s)
  Modules/CustomRolesHelper.cs
  Roles/AddOns/Impostor/Swift.cs
  Roles/Core/CustomRoleManager.cs
  Roles/Impostor/Kamikaze.cs
Labels: Fix bug

#1010 Added new Shaman Note TommyXL just added, plus more updates.
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#1003 Add notify
  Modules/RPC.cs
  Modules/Translator.cs
  Patches/OutroPatch.cs
  Patches/PlayerControlPatch.cs
  Roles/Core/CustomRoleManager.cs
Labels: Some change

#1011 Update Icons
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#1014 Fix Swift with Lightning and Hangman
  Modules/CustomRolesHelper.cs
Labels: Fix bug

#1015 Fix killtimer not going when press f1
  Modules/ExtendedPlayerControl.cs
  Patches/ControlPatch.cs
  Patches/DialogueBoxPatch.cs
Labels: Fix bug

#1016 Remove double shot from doomsayer if can't die on missguess
  Modules/CustomRolesHelper.cs
  Roles/Neutral/Doomsayer.cs
Labels: Fix bug

#1017 New Crowdin updates
  Resources/Lang/ru_RU.json
Labels: Add/Update Translation

#1022 i had uncomitted changes
  Patches/GameStartManagerPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Update Mod (v2024.6.18)

#1023 fix cancel button
  Patches/GameStartManagerPatch.cs
Labels: Fix bug, Update Mod (v2024.6.18)

#1026 Update some rpc calls
  Modules/Camouflague.cs
  Modules/ChatManager.cs
  Modules/CustomRolesHelper.cs
  Modules/CustomRpcSender.cs
  Modules/EAC.cs
  Modules/ExtendedPlayerControl.cs
  Modules/RPC.cs
  Patches/ChatCommandPatch.cs
  Patches/InnerNetClientPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/TaskAssignPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/AddOns/Common/Rainbow.cs
  Roles/Crewmate/Spiritualist.cs
  Roles/Impostor/Devourer.cs
  Roles/Neutral/Doppelganger.cs
  Roles/Neutral/Spiritcaller.cs
Labels: Update Mod (v2024.6.18)

#1025 Add buttons and remove GamePreset
  Patches/GameOptionsMenuPatch.cs
  Resources/Lang/en_US.json
Labels: Update Mod (v2024.6.18)

#1028 Rename Masochist to Punching Bag
  Modules/CustomRolesHelper.cs
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/Neutral/PunchingBag.cs
  main.cs
Labels: Some change

#1027 Dollmaster Cosmetic swap fix + More
  Roles/Impostor/DollMaster.cs
  Roles/Neutral/Doppelganger.cs
Labels: Fix bug

#1030 Fix real client name
  Modules/ExtendedPlayerControl.cs
  Modules/RPC.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  main.cs
Labels: Fix bug

#1029 Adjust some hud (+ add our preset and lobbytimer fix)
  Patches/GameOptionsMenuPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/LobbyPatch.cs
Labels: Fix bug

#1032 Fix phantom cmds and check task complete
  Patches/NoBlackoutPatch.cs
  Patches/PlayerControlPatch.cs
Labels: Update Mod (v2024.6.18)

#1033 TOHE Dropship Decorations
  Patches/ClientOptionsPatch.cs
  Patches/LobbyPatch.cs
  Patches/ShipStatusPatch.cs
  Resources/Images/Dropship-Decorations.png
  Resources/Lang/en_US.json
  main.cs
Labels: Enhancement

#1031 Rename Bloodlust to Bloodthirst
  Modules/CustomRolesHelper.cs
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/AddOns/Crewmate/Bloodthirst.cs
  Roles/Crewmate/Alchemist.cs
  main.cs
Labels: Add/Update Translation

#1034 Fixed lobby decoration display for v2024.6.18
  Patches/LobbyPatch.cs
Labels: Fix bug

#1041 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1043 Disable Desync Roles From Getting ghost-roles
  Roles/Core/AssignManager/GhostRoleAssign.cs
Labels: Fix bug

#1045 Change color id to byte
  Modules/Camouflague.cs
  Modules/ExtendedPlayerControl.cs
  Roles/AddOns/Common/Rainbow.cs
  Roles/Impostor/Devourer.cs
  Roles/Impostor/DollMaster.cs
  Roles/Neutral/Doppelganger.cs
Labels: Some change

#1042 remove and fix a few things in en_US.json file
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#1047 UI for settings (Ported from TOH-Y and optimazed from EHR)
  Modules/OptionHolder.cs
  Modules/OptionItem/OptionItem.cs
  Modules/OptionItem/PresetOptionItem.cs
  Modules/OptionItem/StringOptionItem.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/GameSettingMenuPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  README.md
  Resources/Lang/en_US.json
Labels: Port from EHR, Port from TOH-Y, Update Mod (v2024.6.18)

#1050 Fix Paranoia strings
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#1049 Add Oiiai.wav to OIIAI and Eraser skill
  Resources/Sounds/Oiiai.wav
  Roles/AddOns/Common/Oiiai.cs
  Roles/Impostor/Eraser.cs
Labels: Some improvements

#1051 Change version check
  Modules/RPC.cs
  Patches/ClientPatch.cs
  Patches/IntroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Fix bug
