Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2024-12, with the labels that each got.

#1304 Announcement updates
  Resources/Announcements/modNews-en_US.json
Labels: Add/Update Translation

#1302 Fix Horse Mode crashing the game
  Patches/AprilFoolsModePatch.cs
  Patches/ChatCommandPatch.cs
  Patches/ChatControlPatch.cs
  Patches/ClientOptionsPatch.cs
  Patches/IntroPatch.cs
  main.cs
Labels: Fix bug

#1287 eac upgrade
  Modules/EAC.cs
  Modules/RPC.cs
Labels: Other

#1319 Add Legacy Version setting for Parasite & Additions
  .github/workflows/build.yml
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
  Roles/Impostor/Parasite.cs
  Roles/Neutral/Traitor.cs
Labels: Improve Role/Add-on

#1320 Global remove playerids
  Roles/(Ghosts)/Crewmate/GuardianAngelTOHE.cs
  Roles/(Ghosts)/Impostor/Minion.cs
  Roles/Core/CustomRoleManager.cs
  Roles/Impostor/Bard.cs
  Roles/Impostor/Bomber.cs
  Roles/Impostor/Butcher.cs
  Roles/Impostor/Camouflager.cs
  Roles/Impostor/Cleaner.cs
  Roles/Impostor/Consigliere.cs
  Roles/Impostor/Crewpostor.cs
  Roles/Impostor/Dazzler.cs
  Roles/Impostor/Deathpact.cs
  Roles/Impostor/Devourer.cs
  Roles/Impostor/Disperser.cs
  Roles/Impostor/Escapist.cs
  Roles/Impostor/EvilGuesser.cs
  Roles/Impostor/Godfather.cs
  Roles/Impostor/Inhibitor.cs
  Roles/Impostor/KillingMachine.cs
  Roles/Impostor/Ludopath.cs
  Roles/Impostor/Miner.cs
  Roles/Impostor/Nemesis.cs
  Roles/Impostor/Puppeteer.cs
  Roles/Impostor/Refugee.cs
  Roles/Impostor/Saboteur.cs
  Roles/Impostor/Scavenger.cs
  Roles/Impostor/ShapeMaster.cs
  Roles/Impostor/SoulCatcher.cs
  Roles/Impostor/Trapster.cs
  Roles/Impostor/Trickster.cs
  Roles/Impostor/Underdog.cs
  Roles/Neutral/Arsonist.cs
  Roles/Neutral/Berserker.cs
  Roles/Neutral/Infectious.cs
  Roles/Neutral/Innocent.cs
  Roles/Neutral/Jackal.cs
  Roles/Neutral/Opportunist.cs
  Roles/Neutral/Provocateur.cs
  Roles/Neutral/PunchingBag.cs
  Roles/Neutral/Revolutionist.cs
  Roles/Neutral/Specter.cs
  Roles/Neutral/Sunnyboy.cs
  Roles/Neutral/Terrorist.cs
  Roles/Neutral/Vector.cs
  Roles/Neutral/Workaholic.cs
Labels: Improve Code

#1321 Change ability button text for some roles
  Patches/GameStartManagerPatch.cs
  Patches/IntroPatch.cs
  Resources/Lang/en_US.json
  Roles/AddOns/Common/Sloth.cs
  Roles/Impostor/AbyssBringer.cs
  Roles/Impostor/Pitfall.cs
  Roles/Impostor/RiftMaker.cs
Labels: Improve Role/Add-on, Some change

#1331 Fix typo
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#1323 New Crowdin updates
  Resources/Announcements/modNews-it_IT.json
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation
