Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2024-08, with the labels that each got.

#1133 Fix Fortune Teller Showin not assigned role
  Roles/Crewmate/FortuneTeller.cs
Labels: Fix bug

#1135 New Crowdin updates
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1136 New Crowdin updates
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#815 Neutral Apocalypse
  Modules/AntiBlackout.cs
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/GuessManager.cs
  Modules/MeetingTimeManager.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/(Ghosts)/Crewmate/Hawk.cs
  Roles/(Ghosts)/Impostor/Bloodmoon.cs
  Roles/AddOns/Common/Burst.cs
  Roles/AddOns/Common/Susceptible.cs
  Roles/AddOns/Crewmate/Ghoul.cs
  Roles/Core/AssignManager/RoleAssign.cs
  Roles/Crewmate/Alchemist.cs
  Roles/Crewmate/Captain.cs
  Roles/Crewmate/CopyCat.cs
  Roles/Crewmate/Deceiver.cs
  Roles/Crewmate/Jailer.cs
  Roles/Crewmate/Judge.cs
  Roles/Crewmate/Psychic.cs
  Roles/Crewmate/Randomizer.cs
  Roles/Crewmate/Retributionist.cs
  Roles/Crewmate/Sheriff.cs
  Roles/Crewmate/Snitch.cs
  Roles/Crewmate/Veteran.cs
  Roles/Impostor/Berserker.cs
  Roles/Impostor/Bomber.cs
  Roles/Impostor/Councillor.cs
  Roles/Impostor/Crewpostor.cs
  Roles/Impostor/CursedWolf.cs
  Roles/Impostor/Hangman.cs
  Roles/Impostor/Nemesis.cs
  Roles/Impostor/Trapster.cs
  Roles/Neutral/Amnesiac.cs
  Roles/Neutral/Baker.cs
  Roles/Neutral/Berserker.cs
  Roles/Neutral/Demon.cs
  Roles/Neutral/Executioner.cs
  Roles/Neutral/HexMaster.cs
  Roles/Neutral/Infectious.cs
  Roles/Neutral/Jinx.cs
  Roles/Neutral/Lawyer.cs
  Roles/Neutral/Pelican.cs
  Roles/Neutral/PlagueBearer.cs
  Roles/Neutral/Shroud.cs
  Roles/Neutral/SoulCollector.cs
  Roles/Neutral/Werewolf.cs
  main.cs
Labels: Improve Role/Add-on

#934 TextBoxPatch (Port from EHR)
  Patches/ChatCommandPatch.cs
  Patches/ChatControlPatch.cs
  Patches/TextBoxPatch.cs
  README.md
Labels: Enhancement, Port from EHR

#959 Disable ShapeShift Menu for Reject Shapeshift roles
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/Utils.cs
  Patches/IntroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/Core/CustomRoleManager.cs
  Roles/Core/RoleBase.cs
  Roles/Impostor/Bomber.cs
  Roles/Impostor/Pitfall.cs
  Roles/Impostor/Undertaker.cs
  main.cs
Labels: Enhancement

#1038 "Shield Person Died First" Rework
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  main.cs
Labels: Rework Setting

#918 Cancel Vote System
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/MeetingHudPatch.cs
  Resources/Config/template/English.txt
  Resources/Lang/en_US.json
  Roles/Core/RoleBase.cs
  Roles/Crewmate/Cleanser.cs
  Roles/Crewmate/FortuneTeller.cs
  Roles/Crewmate/Keeper.cs
  Roles/Crewmate/Oracle.cs
  Roles/Crewmate/Tracker.cs
  Roles/Impostor/Eraser.cs
  Roles/Impostor/Godfather.cs
  Roles/Neutral/Jester.cs
  Roles/Neutral/SoulCollector.cs
Labels: Enhancement

#1141 /apocalypseinfo command
  Patches/ChatCommandPatch.cs
  Patches/MeetingHudPatch.cs
  Resources/Lang/en_US.json
  Roles/Neutral/Berserker.cs
Labels: New command

#1140 Fix Neutral Apocalypse Guess Setting being inverted
  Roles/Neutral/Baker.cs
  Roles/Neutral/Berserker.cs
  Roles/Neutral/SoulCollector.cs
Labels: Fix bug

#1143 Update Api Error Connection Message
  Modules/dbConnect.cs
  Resources/Lang/en_US.json
Labels: Some change

#1144 (README.MD) Update Invalid Links. Proper crediting.
  README.md
Labels: Update README

#1115 Some UI Adittions and search bar (🙀🙀🙀)
  Modules/Extensions/CollectionExtensions.cs
  Modules/OptionHolder.cs
  Modules/OptionItem/OptionItem.cs
  Patches/ChatBubblePatch.cs
  Patches/ControlPatch.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/GameSettingMenuPatch.cs
  Patches/TextBoxPatch.cs
  Resources/Images/PresetBox.png
  Resources/Images/SearchIcon.png
  Resources/Images/SearchIconActive.png
  Resources/Images/SearchIconHover.png
  Resources/Lang/en_US.json
Labels: Enhancement

#1149 fix null error
  Modules/OptionHolder.cs
Labels: Fix bug

#1150 Better RegionMenu
  Patches/RegionMenuPatch.cs
Labels: Enhancement

#1148 New Role: Troller (Neutral Chaos)
  Modules/DoorsReset.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Patches/CheckGameEndPatch.cs
  Patches/ControlPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/Crewmate/Alchemist.cs
  Roles/Crewmate/Investigator.cs
  Roles/Crewmate/Mechanic.cs
  Roles/Impostor/Mastermind.cs
  Roles/Impostor/Twister.cs
  Roles/Neutral/Troller.cs
  main.cs
Labels: New Role/Add-on

#1153 /apocinfo alias for /apocalypseinfo
  Patches/ChatCommandPatch.cs
Labels: Some change

#1142 New Crowdin updates
  Resources/Announcements/modNews-zh_CN.json
  Resources/Lang/es_419.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1156 Return Strings
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/RPC.cs
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
Labels: Fix bug

#1157 Fix Egoist win text
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#1159 Temporarily disable "Fix Texbox Cursor" Patch
  Patches/TextBoxPatch.cs
Labels: Some change

#1160 Brin it back LOL 💀
  Patches/TextBoxPatch.cs
Labels: Some change

#1158 Update 2024.8.13
  Patches/ExilePatch.cs
  Patches/GameOptionsMenuPatch.cs
  TOHE.csproj
  main.cs
Labels: Update Mod (v2024.8.13)

#1161 Fix Textboxpatch and Fix SetupHelpIcon
  Modules/RPC.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/TextBoxPatch.cs
  TOHE.csproj
Labels: Fix bug, Update Mod (v2024.8.13)

#1166 Show NA on Eject + NA Guess NA Setting
  Modules/OptionHolder.cs
  Patches/MeetingHudPatch.cs
  Resources/Lang/en_US.json
  Roles/Neutral/Baker.cs
  Roles/Neutral/Berserker.cs
  Roles/Neutral/PlagueBearer.cs
  Roles/Neutral/SoulCollector.cs
Labels: New Setting

#1163 New Crowdin updates
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1169 New Crowdin updates
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1168 2.1.0 Translation merged into main
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#1125 New Imposter Role: Double Agent
  Modules/CustomRolesHelper.cs
  Resources/Images/Skills/DoubleAgentPocketBomb.png
  Resources/Lang/en_US.json
  Roles/Crewmate/Bastion.cs
  Roles/Impostor/DoubleAgent.cs
  Roles/Neutral/Agitater.cs
  main.cs
Labels: New Role/Add-on

#1162 New Imposter Ghost Role: Possessor
  Modules/CustomRolesHelper.cs
  Resources/Lang/en_US.json
  Roles/(Ghosts)/Impostor/Possessor.cs
  main.cs
Labels: New Role/Add-on

#1172 New Role: Double Agent & Possessor (By D1GQ)
  Modules/CustomRolesHelper.cs
  Modules/DisableDevice.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/LadderPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/SabotageSystemPatch.cs
  Patches/UsablesPatch.cs
  Resources/Images/Skills/DoubleAgentPocketBomb.png
  Resources/Lang/en_US.json
  Roles/(Ghosts)/Impostor/Possessor.cs
  Roles/AddOns/Common/Glow.cs
  Roles/AddOns/Common/Radar.cs
  Roles/AddOns/Common/Spurt.cs
  Roles/AddOns/Common/Statue.cs
  Roles/Crewmate/Alchemist.cs
  Roles/Crewmate/Bastion.cs
  Roles/Crewmate/Bodyguard.cs
  Roles/Crewmate/Mortician.cs
  Roles/Crewmate/Overseer.cs
  Roles/Crewmate/SuperStar.cs
  Roles/Crewmate/Telecommunication.cs
  Roles/Impostor/AntiAdminer.cs
  Roles/Impostor/Bomber.cs
  Roles/Impostor/Crewpostor.cs
  Roles/Impostor/Deathpact.cs
  Roles/Impostor/DoubleAgent.cs
  Roles/Impostor/Fireworker.cs
  Roles/Impostor/Lightning.cs
  Roles/Impostor/Pitfall.cs
  Roles/Impostor/Puppeteer.cs
  Roles/Impostor/RiftMaker.cs
  Roles/Impostor/Warlock.cs
  Roles/Neutral/Agitater.cs
  Roles/Neutral/Arsonist.cs
  Roles/Neutral/Berserker.cs
  Roles/Neutral/Pelican.cs
  Roles/Neutral/Revolutionist.cs
  Roles/Neutral/Shroud.cs
  Roles/Neutral/Solsticer.cs
  Roles/Neutral/Vulture.cs
  Roles/Neutral/Werewolf.cs
  main.cs
Labels: New Role/Add-on

#1167 Add YinYanger
  Modules/GameState.cs
  Resources/Lang/en_US.json
  Roles/Impostor/YinYanger.cs
  main.cs
Labels: New Role/Add-on

#1173 Fix typo in the icons
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#1175 Add note for CopyCat
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#1171 Add Rebirth
  Modules/Camouflague.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/OutfitManager.cs
  Modules/RPC.cs
  Patches/MeetingHudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/ShowHostMeetingPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/AddOns/Common/Rebirth.cs
  Roles/Impostor/Blackmailer.cs
  Roles/Neutral/Doppelganger.cs
  main.cs
Labels: New Role/Add-on

#1176 Spurt rpc
  Modules/RPC.cs
  Roles/AddOns/Common/Spurt.cs
Labels: Fix bug

#1178 Fxi rebirth setting
  Roles/AddOns/Common/Rebirth.cs
Labels: Fix bug

#1185 Improve DoubleAgent Role description
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#1182 Role Basis Changer (port from TOH-Y)
  Modules/AntiBlackout.cs
  Modules/CustomRpcSender.cs
  Modules/EAC.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/RoleBasisChanger.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/ExilePatch.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/TaskAdderPatch.cs
  Patches/onGameStartedPatch.cs
  README.md
  Resources/Lang/en_US.json
  Roles/Core/AssignManager/GhostRoleAssign.cs
  Roles/Core/CustomRoleManager.cs
  Roles/Core/RoleBase.cs
  Roles/Crewmate/Sheriff.cs
Labels: Enhancement, In Progress, Port from TOH-Y

#1189 Try Fix Phantom For Desync Roles (PhantomRolePatch.cs)
  Modules/ExtendedPlayerControl.cs
  Modules/RPC.cs
  Patches/ExilePatch.cs
  Patches/PhantomRolePatch.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/Core/AssignManager/RoleAssign.cs
  Roles/Vanilla/EngineerTOHE.cs
  Roles/Vanilla/PhantomTOHE.cs
  Roles/Vanilla/TrackerTOHE.cs
Labels: Fix bug

#1188 Better AntiBlackout
  Modules/AntiBlackout.cs
  Patches/ExilePatch.cs
  Patches/PlayerControlPatch.cs
Labels: Enhancement

#1184 New Add-on: Evader
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/MeetingHudPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/AddOns/Common/Evader.cs
  Roles/AddOns/Common/Rebirth.cs
  Roles/Core/RoleBase.cs
  Roles/Crewmate/Deceiver.cs
  Roles/Crewmate/FortuneTeller.cs
  Roles/Crewmate/Medium.cs
  Roles/Crewmate/Pacifist.cs
  Roles/Crewmate/President.cs
  Roles/Crewmate/Witness.cs
  Roles/Neutral/Pursuer.cs
  main.cs
Labels: New Role/Add-on

#1192 Fix Chronomancer bar not changing for mod clients
  Roles/Impostor/Chronomancer.cs
Labels: Fix bug

#1194 Fix Investigator red name not working on modded clients
  Roles/Crewmate/Investigator.cs
Labels: Fix bug

#1190 Update en_US.json (Evader Mostly)
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#1183 Fix AntiBlackOut Rpc releated bugs
  Modules/GameState.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ControlPatch.cs
  Patches/DiscordPatch.cs
  Patches/GameStartManagerPatch.cs
  Resources/Lang/en_US.json
Labels: Fix bug

#1195 Improvements for DisableUseVentForVanilla
  Modules/ExtendedPlayerControl.cs
  Patches/IntroPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/VentSystemPatch.cs
Labels: Enhancement

#1174 Add Mage
  Modules/Extensions/CollectionExtensions.cs
  Modules/OutfitManager.cs
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/Core/RoleBase.cs
  Roles/Crewmate/Mage.cs
  main.cs
Labels: New Role/Add-on
