Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2024-03, with the labels that each got.

#714 New Crowdin updates
  Resources/Announcements/modNews-it_IT.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#705 revert nemesis & retributionst
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/(Ghosts)/Crewmate/Hawk.cs
  Roles/(Ghosts)/Crewmate/Warden.cs
  Roles/(Ghosts)/Impostor/Bloodmoon.cs
  Roles/AddOns/Impostor/Madmate.cs
  Roles/Core/AssignManager/GhostRoleAssign.cs
  Roles/Crewmate/CopyCat.cs
  Roles/Crewmate/Divinator.cs
  Roles/Crewmate/Retributionist.cs
  Roles/Impostor/Gangster.cs
  Roles/Impostor/Nemesis.cs
  main.cs
Labels: Some change, New Role/Add-on

#723 Fix text when settings are loading
  Patches/CredentialsPatch.cs
  Patches/MainMenuManagerPatch.cs
  Resources/Lang/en_US.json
  main.cs
Labels: Fix bug

#721 Add Dleks in Map Picker Menu (Thanks Submerged sourse code)
  Patches/MapPickerMenuPatch.cs
Labels: Enhancement

#726 Fix susceptible making role visisble to others
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#728 Fix Plague Scientist typo
  Resources/Lang/en_US.json
Labels: Some change

#730 Support AU v2024.3.5
  Patches/AprilFoolsModePatch.cs
  Patches/ClientOptionsPatch.cs
  Patches/DiscordPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/HorseModePatch.cs
  TOHE.csproj
  main.cs
Labels: Update Mod (v2024.3.5)

#734 options to disable /tpin, /tpout and mini games
  Modules/OptionHolder.cs
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
Labels: New Setting

#742 remove SeverAddManager.cs
  Modules/ServerAddManager.cs
  README.md
  main.cs
Labels: Some change

#745 Small Fix
  Patches/OutroPatch.cs
  Roles/Core/AssignManager/GhostRoleAssign.cs
Labels: Fix bug

#733 Recode random spawn (Code ported from TOH)
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Modules/OptionItem/BooleanOptionItem.cs
  Modules/OptionItem/FloatOptionItem.cs
  Modules/OptionItem/IntegerOptionItem.cs
  Modules/OptionItem/StringOptionItem.cs
  Modules/Utils.cs
  Patches/AirshipStatus.cs
  Patches/ExilePatch.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/RandomSpawnPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/Neutral/Solsticer.cs
Labels: Port from TOH

#743 remove unused strings (Thanks to kevoutings for providing all the unused strings)
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#749 RoleBase: Pixie
  Modules/ExtendedPlayerControl.cs
  Modules/NameColorManager.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ExilePatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/Core/CustomRoleManager.cs
  Roles/Neutral/Pixie.cs
Labels: Improve Code

#752 Try fix assign ghost role
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/Core/AssignManager/GhostRoleAssign.cs
Labels: Fix bug

#754 Move DoubleTrigger OnFixedUpdate
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#753 Only rpcset ghostroles in dieplayer patch & some fixes
  Patches/PlayerControlPatch.cs
  Roles/Core/AssignManager/GhostRoleAssign.cs
Labels: Fix bug

#757 Return Used Strings
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#756 fix number chances, <color=
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#759 Change lastSequenceId for clients (Hotfix rpc teleport)
  Modules/ExtendedPlayerControl.cs
Labels: Fix bug

#739 Fix lawyer
  Modules/Utils.cs
  Patches/ExilePatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Resources/Lang/en_US.json
  Roles/Neutral/Lawyer.cs
Labels: Fix bug

#750 Merge role skill rpc into one
  Modules/RPC.cs
  Modules/Utils.cs
  Roles/Double/Mini.cs
  Roles/Impostor/Councillor.cs
  Roles/Impostor/Lightning.cs
  Roles/Neutral/Agitater.cs
  Roles/Neutral/Amnesiac.cs
  Roles/Neutral/Bandit.cs
  Roles/Neutral/BloodKnight.cs
  Roles/Neutral/Collector.cs
  Roles/Neutral/Demon.cs
  Roles/Neutral/Doomsayer.cs
  Roles/Neutral/Doppelganger.cs
  Roles/Neutral/Huntsman.cs
  Roles/Neutral/Imitator.cs
  Roles/Neutral/Jackal.cs
  Roles/Neutral/Lawyer.cs
  Roles/Neutral/Pelican.cs
  Roles/Neutral/Pirate.cs
  Roles/Neutral/Pixie.cs
  Roles/Neutral/PlagueBearer.cs
  Roles/Neutral/PlagueDoctor.cs
  Roles/Neutral/PotionMaster.cs
  Roles/Neutral/Pursuer.cs
  Roles/Neutral/Quizmaster.cs
  Roles/Neutral/Romantic.cs
  Roles/Neutral/SchrodingersCat.cs
  Roles/Neutral/Seeker.cs
  Roles/Neutral/Shroud.cs
  Roles/Neutral/Solsticer.cs
  Roles/Neutral/SoulCollector.cs
  Roles/Neutral/Spiritcaller.cs
  Roles/Neutral/Succubus.cs
  Roles/Neutral/Taskinator.cs
  Roles/Neutral/Totocalcio.cs
  Roles/Neutral/Virus.cs
  Roles/Neutral/Wraith.cs
Labels: Improve Code

#761 New Crowdin updates
  Resources/Lang/fr_FR.json
  Resources/Lang/ru_RU.json
Labels: Add/Update Translation

#762 Fix Invalid Strings Quiz Master
  Roles/Neutral/Quizmaster.cs
Labels: Fix bug

#764 Fix RpcTeleport & Random Spawn In Airship
  Modules/ExtendedPlayerControl.cs
  Patches/ShipStatusPatch.cs
  Roles/Impostor/Penguin.cs
Labels: Fix bug

#763 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/fr_FR.json
  Resources/Lang/ja_JP.json
Labels: Add/Update Translation

#765 Msg for users
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
Labels: Some change

#766 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/en_US.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#768 Increase character limit for sending chat messages
  Patches/ChatCommandPatch.cs
Labels: Some change

#769 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#771 fix mole not working on fungle
  Roles/Crewmate/Mole.cs
Labels: Fix bug

#772 remove ejected from tricky random death reason
  Roles/AddOns/Impostor/Tricky.cs
Labels: Fix bug

#773 fix imitator having vanilla cooldown
  Modules/ExtendedPlayerControl.cs
Labels: Fix bug

#774 fix addon rate always showing 100% when player does /r
  Modules/OptionShower.cs
  Modules/Utils.cs
Labels: Fix bug

#778 new setting revert to old kill log and fix addon percentage
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Modules/Utils.cs
  Resources/Lang/en_US.json
Labels: Fix bug, Some change, Add/Update Translation, New Setting

#775 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_ES.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/nl_NL.json
Labels: Add/Update Translation

#781 change version
  main.cs
Labels: Some change

#782 fix mayor can call meeting even when limit is over
  Roles/Crewmate/Mayor.cs
Labels: Fix bug
