Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2024-01, with the labels that each got.

#388 Add some chinese regions
  Modules/ServerAddManager.cs
Labels: Some change

#389 Correcting translation and string conflicts
  Patches/ChatCommandPatch.cs
Labels: Add/Update Translation

#391 fix spelling
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#393 Some Fixes & Improvements
  Modules/Camouflague.cs
  Modules/DisableDevice.cs
  Modules/ExtendedPlayerControl.cs
  Modules/NameNotifyManager.cs
  Modules/Utils.cs
  Patches/CheckGameEndPatch.cs
  Patches/ControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Fix bug, Some change, Improve Code

#394 keeper dual vote and fix pixie bug
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Keeper.cs
  Roles/Neutral/Pixie.cs
Labels: Fix bug, Enhancement, Add/Update Translation

#396 captain no. of task required settings to slow and reveal
  Modules/Utils.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Captain.cs
Labels: Fix bug, New Setting

#400 Basic fix for EAC
  Modules/ChatManager.cs
  Modules/EAC.cs
  Modules/OptionHolder.cs
  Patches/ChatCommandPatch.cs
  Patches/ShipStatusPatch.cs
  Resources/Lang/en_US.json
  Roles/AddOns/Common/Repairman.cs
  Roles/Crewmate/SabotageMaster.cs
Labels: Fix bug

#383 Encode role log and bug fix
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/IntroPatch.cs
Labels: Fix bug, Some change

#401 Fix Bug When Modded SA Auto Selected
  Modules/ServerAddManager.cs
Labels: Fix bug

#402 Add tag for some Harmony Function
  Modules/OptionHolder.cs
  Patches/AnnouncementPatch.cs
  Patches/HashRandomPatch.cs
Labels: Some change

#403 doppelganger switch level
  Roles/Neutral/Doppelganger.cs
Labels: Some change

#404 try fix dual kamikaze bug
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/OptionHolder.cs
  Roles/Impostor/Kamikaze.cs
Labels: Fix bug

#405 improve chat spam and remove booster /say permission
  Modules/ChatManager.cs
  Modules/GuessManager.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Resources/Lang/en_US.json
  dbConnect.cs
Labels: Some change

#406 /quit setting to prevent hackers or player to ban themselves
  Modules/EAC.cs
  Modules/OptionHolder.cs
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
Labels: Some change, New Setting

#407 change version and remove resetcamlist for kamikaze
  Roles/Impostor/Kamikaze.cs
  main.cs
Labels: Some change

#408 update bg
  Patches/MainMenuManagerPatch.cs
  Resources/Background/TOHE-Background-1.4.0.png
Labels: Some change

#412 Add RU Announcement
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#413 Fix /b
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#414 italian translation
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#415 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/ga_IE.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#418 Fix s chinese announcement
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#417 Update TChinese in CheckCommond()
  Modules/ChatManager.cs
  Modules/GuessManager.cs
  Roles/Crewmate/Judge.cs
  Roles/Crewmate/ParityCop.cs
  Roles/Crewmate/President.cs
  Roles/Crewmate/Swapper.cs
Labels: Add/Update Translation

#420 Provocateur can't get Bait
  Modules/CustomRolesHelper.cs
Labels: Fix bug

#421 Fix Tracker Error In SendRPC
  Modules/NameNotifyManager.cs
  Roles/Crewmate/Tracker.cs
Labels: Fix bug

#422 Fix Check Game End & Some Fix
  Patches/CheckGameEndPatch.cs
  Roles/Crewmate/Tracker.cs
  Roles/Impostor/Morphling.cs
  Roles/Neutral/DarkHide.cs
  Roles/Neutral/Vulture.cs
Labels: Fix bug

#423 Fix Bug When Bard Not Work
  Modules/CustomRoleSelector.cs
  Patches/ExilePatch.cs
  Roles/Impostor/Bard.cs
Labels: Fix bug

#419 Develop 1.4.1 dev 1
  Modules/ChatManager.cs
  Modules/CustomRoleSelector.cs
  Modules/CustomRolesHelper.cs
  Modules/GuessManager.cs
  Modules/NameNotifyManager.cs
  Patches/AnnouncementPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ExilePatch.cs
  Roles/Crewmate/Judge.cs
  Roles/Crewmate/ParityCop.cs
  Roles/Crewmate/President.cs
  Roles/Crewmate/Swapper.cs
  Roles/Crewmate/Tracker.cs
  Roles/Impostor/Bard.cs
  Roles/Impostor/Morphling.cs
  Roles/Neutral/DarkHide.cs
  Roles/Neutral/Vulture.cs
  main.cs
Labels: Merge to main

#416 Add option to hide host text + Translate API tags
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/ClientPatch.cs
  Resources/Lang/en_US.json
  dbConnect.cs
  main.cs
Labels: Some change

#377 Auto Rehost for debugger Usage
  Modules/RehostManager.cs
  Patches/ClientOptionsPatch.cs
  Patches/ControlPatch.cs
  Patches/EndGameManagerPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Resources/Lang/en_US.json
  main.cs
Labels: Enhancement

#399 Support Vanilla Hide&Seek & Fix Vents On Dleks Map
  GameModes/FFAManager.cs
  Modules/BanManager.cs
  Modules/CustomRoleSelector.cs
  Modules/DisableDevice.cs
  Modules/DoorsReset.cs
  Modules/EAC.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Modules/OptionItem/OptionItem.cs
  Modules/TemplateManager.cs
  Modules/Utils.cs
  Patches/AirShipElectricalDoors.cs
  Patches/ChatCommandPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ClientPatch.cs
  Patches/ControlPatch.cs
  Patches/DeconSystemPatch.cs
  Patches/DiscordPatch.cs
  Patches/DleksPatch.cs
  Patches/ExilePatch.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/GameOptionsPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/HideNSeek/CheckGameEndPatchHnS.cs
  Patches/HideNSeek/PlayerControlPatchHnS.cs
  Patches/HudPatch.cs
  Patches/HudSpritePatch.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/RandomSpawnPatch.cs
  Patches/RecomputeTaskPatch.cs
  Patches/SabotageSystemPatch.cs
  Patches/ServerVersionPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/TaskAdderPatch.cs
  Patches/TaskAssignPatch.cs
  Patches/UsablesPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/AddOns/Common/Repairman.cs
  Roles/Crewmate/Alchemist.cs
  Roles/Crewmate/Mole.cs
  Roles/Crewmate/Monitor.cs
  Roles/Crewmate/SabotageMaster.cs
  Roles/Impostor/AntiAdminer.cs
  Roles/Neutral/Pelican.cs
  TOHE.csproj
  main.cs
Labels: Fix bug, Enhancement

#427 Fix Random Spawn In Hide & Seek
  Modules/OptionHolder.cs
  Patches/IntroPatch.cs
Labels: Fix bug

#431 dev
  main.cs
Labels: Some change

#432 Options.IsActiveMAP => GameStates.MAPIsActive
  GameModes/FFAManager.cs
  Modules/Camouflague.cs
  Modules/CustomRoleSelector.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/AirShipElectricalDoors.cs
  Patches/DleksPatch.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/RandomSpawnPatch.cs
  Patches/SabotageSystemPatch.cs
Labels: Some change

#426 Optional bool to use vanilla strings. (fixed)
  Modules/OptionItem/BooleanOptionItem.cs
  Modules/OptionItem/FloatOptionItem.cs
  Modules/OptionItem/IntegerOptionItem.cs
  Modules/OptionItem/OptionItem.cs
  Modules/OptionItem/PresetOptionItem.cs
  Modules/OptionItem/StringOptionItem.cs
  Modules/OptionItem/TextOptionItem.cs
  Modules/Translator.cs
  Patches/GameOptionsMenuPatch.cs
Labels: Some change

#337 Quizmaster
  Modules/CustomRolesHelper.cs
  Modules/DevManager.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Translator.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ClientPatch.cs
  Patches/ExilePatch.cs
  Patches/HudPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/Neutral/Quizmaster.cs
  Roles/Neutral/Solsticer.cs
  main.cs
Labels: New Role/Add-on, In Progress

#433 Quizmaster (done)
  Modules/CustomRolesHelper.cs
  Modules/DevManager.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Translator.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ClientPatch.cs
  Patches/ExilePatch.cs
  Patches/HudPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/Neutral/Quizmaster.cs
  Roles/Neutral/Solsticer.cs
  main.cs
Labels: Merge to main

#387 Add Susceptible
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Patches/ChatCommandPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/AddOns/Common/Susceptible.cs
  main.cs
Labels: New Role/Add-on

#434 Evil Tracker Now Cannot Get Seer Add-on
  Modules/CustomRolesHelper.cs
Labels: Some change

#435 Kamikaze Now Cannot Get Swift Add-on
  Modules/CustomRolesHelper.cs
Labels: Fix bug

#438 fix quizmaster not working
  Patches/onGameStartedPatch.cs
  Roles/Neutral/Quizmaster.cs
Labels: Fix bug

#439 Fix Burst Error When Game End
  Patches/CheckGameEndPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#440 Fix MeetingHud OnDestroy Error
  Modules/GuessManager.cs
Labels: Fix bug

#441 Sort Options & Remove Unused Options
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/GameState.cs
  Modules/NameColorManager.cs
  Modules/OptionHolder.cs
  Modules/SpamManager.cs
  Patches/PlayerControlPatch.cs
Labels: Some change

#442 More "ToArray()"
  Modules/ChatManager.cs
  Modules/CustomRoleSelector.cs
  Modules/CustomWinnerHolder.cs
  Modules/GameState.cs
  Patches/CheckGameEndPatch.cs
  Patches/ControlPatch.cs
  Patches/GameOptionsMenuPatch.cs
  Roles/Crewmate/Addict.cs
  Roles/Crewmate/Benefactor.cs
  Roles/Crewmate/Bloodhound.cs
  Roles/Crewmate/Captain.cs
  Roles/Crewmate/Cleanser.cs
  Roles/Crewmate/CopyCat.cs
  Roles/Crewmate/Counterfeiter.cs
  Roles/Crewmate/Divinator.cs
  Roles/Crewmate/Enigma.cs
  Roles/Impostor/BallLightning.cs
  Roles/Impostor/BountyHunter.cs
  Roles/Impostor/Chronomancer.cs
  Roles/Impostor/Councillor.cs
  Roles/Impostor/Deathpact.cs
  Roles/Impostor/Eraser.cs
  Roles/Impostor/EvilTracker.cs
Labels: Improve Code

#428 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/ga_IE.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#443 Local Teleport
  Modules/Utils.cs
Labels: Some change

#444 rearrange customroles enum in alphabetical order for guesser UI
  main.cs
Labels: Some change

#446 New Impostor role Rift Maker and fix Undertaker RPC
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/Impostor/RiftMaker.cs
  Roles/Impostor/Undertaker.cs
  main.cs
Labels: Fix bug, New Role/Add-on

#447 Save Preset Options (Coded by dev TOH)
  Modules/OptionHolder.cs
  Modules/OptionItem/OptionItem.cs
  Modules/OptionItem/PresetOptionItem.cs
  Modules/OptionSaver.cs
Labels: Some change

#448 Fix Disconnect At Game End (Coded by dev TOH)
  Modules/CustomWinnerHolder.cs
  Patches/CheckGameEndPatch.cs
Labels: Fix bug

#449 New Setting: Show Only Enabled Roles In Guesser UI
  Modules/GuessManager.cs
  Modules/OptionHolder.cs
  Resources/Lang/en_US.json
Labels: New Setting

#453 copycat copying taskinator will give benefactor
  Roles/Crewmate/CopyCat.cs
Labels: Some change

#452 some fixes for rift maker
  Modules/Utils.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Divinator.cs
  Roles/Impostor/RiftMaker.cs
Labels: Fix bug

#451 Add alchemist settings
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Alchemist.cs
Labels: Improve Role/Add-on

#454 Improve Code In Check Murder & Fix Spam LateTask About Mole On Exit Vent
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Patches/PlayerControlPatch.cs
  Roles/Crewmate/Benefactor.cs
  Roles/Crewmate/Merchant.cs
  Roles/Crewmate/Mole.cs
Labels: Some change, Improve Code

#455 Set Preset 5 For Modded Non-Host Players
  Modules/RPC.cs
Labels: Some change

#456 Fix Set Preset 5
  Modules/RPC.cs
Labels: Fix bug

#458 Fix Many Bugs In Quizmaster & New Setting: Can Give Questions About Past Games
  Modules/CustomRolesHelper.cs
  Modules/Utils.cs
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/ShipStatusPatch.cs
  Resources/Lang/en_US.json
  Roles/Neutral/Quizmaster.cs
  Roles/Neutral/Spiritcaller.cs
Labels: Fix bug, New Setting

#464 Fix Bug Where Evil Tracker "Can See Kill Flash" Option Sometimes Not Work
  Modules/Utils.cs
  Roles/Impostor/EvilTracker.cs
Labels: Fix bug

#466 fix copycat copying enigma doesnt give clue and missing pyromaniac string
  Resources/Lang/en_US.json
  Roles/Crewmate/CopyCat.cs
  Roles/Crewmate/Enigma.cs
Labels: Fix bug

#463 make /rand inclusive + add /rn for vanilla clients
  Modules/DevManager.cs
  Modules/OptionHolder.cs
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
Labels: Fix bug, Some change

#468 change ver
  main.cs
Labels: Some change

#469 revert change version
  main.cs
Labels: Some change

#470 fix copycat x Enigma ~~i'm dumb~~
  Roles/Crewmate/CopyCat.cs
Labels: Fix bug

#471 Random Skins & Colors In Camouflage
  Modules/Camouflague.cs
  Modules/OptionHolder.cs
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
Labels: Enhancement, New Setting

#474 Copycat improvements and fix
  Modules/CustomRolesHelper.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Admirer.cs
  Roles/Crewmate/Benefactor.cs
  Roles/Crewmate/Bloodhound.cs
  Roles/Crewmate/Cleanser.cs
  Roles/Crewmate/CopyCat.cs
  Roles/Crewmate/Counterfeiter.cs
  Roles/Crewmate/Crusader.cs
  Roles/Crewmate/Deputy.cs
  Roles/Crewmate/Divinator.cs
  Roles/Crewmate/Jailer.cs
  Roles/Crewmate/Judge.cs
  Roles/Crewmate/Medic.cs
  Roles/Crewmate/Mediumshiper.cs
  Roles/Crewmate/Merchant.cs
  Roles/Crewmate/Monitor.cs
  Roles/Crewmate/Mortician.cs
  Roles/Crewmate/Oracle.cs
  Roles/Crewmate/ParityCop.cs
  Roles/Crewmate/President.cs
  Roles/Crewmate/Reverie.cs
  Roles/Crewmate/SabotageMaster.cs
  Roles/Crewmate/Sheriff.cs
  Roles/Crewmate/Snitch.cs
  Roles/Crewmate/Spiritualist.cs
  Roles/Crewmate/Spy.cs
  Roles/Crewmate/Swapper.cs
  Roles/Crewmate/SwordsMan.cs
  Roles/Crewmate/Tracefinder.cs
  Roles/Crewmate/Tracker.cs
Labels: Fix bug, Improve Role/Add-on

#477 improve FT role reveal code
  Resources/Lang/en_US.json
  Roles/Crewmate/Divinator.cs
Labels: Improve Code

#478 New setting only allow whitelisted players to join lobbies
  Modules/OptionHolder.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Resources/Lang/en_US.json
Labels: New Setting

#479 fix inspector doesnt give madmate as imp team
  Modules/CustomRolesHelper.cs
Labels: Fix bug

#480 Fix solsticer can be murdered
  Modules/ExtendedPlayerControl.cs
  Roles/Neutral/Solsticer.cs
Labels: Fix bug

#481 New Fortune teller setting Give random active roles as hint
  Resources/Lang/en_US.json
  Roles/Crewmate/Divinator.cs
Labels: New Setting

#482 Fix Some Strings
  Resources/Lang/en_US.json
  Roles/Neutral/Quizmaster.cs
Labels: Add/Update Translation

#483 Port code Vent.CanUse From TOH & Fix Vent During Comms Sabotage & Fix Camouflager
  Modules/Utils.cs
  Patches/UsablesPatch.cs
  Roles/Impostor/Camouflager.cs
Labels: Fix bug

#484 Fix Modded Client Left The Game
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Fix bug

#486 Fix Quizmaster Meeting Num Not Resets After Start Game & Last Sabotage
  Roles/Neutral/Quizmaster.cs
Labels: Fix bug

#487 Fix Merchant No Longer Checks Add-ons Limit
  Modules/CustomRolesHelper.cs
  Roles/Crewmate/Merchant.cs
Labels: Fix bug

#488 Try Fix Bug When President Skips Meeting And Someone Will Be Ejected
  Patches/MeetingHudPatch.cs
  Roles/Crewmate/President.cs
Labels: Fix bug

#490 Fix Bug When President Skips Meeting And Someone Will Be Ejected (Again)
  Patches/ControlPatch.cs
  Patches/MeetingHudPatch.cs
  Roles/Crewmate/President.cs
Labels: Fix bug

#491 Get Real Name After Player Left The Game
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Some change

#492 Fix Bug When Alchemist & Bloodlust Could Kill After Meeting
  Patches/PlayerControlPatch.cs
  Roles/Crewmate/Alchemist.cs
Labels: Fix bug

#493 Check Everyone Is Dead First
  Patches/CheckGameEndPatch.cs
Labels: Fix bug

#495 Exclude solsticer from seeker's target
  Roles/Neutral/Seeker.cs
Labels: Fix bug

#494 Rebase Swapper
  Modules/GuessManager.cs
  Modules/RPC.cs
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Swapper.cs
  main.cs
Labels: Fix bug, Rework Role/Add-on

#496 Remove roles from Experimental
  Modules/OptionHolder.cs
  Roles/AddOns/Common/Oiiai.cs
  Roles/Crewmate/Admirer.cs
  Roles/Impostor/BallLightning.cs
  Roles/Impostor/Blackmailer.cs
  Roles/Impostor/Eraser.cs
  Roles/Impostor/Hangman.cs
  Roles/Impostor/OverKiller.cs
  Roles/Neutral/Solsticer.cs
Labels: Some change

#429 Make db connect with async
  Modules/dbConnect.cs
  Patches/ClientPatch.cs
  Resources/Lang/en_US.json
  dbConnect.cs
Labels: Some change

#497 Make Delay Update In Ping Tracker Update
  Patches/CredentialsPatch.cs
Labels: Some change

#498 Fix version check crash
  Modules/RPC.cs
Labels: Fix bug

#499 Fix mini can misguess to death
  Modules/GuessManager.cs
  Resources/Lang/en_US.json
  Roles/Double/Mini.cs
Labels: Fix bug

#500 Rework investigator and fix bug
  Modules/ExtendedPlayerControl.cs
  Modules/NameColorManager.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/CopyCat.cs
  Roles/Crewmate/Investigator.cs
Labels: Fix bug, Rework Role/Add-on

#501 Optimize Ping Tracker Update
  Patches/CredentialsPatch.cs
Labels: Improve Code

#504 Improve Code In GameState
  Modules/GameState.cs
  Roles/Crewmate/Captain.cs
  Roles/Crewmate/Cleanser.cs
  Roles/Crewmate/Merchant.cs
Labels: Improve Code

#502 rework killing machine and move to imp killing
  Modules/CustomRolesHelper.cs
  Modules/OptionHolder.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/AddOns/Common/Oiiai.cs
  Roles/Crewmate/Counterfeiter.cs
  Roles/Crewmate/Medic.cs
  Roles/Neutral/Pursuer.cs
Labels: Some change, Rework Role/Add-on

#462 Add tired
  Modules/CustomRolesHelper.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/AddOns/Common/Tired.cs
  Roles/Crewmate/Merchant.cs
  Roles/Impostor/Dazzler.cs
  Roles/Neutral/Bandit.cs
  main.cs
Labels: New Role/Add-on

#505 Fix Bug When Swooper & Chameleon & Wraith Teleport In Vent After Meeting
  Patches/PlayerControlPatch.cs
  Roles/Crewmate/Chameleon.cs
  Roles/Impostor/Swooper.cs
  Roles/Neutral/Wraith.cs
Labels: Fix bug

#506 Fix Alchemist Teleport In Vent After Meeting
  Roles/Crewmate/Alchemist.cs
Labels: Fix bug

#508 Fix Meeting Error For Swooper & Chameleon & Wraith & Alchemist
  Roles/Crewmate/Alchemist.cs
  Roles/Crewmate/Chameleon.cs
  Roles/Impostor/Swooper.cs
  Roles/Neutral/Wraith.cs
Labels: Fix bug

#509 Fix Quizmaster Invalid Answer
  Resources/Lang/en_US.json
  Roles/Neutral/Quizmaster.cs
Labels: Fix bug

#507 Rebase swapper
  Roles/Crewmate/Swapper.cs
  main.cs
Labels: Fix bug

#510 Fix Random Skins & Colors In Camouflage
  Modules/Camouflague.cs
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#511 Add some try catch for version check
  Modules/RPC.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Some change

#515 Some changes
  Patches/AnnouncementPatch.cs
  Patches/ChatCommandPatch.cs
Labels: Add/Update Translation

#516 Fix color names/symbol for multiple roles
  Roles/Crewmate/Captain.cs
  Roles/Crewmate/Investigator.cs
  Roles/Crewmate/Spy.cs
  Roles/Neutral/Pixie.cs
  Roles/Neutral/Seeker.cs
Labels: Fix bug

#518 fix killing machine using vanilla kill cooldown
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#519 fix coroner not showing arrow towards the killer for modded client
  Modules/RPC.cs
  Roles/Crewmate/Bloodhound.cs
Labels: Fix bug

#520 Fix Bug When Workaholic Not Work
  Modules/GameState.cs
Labels: Fix bug

#522 Fix Error In Logs "Auto Play Again" After Game End
  Patches/EndGameManagerPatch.cs
Labels: Fix bug

#523 Fix Error In Log When Player Complete Task (I hope)
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#525 new role schrodinger's cat
  Modules/CustomRolesHelper.cs
  Modules/NameColorManager.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/CheckGameEndPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/Crewmate/Divinator.cs
  Roles/Neutral/SchrodingersCat.cs
  main.cs
Labels: New Role/Add-on, Port from TOH

#526 Warn when /dump is used and fix original compiler errors
  Modules/ExtendedPlayerControl.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/HudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Resources/Lang/en_US.json
  TOHE.csproj
Labels: Some change

#527 Hide tag for Vanilla
  Modules/Utils.cs
Labels: Fix bug

#513 Port a few TOH (taken from TOHE+) roles.
  Modules/AntiBlackout.cs
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/NameColorManager.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/CheckGameEndPatch.cs
  Patches/HudPatch.cs
  Patches/HudSpritePatch.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/Impostor/Penguin.cs
  Roles/Impostor/Stealth.cs
  Roles/Neutral/PlagueDoctor.cs
  main.cs
Labels: New Role/Add-on, Port from TOH, Port from TOHE+

#503 Add Rainbow
  Modules/CustomRolesHelper.cs
  Modules/GuessManager.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/AddOns/Common/Rainbow.cs
  main.cs
Labels: New Role/Add-on, Port from TOH-Y

#528 Some Changes For Plague Doctor & Penguin & Stealth
  Modules/Utils.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/RandomSpawnPatch.cs
  Roles/Impostor/Penguin.cs
  Roles/Impostor/Stealth.cs
  Roles/Neutral/PlagueDoctor.cs
Labels: Some change

#530 Fix Penguin Bug
  Patches/HudSpritePatch.cs
  Roles/Impostor/Penguin.cs
Labels: Fix bug

#532 Log host data on client join
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Some change

#533 Fix Show Only Enabled Roles In Guesser UI
  Modules/GuessManager.cs
Labels: Fix bug

#534 Add Delay Teleport After Meeting
  Modules/Utils.cs
  Patches/ExilePatch.cs
  Roles/Impostor/Penguin.cs
  Roles/Neutral/Pelican.cs
Labels: Some change

#535 Send Info In Logs
  Modules/Utils.cs
  Roles/Impostor/Penguin.cs
  Roles/Neutral/Pelican.cs
  main.cs
Labels: Some change

#536 Fix Bug When Quizmaster Not Work For Modded Clients
  Roles/Neutral/Quizmaster.cs
Labels: Fix bug

#539 fix bombed player cant pass the bomb if host is haunting
  Roles/Neutral/Agitater.cs
Labels: Fix bug

#540 fix kamikaze key not found error
  Roles/Impostor/Kamikaze.cs
Labels: Fix bug

#541 Move versioncheck to pc.onenable
  Modules/LateTask.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Fix bug

#542 Fix Bug When Quizmaster Has Tasks
  Modules/Utils.cs
Labels: Fix bug

#543 Fix Plague Doctor Not Work
  Modules/Translator.cs
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Neutral/PlagueDoctor.cs
Labels: Fix bug

#544 Fix Bug When Settings "Neutrals/Crewmates can become Sleuth" Was Switched Places
  Resources/Lang/en_US.json
Labels: Fix bug

#545 Inspector Seeing Rascal As Crew And Impostors
  Modules/CustomRolesHelper.cs
  Roles/Crewmate/ParityCop.cs
Labels: Fix bug

#546 Romantic Self Mark And Some Fix
  Modules/Utils.cs
  Patches/CheckGameEndPatch.cs
  Roles/Neutral/Romantic.cs
Labels: Fix bug, Some change

#547 Remove "Temp.Blank"
  Patches/MeetingHudPatch.cs
Labels: Some change

#548 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#549 Fix Bug When Time Master Works Incorrectly
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#550 double click kill for bandit
  Resources/Lang/en_US.json
  Roles/Neutral/Bandit.cs
Labels: Improve Role/Add-on

#551 AntiBlack RpcVoting Complete
  Modules/AntiBlackout.cs
  Modules/CustomRpcSender.cs
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
Labels: Some change

#553 Fix Setting "Dead Imps Can't Sabotage"
  Patches/SabotageSystemPatch.cs
Labels: Fix bug

#531 Patch check shapeshit
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Impostor/QuickShooter.cs
  Roles/Impostor/RiftMaker.cs
Labels: Enhancement

#555 Remove add-on: Repairman
  Modules/CustomRolesHelper.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/ShipStatusPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/AddOns/Common/Repairman.cs
  main.cs
Labels: Remove Role/Add-on

#558 Make FixedUpdatePatch Async
  Patches/HideNSeek/PlayerControlPatchHnS.cs
  Patches/PlayerControlPatch.cs
Labels: Some change

#559 Fix Disperser Teleport Players When They Were In Vent
  Roles/Impostor/Disperser.cs
Labels: Fix bug

#560 Fix Huntsman When Vanilla Player Not Colored Names Targets
  Roles/Neutral/Huntsman.cs
Labels: Fix bug

#552 Improve AntiBlackout
  Modules/AntiBlackout.cs
  Modules/CustomRoleSelector.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PetsPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Benefactor.cs
  Roles/Crewmate/Chameleon.cs
  Roles/Crewmate/Cleanser.cs
  Roles/Crewmate/CopyCat.cs
  Roles/Crewmate/Jailer.cs
  Roles/Crewmate/Keeper.cs
  Roles/Crewmate/Spiritualist.cs
  Roles/Impostor/Blackmailer.cs
  Roles/Impostor/BountyHunter.cs
  Roles/Impostor/Chronomancer.cs
  Roles/Impostor/Eraser.cs
  Roles/Impostor/EvilTracker.cs
  Roles/Impostor/SerialKiller.cs
  Roles/Impostor/Swooper.cs
  Roles/Neutral/Pirate.cs
  Roles/Neutral/Seeker.cs
  Roles/Neutral/Solsticer.cs
  Roles/Neutral/Taskinator.cs
  Roles/Neutral/Vulture.cs
  Roles/Neutral/Wraith.cs
Labels: Enhancement

#561 Try Fix Error In "NormalGameOptionsSender.IsDirty"
  Modules/GameOptionsSender/NormalGameOptionsSender.cs
Labels: Fix bug

#562 Increase LateTask Delay
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Fix bug

#564 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#567 fix shield animation banning modded clients
  Modules/ExtendedPlayerControl.cs
Labels: Fix bug

#566 Fix pestilence
  Modules/ExtendedPlayerControl.cs
  Patches/PlayerControlPatch.cs
  Roles/Impostor/Kamikaze.cs
Labels: Fix bug

#570 IsExiling => airship check
  Modules/GameState.cs
Labels: Fix bug

#571 Add setting : rainbow color changes during camouflage
  Resources/Lang/en_US.json
  Roles/AddOns/Common/Rainbow.cs
Labels: New Setting

#572 Some Fix For Plague Scientist
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/HudPatch.cs
  Patches/MeetingHudPatch.cs
  Roles/Neutral/PlagueDoctor.cs
Labels: Fix bug, Some change

#573 Fix Alchemist Speed
  Resources/Lang/en_US.json
  Roles/Crewmate/Alchemist.cs
Labels: Fix bug
