Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2024-09, with the labels that each got.

#1191 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/it_IT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1202 Jester and Zombie can't get Rebirth
  Modules/CustomRolesHelper.cs
Labels: Fix bug

#1205 Fix dumb moments
  Modules/EAC.cs
Labels: Fix bug

#1207 Solsticer can't get Rebirth
  Modules/CustomRolesHelper.cs
Labels: Fix bug

#1199 Sloth (Harmful Addon) [29700]
  Modules/CustomRolesHelper.cs
  Modules/GameState.cs
  Modules/GuessManager.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/AddOns/Common/Sloth.cs
  Roles/Core/CustomRoleManager.cs
  main.cs
Labels: New Role/Add-on

#1186 Disable Use Vent For Vanilla (Port from MoreGamemodes)
  Modules/ExtendedPlayerControl.cs
  Modules/Utils.cs
  Patches/DleksPatch.cs
  Patches/HudPatch.cs
  Patches/HudSpritePatch.cs
  Patches/IntroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/VentSystemPatch.cs
  Patches/onGameStartedPatch.cs
  README.md
  Resources/Lang/en_US.json
  Roles/Core/CustomRoleManager.cs
  Roles/Core/RoleBase.cs
  Roles/Neutral/Arsonist.cs
  Roles/Neutral/Jester.cs
  Roles/Neutral/Pursuer.cs
  Roles/Neutral/Revolutionist.cs
  main.cs
Labels: Enhancement

#1208 Lift NearBy vents to the top if a player is already in a vent
  Modules/ExtendedPlayerControl.cs
Labels: Fix bug

#1209 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1211 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1210 New Add-on: Prohibited & Add base for removed add-ons
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/AddOns/Common/Prohibited.cs
  Roles/Neutral/Jester.cs
  main.cs
Labels: New Role/Add-on

#1215 Fix Baker RPC
  Roles/Neutral/Baker.cs
Labels: Fix bug

#1212 Better Among Us RPC support
  Modules/BAUPlayersData.cs
  Modules/RPC.cs
  Patches/PlayerControlPatch.cs
  main.cs
Labels: Enhancement

#1213 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1217 Fix mod client not having blue color in lobby
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#1218 Recode Delayed Network Data
  Modules/DelayNetworkedData.cs
Labels: Fix bug

#1219 New role: Ventguard (From EHR)
  Modules/CustomRolesHelper.cs
  Modules/OptionHolder.cs
  Patches/ExilePatch.cs
  Patches/IntroPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/Crewmate/Grenadier.cs
  Roles/Crewmate/Lighter.cs
  Roles/Crewmate/Mayor.cs
  Roles/Crewmate/Pacifist.cs
  Roles/Crewmate/TimeMaster.cs
  Roles/Crewmate/Ventguard.cs
  Roles/Crewmate/Veteran.cs
  main.cs
Labels: New Role/Add-on

#1216 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1221 Death Ejection Message
  Resources/Lang/en_US.json
  Roles/Neutral/SoulCollector.cs
Labels: Enhancement

#1220 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1224 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1228 Add Rpc for Altruist
  Roles/Crewmate/Altruist.cs
Labels: Fix bug

#1227 Again Recode Delayed Networked PlayerInfo
  Modules/DelayNetworkedData.cs
  Patches/onGameStartedPatch.cs
Labels: Fix bug

#1226 New Crowdin updates
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
Labels: Add/Update Translation

#1229 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1232 Add notifyGameEnding
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Resources/Lang/en_US.json
Labels: Some change

#1234 Add more green bean kick
  Modules/DelayNetworkedData.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Fix bug

#1235 Add option Judge max trials per game
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Judge.cs
Labels: New Setting

#1230 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1231 Improve some role descriptions
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#1236 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation
