Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2024-04, with the labels that each got.

#786 RpcSetRole After ResetCams
  Patches/ExilePatch.cs
  Patches/PlayerControlPatch.cs
Labels: Some change

#783 Update zh-CN and zh-TW the ChatCommandPatch.cs
  Patches/ChatCommandPatch.cs
Labels: Add/Update Translation

#790 Fix penguin vent
  Roles/Impostor/Penguin.cs
Labels: Fix bug

#791 Add Announcement for 1.6.0
  Patches/AnnouncementPatch.cs
  Resources/Announcements/modNews-en_US.json
Labels: Add/Update Translation

#796 add Space Monkey to French
  Resources/Announcements/modNews-en_US.json
Labels: Add/Update Translation

#793 Fix bug when April Fools mode not sync for clients
  Modules/GameOptionsSender/GameOptionsSender.cs
Labels: Fix bug

#794 Remove Ghost Roles for 1.6.0
  Modules/OptionHolder.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
Labels: Some change

#797 New Crowdin updates
  Resources/Announcements/modNews-es_419.json
  Resources/Announcements/modNews-it_IT.json
  Resources/Announcements/modNews-pt_BR.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#789 Automate Lang.dat And give roleinfo a new look (+ Colors)
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Modules/TemplateManager.cs
  Modules/Translator.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Impostor/Devourer.cs
  Roles/Impostor/Lurker.cs
Labels: Enhancement

#795 Improved RoleClass System
  Modules/CustomRolesHelper.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/onGameStartedPatch.cs
  Roles/Core/CustomRoleManager.cs
  Roles/Core/RoleBase.cs
  main.cs
Labels: Improve Code

#784 Return Horse mode and prepare for 1st april update
  Modules/ClientOptionItem.cs
  Patches/AprilFoolsModePatch.cs
  Patches/ClientOptionsPatch.cs
  Resources/Lang/en_US.json
  main.cs
Labels: New Setting

#802 Return Init() For ghostassignpatch
  Patches/onGameStartedPatch.cs
  Roles/Core/AssignManager/GhostRoleAssign.cs
Labels: Fix bug

#800 Fix *CHANCE
  Resources/Lang/en_US.json
Labels: Fix bug

#804 shaman typo fix
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#805 Make dbconnect an ienumerator to avoid lag and even connection issues
  Modules/dbConnect.cs
  Patches/ClientPatch.cs
  main.cs
Labels: Some change

#806 nullables fix
  Patches/PlayerControlPatch.cs
  Roles/Crewmate/Captain.cs
  Roles/Crewmate/Medic.cs
  Roles/Neutral/Demon.cs
  Roles/Neutral/Pirate.cs
  Roles/Neutral/Shroud.cs
Labels: Fix bug

#808 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/pt_BR.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#807 Some Changes In Bloodmoon
  Resources/Lang/en_US.json
  Roles/(Ghosts)/Impostor/Bloodmoon.cs
Labels: Fix bug

#809 fixed eaten players did not teleport back in map when scavenger killed pelican
  Roles/Neutral/Pelican.cs
Labels: Fix bug

#810 still apply namecolor when hide host text is enabled
  Modules/Utils.cs
Labels: Some change

#811 Remove seeker from flash (bypasses seeker freeze)
  Modules/CustomRolesHelper.cs
Labels: Fix bug

#812 return
  Roles/(Ghosts)/Impostor/Bloodmoon.cs
Labels: Some change

#814 Councillor new setting Max kill limit per game and fix one impostor spawns no matter what
  Resources/Lang/en_US.json
  Roles/Core/AssignManager/RoleAssign.cs
  Roles/Impostor/Councillor.cs
Labels: Fix bug

#813 Temp fix for friendcodes in modded server
  Modules/GameState.cs
  Modules/RPC.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Some change

#817 Recode updater, removing lag (almost) completely and fixing it
  Modules/ModUpdater.cs
  Patches/MainMenuManagerPatch.cs
  Resources/Lang/en_US.json
  main.cs
Labels: Some change, Improve Code

#818 fix updater *(again)
  Modules/ModUpdater.cs
  Resources/Lang/en_US.json
Labels: Fix bug

#820 it should work perfectly now tbh (updater again)
  Modules/ModUpdater.cs
  Patches/MainMenuManagerPatch.cs
Labels: Fix bug

#822 Multiple bug fixes
  Roles/Crewmate/Jailer.cs
  Roles/Crewmate/Overseer.cs
  Roles/Crewmate/Reverie.cs
  Roles/Crewmate/Vigilante.cs
  Roles/Crewmate/Witness.cs
  Roles/Neutral/Bandit.cs
  Roles/Neutral/God.cs
Labels: Fix bug

#821 update TOHE+ to EHR on README.md lol
  README.md
Labels: Update README

#816 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_ES.json
  Resources/Lang/fr_FR.json
  Resources/Lang/ja_JP.json
  Resources/Lang/zh_CN.json
Labels: Add/Update Translation

#823 Improve random role assign
  Roles/Core/AssignManager/RoleAssign.cs
Labels: Some improvements

#824 Fix Unlucky & Veteran now can't get Fragile
  Modules/CustomRolesHelper.cs
  Patches/PlayerControlPatch.cs
  Patches/ShipStatusPatch.cs
  Resources/Lang/en_US.json
  Roles/AddOns/Common/Unlucky.cs
  Roles/Core/CustomRoleManager.cs
Labels: Fix bug

#825 Fix name not updating when exiled player quits on ejection
  Patches/MeetingHudPatch.cs
Labels: Fix bug

#828 fix kamikaze causing half dead players bug
  Patches/ChatCommandPatch.cs
  Patches/ControlPatch.cs
  Patches/MeetingHudPatch.cs
  Roles/Impostor/Kamikaze.cs
Labels: Fix bug

#830 Fixes
  Modules/CustomRolesHelper.cs
  Roles/Core/RoleBase.cs
  Roles/Crewmate/Detective.cs
  Roles/Impostor/Witch.cs
  Roles/Neutral/HexMaster.cs
  Roles/Neutral/Lawyer.cs
Labels: Fix bug

#829 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/nl_NL.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#836 New setting amnesiac arrows and bug fixes
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Roles/Neutral/Amnesiac.cs
  Roles/Neutral/Lawyer.cs
Labels: Fix bug, Improve Role/Add-on

#838 change version
  main.cs
Labels: Some change

#835 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/nl_NL.json
Labels: Add/Update Translation

#839 translations from main branch
  Resources/Lang/de_DE.json
  Resources/Lang/nl_NL.json
Labels: Add/Update Translation

#837 missing strings + some changes
  Modules/GameState.cs
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/(Ghosts)/Crewmate/Hawk.cs
  Roles/AddOns/Common/Susceptible.cs
  Roles/AddOns/Impostor/Tricky.cs
  Roles/Core/AssignManager/GhostRoleAssign.cs
Labels: Some change

#840 fix quizmaster string and fix grenadier
  Roles/Crewmate/Grenadier.cs
  Roles/Neutral/Quizmaster.cs
Labels: Fix bug, Add/Update Translation

#844 TempAdd Logs and force return
  Patches/PlayerControlPatch.cs
  Roles/AddOns/Common/Fragile.cs
  Roles/Core/CustomRoleManager.cs
Labels: Fix bug, Some change

#846 Revert "TempAdd Logs and force return"
  Patches/PlayerControlPatch.cs
  Roles/AddOns/Common/Fragile.cs
  Roles/Core/CustomRoleManager.cs
Labels: Some change

#845 New addon Glow, Fix eac list not working when apply banlist is off and fix killing machine description
  Modules/BanManager.cs
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/AddOns/Common/Glow.cs
  Roles/Core/CustomRoleManager.cs
  Roles/Impostor/KillingMachine.cs
  main.cs
Labels: Fix bug, New Role/Add-on

#850 Fixes and some changes In "HudSpritePatch"
  Patches/HudPatch.cs
  Patches/HudSpritePatch.cs
  Patches/IntroPatch.cs
  main.cs
Labels: Fix bug, Some change

#849 bug fixes
  Modules/RPC.cs
  Patches/RecomputeTaskPatch.cs
  Roles/Crewmate/Monarch.cs
Labels: Fix bug

#843 New Crowdin updates
  Resources/Announcements/modNews-es_419.json
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/it_IT.json
  Resources/Lang/pt_BR.json
Labels: Add/Update Translation

#853 translations
  Resources/Announcements/modNews-es_419.json
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/it_IT.json
  Resources/Lang/pt_BR.json
Labels: Add/Update Translation

#854 Rolebase n kand ne
  main.cs
Labels: Some change
