Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2024-05, with the labels that each got.

#864 translations
  Resources/Announcements/modNews-nl_NL.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/it_IT.json
  Resources/Lang/nl_NL.json
Labels: Add/Update Translation

#866 Revert changes in other translations
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/ga_IE.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Some change

#867 Upload english translations from RoleBase
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#871 seen == null => seer == seen in NotifyRoles
  Modules/Utils.cs
  Roles/Core/CustomRoleManager.cs
Labels: Some change

#868 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#872 Add notifyroles in checprotect + some killog changes
  Modules/Utils.cs
  Patches/OutroPatch.cs
  Patches/PlayerControlPatch.cs
Labels: Some change

#876 New Addon: Radar
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/AddOns/Common/Radar.cs
  main.cs
Labels: New Role/Add-on

#877 dev 8
  main.cs
Labels: Some change

#878 Translations
  Resources/Lang/de_DE.json
  Resources/Lang/en_US.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#879 update background [added spring art winner by ellenxo]
  Patches/MainMenuManagerPatch.cs
  Resources/Background/ArtComp/TOHE-Background-Old.png
  Resources/Background/ArtComp/drakos_yeager-christmas.png
  Resources/Background/ArtComp/ellenxo-christmas.png
  Resources/Background/ArtComp/fafepl-tohre.png
  Resources/Background/ArtComp/flyflycat_-christmas.png
  Resources/Background/ArtComp/justsonrio8173-tohre.png
  Resources/Background/ArtComp/shapmaster-christmas.png
  Resources/Background/ArtComp/tandem7860-christmas.png
  Resources/Background/CurrentArtWinner/spring-winner-ellenxo.png
  Resources/Background/PrevArtWinner/TOH-RE-Background-New.png
  Resources/Background/PrevArtWinner/TOHE-Background-1.4.0.png
  Resources/Background/TOH-RE-Background-New.png
  Resources/Background/TOH-RE-Background-Unused.jpg
  Resources/Background/TOHE-Background-1.4.0.png
  Resources/Background/TOHE-Background-Old.jpg
Labels: Some change

#880 update text strings
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#881 fix workaholic winning before completing tasks
  Modules/OptionHolder.cs
  Roles/Neutral/Workaholic.cs
Labels: Fix bug

#883 Bring back prefix for addon and fix superstar
  Modules/Utils.cs
  Patches/HudSpritePatch.cs
  Roles/Crewmate/SuperStar.cs
Labels: Fix bug, Some change

#819 New Ghost: Ghastly
  Modules/OptionHolder.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/(Ghosts)/Crewmate/Ghastly.cs
  Roles/(Ghosts)/Impostor/Minion.cs
  main.cs
Labels: New Role/Add-on

#887 Fix Retributionist kills
  Resources/Lang/en_US.json
  Roles/Crewmate/Retributionist.cs
Labels: Fix bug

#886 Improve & recode PlagueBearer
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/HudSpritePatch.cs
  Resources/Lang/en_US.json
  Roles/Core/CustomRoleManager.cs
  Roles/Core/RoleBase.cs
  Roles/Neutral/PlagueBearer.cs
  main.cs
Labels: Improve Role/Add-on

#882 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#889 Fix non host mod client rpc
  Modules/RPC.cs
  Patches/GameStartManagerPatch.cs
Labels: Fix bug

#890 Use "OwnedByHost()" instead of "PlayrId == 0"
  Modules/ExtendedPlayerControl.cs
  Modules/RPC.cs
  Patches/ChatCommandPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/Impostor/Penguin.cs
Labels: Some change

#891 Add some null check in eac
  Modules/EAC.cs
Labels: Some change

#892 TChinese players can use TChinese to guess other players.
  Patches/ChatCommandPatch.cs
Labels: Some change

#894 Fix Player Stuck After Desync "BootFromVent"
  Patches/PlayerControlPatch.cs
  Roles/Crewmate/Benefactor.cs
  Roles/Crewmate/Chameleon.cs
Labels: Fix bug

#885 New Imp Role: Dollmaster
  Modules/ExtendedPlayerControl.cs
  Resources/Lang/en_US.json
  Roles/Core/CustomRoleManager.cs
  Roles/Crewmate/FortuneTeller.cs
  Roles/Impostor/DollMaster.cs
  main.cs
Labels: New Role/Add-on

#895 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#900 EAC use sub reader instead of reader
  Modules/EAC.cs
Labels: Fix bug

#896 Spawn timeout manager
  Modules/RPC.cs
  Modules/TimeOutManager.cs
  Patches/ChatCommandPatch.cs
  Patches/ControlPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  main.cs
Labels: Some change

#901 Port Role: Evil Hacker (From TOH)
  Modules/AdminProvider.cs
  Modules/OptionHolder.cs
  Resources/Lang/en_US.json
  Roles/Impostor/EvilHacker.cs
  main.cs
Labels: New Role/Add-on, Port from TOH

#902 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#904 Fix roles displaying incorrect killer
  Modules/ExtendedPlayerControl.cs
  Roles/(Ghosts)/Impostor/Bloodmoon.cs
  Roles/AddOns/Common/Avanger.cs
  Roles/Crewmate/Alchemist.cs
  Roles/Crewmate/Bastion.cs
  Roles/Impostor/Berserker.cs
  Roles/Impostor/Bomber.cs
  Roles/Impostor/Butcher.cs
  Roles/Impostor/Crewpostor.cs
  Roles/Impostor/CursedWolf.cs
  Roles/Impostor/Deathpact.cs
  Roles/Impostor/Fireworker.cs
  Roles/Impostor/Kamikaze.cs
  Roles/Impostor/Lightning.cs
  Roles/Impostor/Mastermind.cs
  Roles/Impostor/Puppeteer.cs
  Roles/Impostor/Scavenger.cs
  Roles/Impostor/Trapster.cs
  Roles/Impostor/Vampire.cs
  Roles/Impostor/Warlock.cs
  Roles/Neutral/Arsonist.cs
  Roles/Neutral/Infectious.cs
  Roles/Neutral/Jinx.cs
  Roles/Neutral/Poisoner.cs
  Roles/Neutral/Pursuer.cs
  Roles/Neutral/Revolutionist.cs
  Roles/Neutral/Shroud.cs
  Roles/Neutral/Taskinator.cs
  Roles/Neutral/Terrorist.cs
  Roles/Neutral/Werewolf.cs
Labels: Fix bug

#908 Remove custom nt check
  Modules/TimeOutManager.cs
Labels: Fix bug

#910 New Crowdin updates
  Resources/Lang/es_419.json
  Resources/Lang/fr_FR.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#905 RoleBase - Dollmaster Overhaul!
  Modules/ExtendedPlayerControl.cs
  Modules/NameColorManager.cs
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Core/CustomRoleManager.cs
  Roles/Impostor/DollMaster.cs
Labels: Fix bug

#903 Show Lobby Timer For Vanilla & Add "LateTask" For "LobbyStartPatch"
  Modules/RPC.cs
  Patches/GameStartManagerPatch.cs
  Patches/LobbyPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Enhancement

#899 Improve chronomancer
  Modules/ExtendedPlayerControl.cs
  Patches/HudPatch.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Core/RoleBase.cs
  Roles/Impostor/Chronomancer.cs
  Roles/Neutral/Glitch.cs
Labels: Improve Role/Add-on

#906 Improve Blackmailing
  Patches/ChatCommandPatch.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Impostor/Blackmailer.cs
Labels: Improve Role/Add-on

#911 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#912 Fix modded not being able to type forever after blackmailed, and try to fix blackmailing
  Patches/OutroPatch.cs
  Roles/Impostor/Blackmailer.cs
  Roles/Impostor/DollMaster.cs
  Roles/Impostor/EvilHacker.cs
  Roles/Impostor/Trapster.cs
  Roles/Neutral/PlagueBearer.cs
Labels: Fix bug

#913 revert blackmailer
  Patches/ChatCommandPatch.cs
  Roles/Crewmate/Deputy.cs
  Roles/Impostor/Blackmailer.cs
Labels: Fix bug

#917 Automatically ban spoofed fcs
  Modules/BanManager.cs
  Modules/OptionHolder.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Resources/Lang/en_US.json
Labels: Enhancement

#922 fixes
  Modules/Utils.cs
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Neutral/Glitch.cs
Labels: Fix bug

#925 Add killcooldown & engineer settings
  Resources/Lang/en_US.json
  Roles/Vanilla/CrewmateTOHE.cs
  Roles/Vanilla/EngineerTOHE.cs
  Roles/Vanilla/ScientistTOHE.cs
Labels: Some change, New Setting

#924 Fix Monarch, Potion Master rpc + some fixes
  Modules/RPC.cs
  Patches/ChatCommandPatch.cs
  Roles/(Ghosts)/Crewmate/Ghastly.cs
  Roles/Crewmate/Monarch.cs
  Roles/Neutral/PotionMaster.cs
  Roles/Neutral/Vector.cs
Labels: Fix bug

#927 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#929 Addon base + more fixes for Dollmaster!
  Modules/ExtendedPlayerControl.cs
  Roles/Core/CustomRoleManager.cs
Labels: Fix bug

#928 /8ball
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
Labels: New command

#930 Improved SplitMessage
  Modules/Utils.cs
Labels: Fix bug, Enhancement

#931 Show host in meeting (Port from TOU-R)
  Patches/ShowHostMeetingPatch.cs
  README.md
  Resources/Lang/en_US.json
Labels: Enhancement

#933 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#932 Make Disconnected as player state instead of Death Reason
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/GameState.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Resources/Lang/en_US.json
  Roles/AddOns/Impostor/Tricky.cs
  Roles/Core/CustomRoleManager.cs
  Roles/Crewmate/Swapper.cs
  Roles/Neutral/Quizmaster.cs
  Roles/Neutral/Solsticer.cs
  Roles/Neutral/SoulCollector.cs
Labels: Some change

#935 Add Testing Ghost-Roles
  Patches/ChatCommandPatch.cs
  Patches/IntroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Resources/Lang/en_US.json
  Roles/(Ghosts)/Impostor/Minion.cs
  Roles/Core/AssignManager/GhostRoleAssign.cs
Labels: Some change

#937 forgor 💀
  Patches/ChatCommandPatch.cs
Labels: Fix bug

#940 Simplify Glitch + misc fixes
  Modules/Utils.cs
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Roles/Core/AssignManager/GhostRoleAssign.cs
  Roles/Impostor/Trapster.cs
  Roles/Impostor/Zombie.cs
  Roles/Neutral/Collector.cs
  Roles/Neutral/Glitch.cs
  Roles/Neutral/Pelican.cs
  Roles/Neutral/Shroud.cs
Labels: Fix bug

#939 Add-Lobbytimer-in-template
  Modules/TemplateManager.cs
  Resources/Config/template/English.txt
Labels: Some change

#942 Some Bloodmoon Change
  Modules/Extensions/CollectionExtnesions.cs
  Roles/(Ghosts)/Impostor/Bloodmoon.cs
Labels: Fix bug, Some change

#945 Sync Pr (Fix Duplicates in OtherIcons)
  Modules/Extensions/CollectionExtensions.cs
  Modules/Utils.cs
  Patches/onGameStartedPatch.cs
  Roles/Core/CustomRoleManager.cs
Labels: Fix bug

#946 Reset States
  Roles/Core/CustomRoleManager.cs
  Roles/Core/RoleBase.cs
Labels: Fix bug

#950 Fixed some typos and descriptions
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#947 Add ovverides (MarkOther, SuffixOther, LowerOther)
  Helpers/ShuffleHelper.cs
  Modules/Extensions/CollectionExtensions.cs
  Patches/ChatCommandPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/(Ghosts)/Crewmate/Ghastly.cs
  Roles/(Ghosts)/Crewmate/Hawk.cs
  Roles/(Ghosts)/Impostor/Bloodmoon.cs
  Roles/(Ghosts)/Impostor/Minion.cs
  Roles/Core/AssignManager/GhostRoleAssign.cs
  Roles/Core/AssignManager/RoleAssign.cs
  Roles/Core/CustomRoleManager.cs
  Roles/Core/RoleBase.cs
  Roles/Crewmate/Captain.cs
  Roles/Crewmate/Medic.cs
  Roles/Crewmate/Snitch.cs
  Roles/Impostor/Blackmailer.cs
  Roles/Impostor/Lightning.cs
  Roles/Impostor/Sniper.cs
  Roles/Impostor/Witch.cs
  Roles/Neutral/Follower.cs
  Roles/Neutral/HexMaster.cs
  Roles/Neutral/Lawyer.cs
  Roles/Neutral/Pirate.cs
  Roles/Neutral/PlagueDoctor.cs
  Roles/Neutral/Quizmaster.cs
  Roles/Neutral/Romantic.cs
  Roles/Neutral/SchrodingersCat.cs
  Roles/Neutral/Shroud.cs
  Roles/Neutral/Solsticer.cs
  main.cs
Labels: Some change

#944 Fixes black screens during role assign and fix Scientist assign for desync roles
  Patches/IntroPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/Core/AssignManager/RoleAssign.cs
Labels: Fix bug

#941 Some improvements for eac
  Modules/EAC.cs
  Patches/InnerNetClientPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/TaskAssignPatch.cs
Labels: Some improvements

#948 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#952 Role basis desync and remove disable votekick option
  Modules/OptionHolder.cs
  Modules/RoleBasisChanger.cs
  Patches/VoteBanSystemPatch.cs
  Resources/Lang/en_US.json
Labels: Enhancement, Port from EHR

#956 More Role description improvments
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#957 Display Team Name For Vanilla
  Modules/Utils.cs
  Patches/IntroPatch.cs
  Patches/onGameStartedPatch.cs
Labels: Enhancement

#960 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation
