Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2024-02, with the labels that each got.

#574 Doppelganger can vent and imp vision option
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/Utils.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Roles/Neutral/Doppelganger.cs
Labels: New Setting

#575 give N/A as killer role and name when killer is null and player use /death
  Patches/ChatCommandPatch.cs
Labels: Fix bug

#578 Fix Bug When Impostor Ghosts Didn't See The Sabotage Button
  Modules/ExtendedPlayerControl.cs
  Patches/SabotageSystemPatch.cs
Labels: Fix bug

#577 fix instigator using vanilla kill cooldown
  Modules/ExtendedPlayerControl.cs
Labels: Fix bug

#576 fix counillor per meeting limit and fix null error
  Modules/AntiBlackout.cs
  Modules/Utils.cs
  Resources/Lang/en_US.json
  Roles/Impostor/Councillor.cs
Labels: Fix bug

#579 Fix String For Mercenary & Serial Killer
  Resources/Lang/en_US.json
  Roles/Impostor/Mercenary.cs
Labels: Fix bug, Add/Update Translation

#580 Bandit new setting steal cooldown (different from kill cooldown)
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Neutral/Bandit.cs
Labels: New Setting

#582 Fix bug when Pyromaniac not showing the douse on vanilla
  Roles/Neutral/Pyromaniac.cs
Labels: Fix bug

#583 Add file for Observer
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/onGameStartedPatch.cs
  Roles/Crewmate/Observer.cs
Labels: Some change

#584 Disable black screen protection when neutral killers are not present in the game
  Modules/AntiBlackout.cs
Labels: Some change

#585 Remove role: NWitch (Neutral Witch) & Rename role: Spellcaster to Witch
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/NameColorManager.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/CheckGameEndPatch.cs
  Patches/HudPatch.cs
  Patches/IntroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Divinator.cs
  Roles/Neutral/Amnesiac.cs
  Roles/Neutral/Imitator.cs
  Roles/Neutral/NWitch.cs
  Roles/Neutral/PlagueBearer.cs
  main.cs
Labels: Some change, Remove Role/Add-on

#586 Recode add-ons assign
  Modules/CustomRoleSelector.cs
  Patches/onGameStartedPatch.cs
Labels: Enhancement

#587 Fix Assign Add-ons
  Modules/CustomRoleSelector.cs
Labels: Fix bug

#589 Some Changes In Assign Add-ons
  Modules/CustomRoleSelector.cs
Labels: Some change

#588 romantic improvement
  Roles/Neutral/Romantic.cs
Labels: Some change

#590 Use Ctrl+Shift+Enter+Delete for resets setting
  Modules/RPC.cs
  Patches/ControlPatch.cs
Labels: Some change

#568 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#596 Add Missing Divinator Chek Result
  Roles/Crewmate/Divinator.cs
Labels: Fix bug

#597 Process nothing but CustomRPC
  Modules/RPC.cs
Labels: Some change

#600 French Update
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#601 SChinese Announcement
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#602 Remove NWitch From Imitator
  Roles/Neutral/Imitator.cs
Labels: Fix bug

#603 Set default value to 0 for setting "Meetings needed to win" (Jester)
  Modules/OptionHolder.cs
Labels: Some change

#604 Portuguese Brazilian Annoucement Patch translation
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#605 Update FixRoleNameInput for zh-CN and zh-TW.
  Patches/ChatCommandPatch.cs
Labels: Add/Update Translation

#607 Add guard shild when killers try to kill Schrodingers Cat
  Roles/Neutral/SchrodingersCat.cs
Labels: Some change

#608 fix typos
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#595 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#610 pestilence kill pursuer and deceiver when they try to choose pestilence as target
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#611 fix only enabled death reason setting for Tricky
  Patches/onGameStartedPatch.cs
  Roles/AddOns/Impostor/Tricky.cs
Labels: Fix bug

#612 Fix bug when ConfirmImpostor does not set to false
  Patches/GameStartManagerPatch.cs
  Patches/onGameStartedPatch.cs
Labels: Fix bug

#599 Release v1.5.0
  Modules/OptionHolder.cs
  Patches/AnnouncementPatch.cs
  Patches/ChatCommandPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
  Roles/AddOns/Impostor/Tricky.cs
  Roles/Neutral/Imitator.cs
  Roles/Neutral/SchrodingersCat.cs
  main.cs
Labels: Merge to main

#615 fix modded clients cant see huntsman target
  Modules/RPC.cs
  Roles/Neutral/Huntsman.cs
Labels: Fix bug

#617 PlagueBearer & Pestilence now cannot get Fragile
  Modules/CustomRolesHelper.cs
Labels: Fix bug

#618 Fix bug when kill cooldown Sidekick was not set correctly
  Modules/ExtendedPlayerControl.cs
  Roles/Neutral/Jackal.cs
Labels: Fix bug

#619 Fix bug when Pestilence can be eaten
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Neutral/Pelican.cs
Labels: Fix bug

#569 Remove unnecessary error log in on player joined patch
  Modules/ExtendedPlayerControl.cs
  Patches/ChatCommandPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Some change

#622 Fix NotifyRoles For Tricky
  Roles/AddOns/Impostor/Tricky.cs
  Roles/Crewmate/Medic.cs
Labels: Fix bug

#623 Fix Disconnection due relible packet (I hope)
  Modules/CustomRpcSender.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Fix bug

#537 Ghost roles
  Modules/CustomRoleSelector.cs
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/GuessManager.cs
  Modules/NameColorManager.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/(Ghosts)/Crewmate/Warden.cs
  Roles/(Ghosts)/Impostor/Minion.cs
  main.cs
Labels: Enhancement, In Progress

#625 Fix bug when Copycat copy Overseer
  Roles/Crewmate/CopyCat.cs
  Roles/Crewmate/Farseer.cs
Labels: Fix bug

#627 Some fix for Doppelganger
  Modules/RPC.cs
  Roles/Neutral/Doppelganger.cs
Labels: Fix bug

#629 Fix disconnection due reliable packet was not ack'd due message sending was spammed for fortegreen players
  Modules/Utils.cs
Labels: Fix bug

#620 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#634 fix captain remove addon
  Roles/Crewmate/Captain.cs
Labels: Fix bug

#633 Fix errors in logs for Penguin
  Roles/Impostor/Penguin.cs
Labels: Fix bug

#635 rift radius unit chnaged from s
  Roles/Impostor/RiftMaker.cs
Labels: Fix bug

#636 Don't try again send message player with invalid color
  Modules/Utils.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Some change

#640 fix captain addon removal
  Patches/ChatCommandPatch.cs
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
  Roles/Crewmate/Captain.cs
Labels: Fix bug

#639 try fix quizmaster acting zesty
  Modules/CustomRolesHelper.cs
  Patches/CheckGameEndPatch.cs
Labels: Fix bug

#641 fix gangster can not recruit some roles even when setting on
  Modules/Utils.cs
  Roles/Impostor/Gangster.cs
Labels: Fix bug

#642 fix mundane neutral cant do tasks as modded clients
  Modules/Utils.cs
Labels: Fix bug

#643 fix gangster recurting certain roles
  Modules/Utils.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Roles/Crewmate/Admirer.cs
  Roles/Impostor/Gangster.cs
Labels: Fix bug

#644 fix schrodinger's cat win condition
  Patches/CheckGameEndPatch.cs
Labels: Fix bug

#645 fix progress for plaguebearer in modded clients
  Modules/Utils.cs
  Roles/Neutral/PlagueBearer.cs
Labels: Fix bug

#638 New Crowdin updates
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fr_FR.json
  Resources/Lang/ja_JP.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#646 fix collector collecting double votes
  Modules/Utils.cs
  Roles/Neutral/Collector.cs
Labels: Fix bug

#647 Fix same add-ons assign to the same player twice
  Modules/CustomRolesHelper.cs
  Patches/onGameStartedPatch.cs
  Roles/Crewmate/Merchant.cs
Labels: Fix bug

#650 fix crew mundane tasks not counting towards task win
  Modules/Utils.cs
Labels: Fix bug

#655 Return code
  Modules/CustomRolesHelper.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ControlPatch.cs
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fr_FR.json
  Resources/Lang/ja_JP.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
  Roles/Crewmate/Admirer.cs
  Roles/Crewmate/Captain.cs
  Roles/Crewmate/Merchant.cs
  Roles/Impostor/Gangster.cs
  Roles/Neutral/Collector.cs
  Roles/Neutral/PlagueBearer.cs
Labels: Some change

#653 1.5.1 pt br translation
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#654 1.5.1 Jap.AnnouncementPatch
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#656 Add Italian translation of announcement
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#657 Add Rus text in announcement
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#658 Add SChinese translation in announcement
  Patches/AnnouncementPatch.cs
Labels: Add/Update Translation

#538 Merge sync role skill rpc into one - Part1+2 - Crewmate/Impostor roles
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/RPC.cs
  Roles/AddOns/Impostor/Mare.cs
  Roles/Crewmate/Admirer.cs
  Roles/Crewmate/Bloodhound.cs
  Roles/Crewmate/Chameleon.cs
  Roles/Crewmate/ChiefOfPolice.cs
  Roles/Crewmate/Cleanser.cs
  Roles/Crewmate/Counterfeiter.cs
  Roles/Crewmate/Crusader.cs
  Roles/Crewmate/Deputy.cs
  Roles/Crewmate/Divinator.cs
  Roles/Crewmate/Medic.cs
  Roles/Crewmate/Mediumshiper.cs
  Roles/Crewmate/Monarch.cs
  Roles/Crewmate/Oracle.cs
  Roles/Crewmate/SabotageMaster.cs
  Roles/Crewmate/Sheriff.cs
  Roles/Crewmate/Spy.cs
  Roles/Crewmate/Swapper.cs
  Roles/Crewmate/SwordsMan.cs
  Roles/Impostor/Anonymous.cs
  Roles/Impostor/Eraser.cs
  Roles/Impostor/Gangster.cs
  Roles/Impostor/Penguin.cs
  Roles/Impostor/QuickShooter.cs
  Roles/Impostor/Stealth.cs
  Roles/Impostor/Swooper.cs
  Roles/Impostor/Wildling.cs
  Roles/Neutral/BloodKnight.cs
Labels: Some change

#598 Improve Role Summary (Port From TOHE+)
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/Utils.cs
  Patches/ClientOptionsPatch.cs
  Patches/OutroPatch.cs
  Patches/RecomputeTaskPatch.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Farseer.cs
  Roles/Crewmate/Keeper.cs
  Roles/Crewmate/Spy.cs
  main.cs
Labels: Enhancement, Port from TOHE+

#631 Dark Theme (Port From TOHE+)
  Patches/ChatBubblePatch.cs
  Patches/ChatCommandPatch.cs
  Patches/ChatControlPatch.cs
  Patches/ClientOptionsPatch.cs
  Resources/Lang/en_US.json
  main.cs
Labels: Enhancement, New Setting, Port from TOHE+

#651 Remove DecisionByHost
  Modules/ExtendedPlayerControl.cs
  Patches/PlayerControlPatch.cs
Labels: Some change

#659 Fix Progress text and target mark for pirate and remove overtired from enabled addons list
  Modules/RPC.cs
  Roles/AddOns/Impostor/Tricky.cs
  Roles/Neutral/Pirate.cs
Labels: Fix bug

#660 Remove public protocol kick code
  Modules/EAC.cs
  Patches/HorseModePatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Some change

#663 Fix bug when FixedUpdate for roles works in lobby
  Modules/GameState.cs
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#593 add statue
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/AddOns/Common/Statue.cs
  Roles/Crewmate/Merchant.cs
  Roles/Neutral/Bandit.cs
  main.cs
Labels: New Role/Add-on

#665 Fix shapeshifting player getting murdered will cause mod client send shapeshift rpc and trigger eac
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#630 Recode add-ons display
  Modules/ExtendedPlayerControl.cs
  Modules/MafiaRevengeManager.cs
  Modules/NameColorManager.cs
  Modules/OptionHolder.cs
  Modules/RetributionistRevengeManager.cs
  Modules/Utils.cs
  Patches/HudPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Enigma.cs
Labels: Some change

#556 Reject-ShapeShift
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/OptionHolder.cs
  Patches/HudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/SabotageSystemPatch.cs
  Resources/Lang/en_US.json
  Roles/Impostor/Assassin.cs
  Roles/Impostor/Blackmailer.cs
  Roles/Impostor/Camouflager.cs
  Roles/Impostor/Disperser.cs
  Roles/Impostor/EvilTracker.cs
  Roles/Impostor/FireWorker.cs
  Roles/Impostor/QuickShooter.cs
  Roles/Impostor/Sniper.cs
  Roles/Impostor/Twister.cs
Labels: Enhancement

#667 Fix bug when Anti Blackout somtimse not work
  Modules/AntiBlackout.cs
Labels: Fix bug

#668 New setting: Impostors can see each other's Add-ons
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/NameColorManager.cs
  Modules/OptionHolder.cs
  Resources/Lang/en_US.json
  Roles/AddOns/Impostor/Madmate.cs
Labels: New Setting

#662 Fix Time Master teleport & Random spawn
  Modules/GameState.cs
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Patches/RandomSpawnPatch.cs
  Roles/Impostor/Disperser.cs
  Roles/Impostor/Penguin.cs
Labels: Fix bug

#672 Fix Dark Theme
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/ChatControlPatch.cs
Labels: Fix bug

#671 Fix issues in ghost assign
  Modules/CustomRoleSelector.cs
  Modules/Utils.cs
  Patches/OutroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/Core/AssignManager/GhostRoleAssign.cs
  main.cs
Labels: Fix bug

#677 Hotfix
  Patches/ChatCommandPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/(Ghosts)/Crewmate/Warden.cs
  Roles/(Ghosts)/Impostor/Minion.cs
Labels: Fix bug

#679 Add option to disable votebansystem
  Modules/OptionHolder.cs
  Patches/VoteBanSystemPatch.cs
  Resources/Lang/en_US.json
Labels: New Setting

#680 somew fixes
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Patches/GameStartManagerPatch.cs
  Roles/(Ghosts)/Crewmate/Warden.cs
  Roles/(Ghosts)/Impostor/Minion.cs
  Roles/Core/AssignManager/GhostRoleAssign.cs
Labels: Fix bug

#681 Try Fix ShowLastResult
  Modules/ExtendedPlayerControl.cs
  Patches/GameOptionsPatch.cs
  Patches/OutroPatch.cs
  Roles/(Ghosts)/Crewmate/Warden.cs
  Roles/(Ghosts)/Impostor/Minion.cs
  Roles/Core/AssignManager/GhostRoleAssign.cs
Labels: Fix bug

#684 Change Solsticer's counttype to none
  Modules/CustomRolesHelper.cs
  Resources/Lang/en_US.json
Labels: Some change

#685 Fix IsAlive
  Modules/ExtendedPlayerControl.cs
Labels: Fix bug

#687 Make penguin victim cannot kill & pelican cannot eat grabbing penguin
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Impostor/Penguin.cs
  Roles/Neutral/Pelican.cs
Labels: Some change

#689 Add simple error detection for dbConnect
  Modules/dbConnect.cs
Labels: Some change

#682 Retributionist & nemesis
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/MafiaRevengeManager.cs
  Modules/NameColorManager.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/RetributionistRevengeManager.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/(Ghosts)/Crewmate/Retributionist.cs
  Roles/(Ghosts)/Crewmate/Warden.cs
  Roles/(Ghosts)/Impostor/Nemesis.cs
  Roles/AddOns/Common/Necroview.cs
  Roles/AddOns/Common/Susceptible.cs
  Roles/AddOns/Impostor/Madmate.cs
  Roles/AddOns/Impostor/Tricky.cs
  Roles/Core/AssignManager/GhostRoleAssign.cs
  Roles/Crewmate/CopyCat.cs
  Roles/Crewmate/Divinator.cs
  Roles/Crewmate/Inspector.cs
  main.cs
Labels: Improve Role/Add-on

#690 some changes
  Patches/MainMenuManagerPatch.cs
  README.md
  Resources/Background/ArtComp/TOHE-Background-Old.png
  Resources/Background/ArtComp/drakos_yeager-christmas.png
  Resources/Background/ArtComp/ellenxo-christmas.png
  Resources/Background/ArtComp/fafepl-tohre.png
  Resources/Background/ArtComp/flyflycat_-christmas.png
  Resources/Background/ArtComp/justsonrio8173-tohre.png
  Resources/Background/ArtComp/shapmaster-christmas.png
  Resources/Background/ArtComp/tandem7860-christmas.png
  Resources/Background/ArtWinner/TOH-RE-Background-New.png
  Resources/Background/ArtWinner/TOHE-Background-1.4.0.png
  Resources/Background/TOHE-Background-Old.jpg
  Roles/Impostor/Hangman.cs
Labels: Some change

#624 Ghost roles (Developed by Drakos)
  Modules/CustomRoleSelector.cs
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/GuessManager.cs
  Modules/MafiaRevengeManager.cs
  Modules/NameColorManager.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/RetributionistRevengeManager.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/GameOptionsPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/(Ghosts)/Crewmate/Retributionist.cs
  Roles/(Ghosts)/Crewmate/Warden.cs
  Roles/(Ghosts)/Impostor/Minion.cs
  Roles/(Ghosts)/Impostor/Nemesis.cs
  Roles/AddOns/Common/Necroview.cs
  Roles/AddOns/Common/Susceptible.cs
  Roles/AddOns/Impostor/Madmate.cs
  Roles/AddOns/Impostor/Tricky.cs
  Roles/Core/AssignManager/GhostRoleAssign.cs
  Roles/Crewmate/Alchemist.cs
  Roles/Crewmate/CopyCat.cs
  Roles/Crewmate/Divinator.cs
  Roles/Crewmate/Inspector.cs
  main.cs
Labels: Enhancement

#666 Improve Role Spawns (Port From TOHE+)
  Helpers/ShuffleHelper.cs
  Modules/CustomRoleSelector.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/OptionItem/StringOptionItem.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/onGameStartedPatch.cs
  README.md
  Resources/Lang/en_US.json
  Roles/Core/AssignManager/AddonAssign.cs
  Roles/Core/AssignManager/RoleAssign.cs
  main.cs
Labels: Enhancement, Port from TOHE+

#692 Fix "IsAlive" for modded clients
  Modules/ExtendedPlayerControl.cs
Labels: Fix bug

#691 update ghostassign to % update
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Roles/Core/AssignManager/GhostRoleAssign.cs
  Roles/Core/AssignManager/RoleAssign.cs
Labels: Some change

#697 Now?
  Modules/CustomRoleSelector.cs
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/GuessManager.cs
  Modules/MafiaRevengeManager.cs
  Modules/NameColorManager.cs
  Modules/OptionHolder.cs
  Modules/OptionItem/StringOptionItem.cs
  Modules/RPC.cs
  Modules/RetributionistRevengeManager.cs
  Modules/Utils.cs
  Modules/dbConnect.cs
  Patches/ChatCommandPatch.cs
  Patches/GameOptionsPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/IntroPatch.cs
  Patches/MainMenuManagerPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/roleColor.json
  Roles/AddOns/Common/Necroview.cs
  Roles/AddOns/Common/Susceptible.cs
  Roles/AddOns/Impostor/Madmate.cs
  Roles/AddOns/Impostor/Tricky.cs
  Roles/Crewmate/Alchemist.cs
  Roles/Crewmate/CopyCat.cs
  Roles/Crewmate/Divinator.cs
  Roles/Crewmate/Inspector.cs
  Roles/Impostor/Hangman.cs
  Roles/Impostor/Penguin.cs
  Roles/Neutral/Pelican.cs
  TOHE.csproj
  main.cs
Labels: Some change

#699 Remove Retributionist Can Be Madmate
  Roles/AddOns/Impostor/Madmate.cs
  Roles/Impostor/Gangster.cs
Labels: Fix bug

#700 Improve announcement patch (TOHY)
  Patches/AnnouncementPatch.cs
Labels: Enhancement, Port from TOH-Y

#701 RoleBase : Addict
  Modules/RPC.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/Crewmate/Addict.cs
Labels: Improve Code

#703 seeker
  Modules/AntiBlackout.cs
  Modules/Utils.cs
  Roles/Core/CustomRoleManager.cs
  Roles/Neutral/Seeker.cs
Labels: Improve Code

#704 Fix spawn Nice Mini and Evil Mini
  Roles/Core/AssignManager/RoleAssign.cs
Labels: Fix bug

#706 Try fix error after meeting
  Modules/AntiBlackout.cs
  Patches/PlayerControlPatch.cs
  Roles/Core/AssignManager/GhostRoleAssign.cs
Labels: Fix bug

#707 Fix Double Assign Role
  Roles/Core/AssignManager/RoleAssign.cs
Labels: Fix bug

#708 Fix error Fireworker
  Roles/Impostor/FireWorker.cs
Labels: Fix bug

#710 ThisRoleBase & Guardian.
  Modules/CustomRolesHelper.cs
  Modules/GuessManager.cs
  Modules/OptionHolder.cs
  Roles/(Ghosts)/Impostor/Minion.cs
  Roles/Core/CustomRoleManager.cs
  Roles/Core/RoleBase.cs
  Roles/Crewmate/Addict.cs
  Roles/Crewmate/Guardian.cs
  Roles/Crewmate/Judge.cs
  Roles/Impostor/Anonymous.cs
  Roles/Impostor/AntiAdminer.cs
  Roles/Impostor/Arrogance.cs
  Roles/Impostor/Bard.cs
  Roles/Impostor/Berserker.cs
  Roles/Impostor/Blackmailer.cs
  Roles/Impostor/Bomber.cs
  Roles/Impostor/BountyHunter.cs
  Roles/Impostor/Butcher.cs
  Roles/Impostor/Camouflager.cs
  Roles/Impostor/Chronomancer.cs
  Roles/Impostor/Cleaner.cs
  Roles/Impostor/Consigliere.cs
  Roles/Impostor/Councillor.cs
  Roles/Impostor/Crewpostor.cs
  Roles/Impostor/Dazzler.cs
  Roles/Impostor/Deathpact.cs
  Roles/Impostor/Devourer.cs
  Roles/Impostor/SoulCatcher.cs
  Roles/Impostor/Trapster.cs
  Roles/Neutral/Seeker.cs
  Roles/Vanilla/VanillaRole.cs
Labels: Improve Code

#712 Fix Check Shapeshift
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#711 Always Disable ghost-roles from showing in guesser ui
  Modules/GuessManager.cs
Labels: Some change

#709 Fix role assign if "Maximum" is set to > 1
  Roles/Core/AssignManager/RoleAssign.cs
Labels: Fix bug

#628 Fix mod updater for current version number
  Modules/ModUpdater.cs
  Modules/VersionChecker.cs
  Modules/dbConnect.cs
Labels: Fix bug, Some change
