Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2024-10, with the labels that each got.

#1238 Jester can't get Susceptible
  Modules/CustomRolesHelper.cs
Labels: Fix bug

#1241 Improve code and fix altrurist may revive unreported body sometime
  Roles/Crewmate/Altruist.cs
  Roles/Crewmate/Coroner.cs
  Roles/Impostor/Cleaner.cs
  Roles/Neutral/Medusa.cs
  Roles/Neutral/Vulture.cs
Labels: Fix bug, Improve Code

#1240 New Crowdin updates
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/it_IT.json
  Resources/Lang/pt_BR.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1251 Fix Bug:Bait wrong sound and log
  Roles/AddOns/Common/Bait.cs
Labels: Fix bug

#1247 Add Simplified Chinese Command
  Patches/ChatCommandPatch.cs
Labels: Some change, Add/Update Translation

#1246 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1254 Apocalypse Changes Post-Beta
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Patches/MeetingHudPatch.cs
  Resources/Lang/en_US.json
Labels: Fix bug

#1256 Miner can't get Circumvent
  Modules/CustomRolesHelper.cs
  Resources/Lang/en_US.json
  Roles/AddOns/Common/Sleuth.cs
Labels: Fix bug

#1248 Vanilla Map Decorations (Skeld/Mira/Dleks)
  Modules/OptionHolder.cs
  Patches/ShipStatusPatch.cs
  Resources/Lang/en_US.json
Labels: New Setting

#1252 New Crowdin updates
  Resources/Lang/it_IT.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1258 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1259 New Crowdin updates
  Resources/Lang/es_419.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1261 New Crowdin updates
  Resources/Lang/it_IT.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1263 War no longer dies to Pestilence nor can kill it
  Roles/Neutral/PlagueBearer.cs
Labels: Fix bug

#1260 Unhide Team Guessing
  Modules/GuessManager.cs
  Modules/OptionHolder.cs
  Roles/Neutral/Baker.cs
  Roles/Neutral/Berserker.cs
  Roles/Neutral/PlagueBearer.cs
  Roles/Neutral/SoulCollector.cs
Labels: Some change

#1262 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1269 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1272 Add token.env
  token.env
Labels: Some change

#1270 New Crowdin updates
  Resources/Lang/ja_JP.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation
