Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2024-07, with the labels that each got.

#1054 well well well
  Modules/BanManager.cs
Labels: Fix bug

#1056 Fix unity throwing a tantrum
  Patches/GameOptionsMenuPatch.cs
Labels: Some change

#1059 /me stuff
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
Labels: Some improvements

#1061 Lightning can't get Tricky
  Modules/CustomRolesHelper.cs
Labels: Fix bug

#1062 Disable AssertWithTimeout
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Fix bug

#1063 Update kamikaze symbol
  Roles/Impostor/Kamikaze.cs
Labels: Some change

#1064 PunchingBag to Punching Bag
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#1065 Shaman can't get Fragile
  Modules/CustomRolesHelper.cs
Labels: Fix bug

#1066 Possibly fix blackout issue
  Patches/ClientPatch.cs
Labels: Fix bug, Some change

#1068 Delay the spawn for networked data for new clients
  Modules/DelayNetworkedData.cs
  Patches/ClientPatch.cs
  Patches/MainMenuManagerPatch.cs
Labels: Some change

#1069 When Trapster kills Bait note
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#1052 Fix Phantom For Desync Roles
  Modules/ExtendedPlayerControl.cs
  Patches/PlayerControlPatch.cs
  Roles/Crewmate/Chameleon.cs
  Roles/Impostor/Swooper.cs
  Roles/Neutral/Wraith.cs
Labels: Fix bug, Update Mod (v2024.6.18)

#1071 Fix Immediate autostart settings
  Patches/GameStartManagerPatch.cs
Labels: Fix bug

#1073 Youtuber alive death & bait can self report
  Patches/PlayerControlPatch.cs
  Roles/AddOns/Common/Bait.cs
  Roles/AddOns/Common/Youtuber.cs
  Roles/Crewmate/Randomizer.cs
Labels: Fix bug

#1072 Move NetworkedData update from sendallstreamedobjects to FixedUpdate and add a delay
  Modules/DelayNetworkedData.cs
Labels: Fix bug, Some change

#1082 add SetAbilityButtonText for some roles
  Resources/Lang/en_US.json
  Roles/Crewmate/Coroner.cs
  Roles/Neutral/Romantic.cs
  Roles/Neutral/Seeker.cs
  Roles/Neutral/Werewolf.cs
Labels: Some change

#1081 Add blacklisting of some roles for mini + fix bug
  Modules/CustomRolesHelper.cs
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
  Roles/(Ghosts)/Crewmate/Ghastly.cs
  Roles/(Ghosts)/Impostor/Bloodmoon.cs
  Roles/Impostor/Ninja.cs
  Roles/Neutral/Pirate.cs
Labels: Fix bug

#1075 fix amnesiac remembered roles not able to vent
  Modules/Camouflague.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Patches/ControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Neutral/Amnesiac.cs
Labels: Fix bug, Some change

#1070 /poll + QOL changes
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
  Roles/Core/AssignManager/GhostRoleAssign.cs
  Roles/Crewmate/Jailer.cs
  Roles/Crewmate/Mayor.cs
Labels: New command

#1084 Again fix Youtuber Alive bug
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#1077 Dollmaster Fixes
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Roles/Impostor/DollMaster.cs
Labels: Fix bug

#1087 Remove Duplicate String
  Modules/CustomRolesHelper.cs
Labels: Some change

#1086 Add RequestRetryVersionCheck LateTask
  Modules/DelayNetworkedData.cs
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#1085 Rework Councillor Conditons
  Modules/DevManager.cs
  Modules/RPC.cs
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Judge.cs
  Roles/Impostor/Councillor.cs
Labels: Some change

#989 Fix some object references
  Modules/EAC.cs
  Modules/ExtendedPlayerControl.cs
  Modules/RPC.cs
Labels: Fix bug

#1089 Fix Punching bag being judged
  Resources/Lang/en_US.json
  Roles/Crewmate/Judge.cs
  Roles/Impostor/Councillor.cs
Labels: Fix bug

#1090 fix retributionist not working
  Roles/Crewmate/Retributionist.cs
Labels: Fix bug

#1091 Skid Region Menu paging behavior
  Modules/DelayNetworkedData.cs
  Modules/Utils.cs
  Patches/CredentialsPatch.cs
  Patches/DiscordPatch.cs
  Patches/RegionMenuPatch.cs
  main.cs
Labels: Enhancement

#1088 Fix butcher realted
  Roles/Impostor/Butcher.cs
Labels: Fix bug

#1092 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1093 New Crowdin updates
  Resources/Lang/es_ES.json
  Resources/Lang/ja_JP.json
  Resources/Lang/pt_BR.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1094 Fix butcher playing congrats
  Roles/Impostor/Butcher.cs
Labels: Fix bug

#1095 Fix fragile and make Bodyguard and Bloodlust incompatible
  Modules/CustomRolesHelper.cs
  Patches/PlayerControlPatch.cs
  Roles/AddOns/Common/Fragile.cs
  Roles/Core/CustomRoleManager.cs
Labels: Fix bug

#1097 Fix poll title cutting of the text
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
Labels: Fix bug

#1098 Add new roles in alphabetical order in CustomRole Enum file
  main.cs
Labels: Some change

#1083 Specific Turn On Chat
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/InnerNetClientPatch.cs
Labels: Enhancement

#1102 Add two things to the Stealer description.
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#1103 Add Scanner for overseer
  Modules/ExtendedPlayerControl.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Overseer.cs
Labels: Some improvements

#1104 Announcement for 2.0.0
  Resources/Announcements/modNews-en_US.json
Labels: Add/Update Translation

#1105 New Crowdin updates
  Resources/Announcements/modNews-de_DE.json
  Resources/Announcements/modNews-es_419.json
  Resources/Announcements/modNews-es_ES.json
  Resources/Announcements/modNews-fil_PH.json
  Resources/Announcements/modNews-fr_FR.json
  Resources/Announcements/modNews-it_IT.json
  Resources/Announcements/modNews-ja_JP.json
  Resources/Announcements/modNews-ko_KR.json
  Resources/Announcements/modNews-nl_NL.json
  Resources/Announcements/modNews-pt_BR.json
  Resources/Announcements/modNews-pt_PT.json
  Resources/Announcements/modNews-ru_RU.json
  Resources/Announcements/modNews-zh_CN.json
  Resources/Announcements/modNews-zh_TW.json
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1107 Support Hide And Seek (real)
  Modules/OptionHolder.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/GameOptionsPatch.cs
  Patches/GameSettingMenuPatch.cs
Labels: Fix bug

#1110 Just Enable EAC
  Modules/BanManager.cs
  Modules/EAC.cs
  Modules/RPC.cs
  Patches/GameManagerPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Fix bug

#1109 Disable the 5s timeout on custom server
  Patches/InnerNetClientPatch.cs
Labels: Some change

#1112 Fix Councillor Typos
  Resources/Lang/en_US.json
  Roles/Impostor/Councillor.cs
Labels: Add/Update Translation

#1121 Update all Website Links + Donation/Support Links to the New Website (RIP tohre.dev)
  Resources/Config/template/Brazilian.txt
  Resources/Config/template/Dutch.txt
  Resources/Config/template/English.txt
  Resources/Config/template/French.txt
  Resources/Config/template/Italian.txt
  Resources/Config/template/Japanese.txt
  Resources/Config/template/Latam.txt
  Resources/Config/template/Russian.txt
  Resources/Config/template/SChinese.txt
  Resources/Config/template/Spanish.txt
  Resources/Config/template/TChinese.txt
Labels: Some change

#1120 Re-added dlekS ehT map support
  Patches/DleksPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/MapPickerMenuPatch.cs
  Resources/Images/DleksBanner-Wordart.png
  Resources/Images/DleksBanner.png
Labels: Fix bug

#1123 update website, donation and api links
  Modules/dbConnect.cs
  Patches/MainMenuManagerPatch.cs
  README.md
  Resources/Lang/en_US.json
  Roles/Core/CustomRoleManager.cs
  main.cs
Labels: Some change

#1122 Support dleks in select map (By D1GQ )
  Patches/DleksPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/MapPickerMenuPatch.cs
  Resources/Announcements/modNews-en_US.json
  Resources/Images/DleksBanner-Wordart.png
  Resources/Images/DleksBanner.png
Labels: Fix bug

#1124 New Crowdin updates
  Resources/Announcements/modNews-de_DE.json
  Resources/Announcements/modNews-es_419.json
  Resources/Announcements/modNews-es_ES.json
  Resources/Announcements/modNews-fil_PH.json
  Resources/Announcements/modNews-fr_FR.json
  Resources/Announcements/modNews-it_IT.json
  Resources/Announcements/modNews-ja_JP.json
  Resources/Announcements/modNews-ko_KR.json
  Resources/Announcements/modNews-nl_NL.json
  Resources/Announcements/modNews-pt_BR.json
  Resources/Announcements/modNews-pt_PT.json
  Resources/Announcements/modNews-ru_RU.json
  Resources/Announcements/modNews-zh_CN.json
  Resources/Announcements/modNews-zh_TW.json
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1128 remove / IN THIS dbconnect
  Modules/dbConnect.cs
Labels: Some change

#1130 Fixing a small number of bugs that I already knew about
  Modules/CustomRolesHelper.cs
  Resources/Config/template/SChinese.txt
  Roles/Impostor/Vindicator.cs
Labels: Fix bug

#1132 Change API connect system
  Modules/dbConnect.cs
  main.cs
Labels: Some change
