Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2025-01, with the labels that each got.

#1368 Try fix murders instantly after meeting
  Modules/AntiBlackout.cs
  Modules/ExtendedPlayerControl.cs
  Patches/ExilePatch.cs
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#1377 Jester, Jackal and Sidekick now can't get ghost role
  Roles/Core/AssignManager/GhostRoleAssign.cs
Labels: Fix bug

#1383 Fix broken teleport for modded clients + add delay for Mole
  Modules/RPC.cs
  Patches/RandomSpawnPatch.cs
  Roles/Crewmate/Mole.cs
Labels: Fix bug

#1384 Fix bugs mentioned in #1378 and #1379...in another way
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Resources/Lang/en_US.json
Labels: Fix bug, Some improvements

#1388 New Option: Change First Kill Cooldown
  Modules/OptionHolder.cs
  Patches/IntroPatch.cs
  Resources/Lang/en_US.json
Labels: New Setting

#1390 Force update NotifyRoles() for all after murder (for roles using arrows)
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#1396 Fix bug when Amnesiac don't clear arrows after remembering role
  Roles/Neutral/Amnesiac.cs
Labels: Fix bug

#1394 Guesser
  Modules/GuessManager.cs
  Roles/Crewmate/NiceGuesser.cs
  Roles/Impostor/EvilGuesser.cs
Labels: Some change

#1392 Fix Madmate Psychic not seeing all Neutrals displayed in red names
  Roles/Crewmate/Psychic.cs
Labels: Some change

#1395 New Option For Low Load: Delay Update Names
  Modules/LocateArrow.cs
  Modules/OptionHolder.cs
  Modules/TargetArrow.cs
  Modules/Utils.cs
  Patches/IntroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  main.cs
Labels: New Setting

#1404 Fix "SecurityCameraSystem" Not Cleared After RpcExile
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#1406 Fix FFA Assign
  Patches/MeetingHudPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/Core/AssignManager/RoleAssign.cs
Labels: Fix bug

#1405 Fix Witch Mark
  Patches/OutroPatch.cs
  Roles/Impostor/Witch.cs
Labels: Fix bug

#1402 Fix bug when UP message send everyone
  Patches/ChatCommandPatch.cs
Labels: Fix bug

#1401 Fix Lags In Game
  Modules/LateTask.cs
  Patches/CredentialsPatch.cs
  Patches/LobbyPatch.cs
  Patches/PlayerControlPatch.cs
  Roles/Coven/CovenManager.cs
Labels: Fix bug

#1407 Fix Mad/Recruit/Enchanted Amnesiac being able to report bodies after killing OIIAI
  Roles/AddOns/Common/Oiiai.cs
Labels: Fix bug

#1399 Add Some Crew Roles For CopyCat
  Roles/Crewmate/CopyCat.cs
Labels: Some change

#1386 Improve Godfather
  Modules/CustomRolesHelper.cs
  Roles/Impostor/Godfather.cs
Labels: Improve Role/Add-on

#1403 Fixed recruitment issues with Jackal and ChiefOfPolice
  Roles/Crewmate/ChiefOfPolice.cs
  Roles/Neutral/Jackal.cs
Labels: Fix bug

#1409 Fix bug when RemoveIncompatibleAddOns counts self add-on as Incompatible
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
Labels: Fix bug

#1397 Improve AntiBlackout
  Modules/AntiBlackout.cs
  Modules/CustomRolesHelper.cs
  Patches/ExilePatch.cs
Labels: Some improvements

#1414 Add back Option Shower
  Modules/ExtendedPlayerControl.cs
  Modules/OptionShower.cs
  Modules/Utils.cs
  Patches/ControlPatch.cs
  Patches/CredentialsPatch.cs
  Patches/HudPatch.cs
  main.cs
Labels: Enhancement

#1360 New Crowdin updates
  Resources/Announcements/modNews-zh_CN.json
  Resources/Announcements/modNews-zh_TW.json
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1413 No check limit add-ons in RemoveIncompatibleAddOns
  Modules/ExtendedPlayerControl.cs
Labels: Fix bug

#1420 Fix Spurt spam "MarkDirtySettings" when it's not needed
  Roles/AddOns/Common/Spurt.cs
Labels: Fix bug

#1422 Fix error
  Patches/ControlPatch.cs
Labels: Fix bug

#1424 Change Addon Max to 15 + Fixed Version to be Beta 2
  Modules/OptionHolder.cs
  main.cs
Labels: Some change
