Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2025-05, with the labels that each got.

#1278 exorcist
  Modules/GameState.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Resources/Images/Skills/shush.png
  Resources/Lang/en_US.json
  Roles/Impostor/Exorcist.cs
  main.cs
Labels: New Role/Add-on

#1574 fix admirer not being able to recruit players
  Roles/Crewmate/Admirer.cs
Labels: Fix bug

#1576 Disable Vent in 1v1
  Modules/OptionHolder.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
Labels: Enhancement, New Setting

#1577 Variable Impostor Count
  Modules/OptionHolder.cs
  Patches/ChatCommandPatch.cs
  Resources/Lang/en_US.json
  Roles/Core/AssignManager/RoleAssign.cs
Labels: Enhancement, New Setting

#1573 Add addon conflicts for Narc
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
Labels: Fix bug

#1578 Fix Kill Button not working after first round with Modded Clients
  Modules/AntiBlackout.cs
Labels: Fix bug

#1580 Add a few more sounds for some roles
  Modules/AntiBlackout.cs
  Roles/Impostor/AbyssBringer.cs
  Roles/Impostor/Exorcist.cs
  Roles/Impostor/Hangman.cs
Labels: Improve Role/Add-on
