Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2025-04, with the labels that each got.

#1551 Fix Permission Related Tag Issues
  Patches/ChatCommandPatch.cs
Labels: Fix bug

#1550 Client Option to show Modded Client text
  Modules/GuessManager.cs
  Patches/ClientOptionsPatch.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Neutral/Stalker.cs
  main.cs
Labels: Enhancement

#1554 Fix Back button position
  Modules/ClientOptionItem.cs
Labels: Some change

#1555 Dead Players can see who Necromancer and Copycat are when they're different roles
  Modules/Utils.cs
  Patches/PlayerControlPatch.cs
  Roles/Coven/Necromancer.cs
  Roles/Crewmate/CopyCat.cs
Labels: Improve Role/Add-on

#1565 Improvements to Vigilante
  Modules/CustomRolesHelper.cs
  Resources/Lang/en_US.json
  Roles/Crewmate/Vigilante.cs
Labels: Improve Role/Add-on
