Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2025-03, with the labels that each got.

#1504 Fix Vanilla Exception
  Patches/AprilFoolsModePatch.cs
  Patches/LobbyPatch.cs
Labels: Fix bug

#1425 Shapeshift and Flash
  Modules/CustomRolesHelper.cs
Labels: Some change

#1503 Recode "Remove Incompatible Add-ons"
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Patches/TaskAdderPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/AddOns/Common/Oiiai.cs
  Roles/AddOns/Crewmate/Workhorse.cs
  Roles/Coven/MoonDancer.cs
  Roles/Coven/Necromancer.cs
  Roles/Coven/Sacrifist.cs
  Roles/Crewmate/Cleanser.cs
  Roles/Crewmate/CopyCat.cs
  Roles/Crewmate/Merchant.cs
  Roles/Crewmate/TaskManager.cs
  Roles/Neutral/Bandit.cs
Labels: Fix bug

#1500 Port speed run from EHR
  GameModes/FFAManager.cs
  GameModes/SpeedRun.cs
  Modules/CustomRolesHelper.cs
  Modules/GameOptionsSender/PlayerGameOptionsSender.cs
  Modules/OptionHolder.cs
  Modules/OptionItem/OptionItem.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/GameSettingMenuPatch.cs
  Patches/HudPatch.cs
  Patches/IntroPatch.cs
  Patches/OutroPatch.cs
  Patches/SabotageSystemPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/TaskAssignPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/Lang/en_US.json
  Resources/roleColor.json
  Roles/Core/AssignManager/RoleAssign.cs
  main.cs
Labels: Enhancement

#1505 Set spamms CustomRPC to SendOption.None & Remove Unused
  Modules/ExtendedPlayerControl.cs
  Modules/RPC.cs
  Roles/Coven/PotionMaster.cs
  Roles/Coven/Sacrifist.cs
  Roles/Crewmate/Alchemist.cs
  Roles/Crewmate/Chameleon.cs
  Roles/Crewmate/Overseer.cs
  Roles/Impostor/Swooper.cs
  Roles/Neutral/Wraith.cs
Labels: Fix bug

#1492 New Crowdin updates
  Resources/Announcements/modNews-it_IT.json
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/it_IT.json
  Resources/Lang/nl_NL.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
Labels: Add/Update Translation

#1509 Fix strong lag when first load sprites
  Modules/Utils.cs
Labels: Fix bug

#1510 Fix bug in assign roles
  Roles/Core/AssignManager/RoleAssign.cs
Labels: Fix bug

#1512 Improve code in some code
  Modules/Camouflague.cs
  Modules/ExtendedPlayerControl.cs
  Modules/Utils.cs
  Patches/CheckGameEndPatch.cs
  Patches/ExilePatch.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Roles/Double/Mini.cs
  Roles/Impostor/Deathpact.cs
  Roles/Impostor/Devourer.cs
  Roles/Neutral/Doppelganger.cs
Labels: Improve Code

#1514 Allow set parent without role spawn chances overriding names
  GameModes/SpeedRun.cs
  Modules/OptionHolder.cs
  Modules/OptionItem/OptionItem.cs
Labels: Fix bug

#1451 Exile screen
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Patches/MeetingHudPatch.cs
  Resources/Lang/en_US.json
Labels: New Setting

#1522 Sync tags in cmd checkname
  Modules/CustomRpcSender.cs
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#1524 Fix gm getting addons
  Modules/CustomRolesHelper.cs
Labels: Fix bug

#1517 Coven Improvements
  Modules/Utils.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Coven/Conjurer.cs
  Roles/Coven/Illusionist.cs
  Roles/Coven/Jinx.cs
  Roles/Coven/Medusa.cs
  Roles/Coven/PotionMaster.cs
  Roles/Coven/VoodooMaster.cs
  Roles/Crewmate/CopyCat.cs
Labels: Some change, New Setting

#1521 Coven Leader Improvement
  Patches/MeetingHudPatch.cs
  Resources/Lang/en_US.json
  Roles/AddOns/Impostor/Madmate.cs
  Roles/Coven/CovenLeader.cs
  Roles/Crewmate/Admirer.cs
  Roles/Crewmate/Crusader.cs
  Roles/Impostor/Gangster.cs
  Roles/Neutral/Cultist.cs
  Roles/Neutral/CursedSoul.cs
  Roles/Neutral/Infectious.cs
  Roles/Neutral/Jackal.cs
  Roles/Neutral/SchrodingersCat.cs
  Roles/Neutral/Virus.cs
Labels: Improve Role/Add-on

#1515 Dreamweaver (Coven Trickery)
  Modules/OptionHolder.cs
  Patches/MeetingHudPatch.cs
  Resources/Images/Skills/Dreamweave.png
  Resources/Lang/en_US.json
  Roles/Coven/Dreamweaver.cs
  main.cs
Labels: New Role/Add-on

#1530 Add sounds for Vector's venting
  Roles/Crewmate/Alchemist.cs
  Roles/Impostor/Pitfall.cs
  Roles/Neutral/Solsticer.cs
  Roles/Neutral/Vector.cs
  Roles/Neutral/Vulture.cs
Labels: Improve Role/Add-on

#1528 Fix Dictator setting typo
  Resources/Lang/en_US.json
Labels: Add/Update Translation

#1430 Harvester (Coven Utility)
  Modules/OptionHolder.cs
  Resources/Config/template/SChinese.txt
  Resources/Images/Skills/GuessPlateKPD.png
  Resources/Images/Skills/PocketBomb.png
  Resources/Lang/en_US.json
  Roles/Coven/CovenLeader.cs
  Roles/Coven/Harvester.cs
  Roles/Coven/MoonDancer.cs
  main.cs
Labels: New Role/Add-on

#1535 Changes
  Resources/Lang/en_US.json
  Roles/Crewmate/Knight.cs
Labels: Add/Update Translation

#1543 Baker Can Give Bread Again If Breaded Player Dies
  Resources/Lang/en_US.json
  Roles/Neutral/Baker.cs
Labels: Improve Role/Add-on

#1542 Fix missing "OnRemove"s in Romantic's code
  Roles/Neutral/Romantic.cs
Labels: Fix bug

#1545 Improve Crewpostor
  Modules/Utils.cs
  Patches/TaskAssignPatch.cs
  Resources/Lang/en_US.json
  Roles/AddOns/Impostor/LastImpostor.cs
  Roles/Impostor/Crewpostor.cs
Labels: Improve Role/Add-on

#1546 copycat becomes requiter for copying instigator
  Roles/Crewmate/CopyCat.cs
Labels: Improve Role/Add-on

#1547 requiter cannot kill TNAs
  Roles/Crewmate/Knight.cs
Labels: Improve Role/Add-on
