Repository EnhancedNetwork/TownofHost-Enhanced, pull requests merged in 2025-02, with the labels that each got.

#1436 Solsticer can't be Bounty Hunter or Huntsman's target
  Roles/Impostor/BountyHunter.cs
  Roles/Neutral/Huntsman.cs
Labels: Fix bug

#1433 Workaholic and Solsticer shouldn't be Executioner's target
  Roles/Neutral/Executioner.cs
Labels: Fix bug

#1428 Add and Improve Custom Buttons + Add Ability button text for some roles
  .github/workflows/build.yml
  Modules/GuessManager.cs
  Patches/ChatControlPatch.cs
  Resources/Images/DarkKeyboard.png
  Resources/Images/DarkQuickChat.png
  Resources/Images/DarkReport.png
  Resources/Images/Skills/Amnesiac.png
  Resources/Images/Skills/Block.png
  Resources/Images/Skills/Bomb.png
  Resources/Images/Skills/Collective.png
  Resources/Images/Skills/Deputy.png
  Resources/Images/Skills/Disperse.png
  Resources/Images/Skills/Drink.png
  Resources/Images/Skills/EmergencyButton.png
  Resources/Images/Skills/GuessPlateKPD.png
  Resources/Images/Skills/Handcuff.png
  Resources/Images/Skills/JesterVent.png
  Resources/Images/Skills/PocketBomb.png
  Resources/Images/Skills/Pyromaniac.png
  Resources/Images/Skills/RomanticProtect.png
  Resources/Images/Skills/Tag.png
  Resources/Lang/en_US.json
  Roles/Crewmate/Alchemist.cs
  Roles/Crewmate/Deputy.cs
  Roles/Crewmate/Mayor.cs
  Roles/Crewmate/Ventguard.cs
  Roles/Impostor/Blackmailer.cs
  Roles/Impostor/Disperser.cs
  Roles/Impostor/DoubleAgent.cs
  Roles/Neutral/Jester.cs
  Roles/Neutral/Pixie.cs
  Roles/Neutral/Pyromaniac.cs
  Roles/Neutral/Romantic.cs
  Roles/Neutral/Seeker.cs
Labels: Some change

#1431 Madmate Roles can be Last Impostor
  Modules/GameState.cs
  Modules/Utils.cs
  Roles/AddOns/Impostor/LastImpostor.cs
Labels: Improve Role/Add-on

#1439 Change some NotifyRoles
  Modules/Camouflague.cs
  Modules/ExtendedPlayerControl.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ExilePatch.cs
  Patches/IntroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/Crewmate/Altruist.cs
  Roles/Crewmate/Medic.cs
  Roles/Crewmate/Retributionist.cs
  Roles/Impostor/Bomber.cs
  Roles/Impostor/BountyHunter.cs
  Roles/Impostor/Lightning.cs
  Roles/Impostor/Nemesis.cs
  Roles/Neutral/Doppelganger.cs
  Roles/Neutral/Huntsman.cs
  Roles/Neutral/Jackal.cs
  Roles/Neutral/Pelican.cs
  Roles/Neutral/Pixie.cs
  Roles/Neutral/PlagueBearer.cs
  Roles/Neutral/Romantic.cs
  Roles/Neutral/Seeker.cs
  main.cs
Labels: Some change

#1440 Introduce timerLowLoad in FixedUpdate
  Modules/CustomNetObject.cs
  Modules/RPC.cs
  Patches/PlayerControlPatch.cs
  Roles/(Ghosts)/Crewmate/Ghastly.cs
  Roles/Core/CustomRoleManager.cs
  Roles/Core/RoleBase.cs
  Roles/Coven/HexMaster.cs
  Roles/Coven/Necromancer.cs
  Roles/Coven/Poisoner.cs
  Roles/Coven/Sacrifist.cs
  Roles/Crewmate/Addict.cs
  Roles/Crewmate/Alchemist.cs
  Roles/Crewmate/Benefactor.cs
  Roles/Crewmate/Chameleon.cs
  Roles/Crewmate/Grenadier.cs
  Roles/Crewmate/Lighter.cs
  Roles/Crewmate/Overseer.cs
  Roles/Crewmate/Spy.cs
  Roles/Crewmate/Telecommunication.cs
  Roles/Crewmate/TimeMaster.cs
  Roles/Crewmate/Veteran.cs
  Roles/Impostor/AbyssBringer.cs
  Roles/Impostor/AntiAdminer.cs
  Roles/Impostor/BountyHunter.cs
  Roles/Impostor/Chronomancer.cs
  Roles/Impostor/Deathpact.cs
  Roles/Impostor/DollMaster.cs
  Roles/Impostor/DoubleAgent.cs
  Roles/Impostor/EvilHacker.cs
  Roles/Impostor/Lightning.cs
  Roles/Impostor/Mastermind.cs
  Roles/Impostor/Mercenary.cs
  Roles/Impostor/Penguin.cs
  Roles/Impostor/RiftMaker.cs
  Roles/Impostor/Stealth.cs
  Roles/Impostor/Swooper.cs
  Roles/Impostor/Vampire.cs
  Roles/Impostor/Warlock.cs
  Roles/Impostor/Wildling.cs
  Roles/Impostor/YinYanger.cs
  Roles/Neutral/Agitater.cs
  Roles/Neutral/Arsonist.cs
  Roles/Neutral/Baker.cs
  Roles/Neutral/BloodKnight.cs
  Roles/Neutral/Glitch.cs
  Roles/Neutral/Pelican.cs
  Roles/Neutral/Seeker.cs
  Roles/Neutral/Solsticer.cs
  Roles/Neutral/Vulture.cs
  Roles/Neutral/Wraith.cs
Labels: Some change

#1441 More Changes In NotifyRoles
  Patches/ControlPatch.cs
  Patches/SabotageSystemPatch.cs
  Roles/Neutral/Huntsman.cs
  Roles/Neutral/Romantic.cs
  Roles/Neutral/Solsticer.cs
Labels: Some change

#1445 Add SendOption in Rpc logs
  Modules/ExtendedPlayerControl.cs
  Modules/RPC.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: Some change

#1443 fix bug...ig
  Modules/CustomRolesHelper.cs
Labels: Fix bug

#1432 Add Enchanted in more roles
  Roles/AddOns/Common/Necroview.cs
  Roles/AddOns/Common/Rebirth.cs
  Roles/Crewmate/Bodyguard.cs
  Roles/Impostor/BountyHunter.cs
  Roles/Impostor/Visionary.cs
  Roles/Neutral/Cultist.cs
  Roles/Neutral/CursedSoul.cs
  Roles/Neutral/Virus.cs
Labels: Improve Role/Add-on

#1446 Check last closest vent
  Patches/PlayerControlPatch.cs
  Patches/VentSystemPatch.cs
  Patches/onGameStartedPatch.cs
Labels: Some change

#1444 Global Bypass RateLimit
  Modules/ChatManager.cs
  Modules/ExtendedPlayerControl.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/TaskAssignPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/Impostor/Penguin.cs
Labels: Fix bug

#1438 CheckGameEndPatch
  Patches/CheckGameEndPatch.cs
Labels: Fix bug

#1423 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/it_IT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1462 Shuffle Twice In Role Assign & Fix Crashes
  Modules/OptionHolder.cs
  Modules/Random/IRandom.cs
  Roles/Core/AssignManager/RoleAssign.cs
Labels: Fix bug

#1465 Fix Retributionist and Nemesis
  Roles/Crewmate/Retributionist.cs
  Roles/Impostor/Nemesis.cs
Labels: Fix bug

#1467 Fix Phantom Not Work For Desync Roles
  Modules/ExtendedPlayerControl.cs
  Patches/PhantomRolePatch.cs
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#1463 Recode UnShift state
  Modules/ExtendedPlayerControl.cs
  Modules/Extensions/CollectionExtensions.cs
  Modules/GameState.cs
  Patches/ExilePatch.cs
  Patches/IntroPatch.cs
  Patches/PlayerControlPatch.cs
  Patches/SabotageSystemPatch.cs
Labels: Fix bug

#1477 Fix RoleText In Mushroom Spore
  Patches/PlayerControlPatch.cs
Labels: Fix bug

#1479 Fix some Exception in logs
  Patches/OutroPatch.cs
  Roles/(Ghosts)/Crewmate/Hawk.cs
  Roles/Coven/Conjurer.cs
  Roles/Coven/MoonDancer.cs
  Roles/Crewmate/Merchant.cs
Labels: Fix bug

#1478 Fix Poisoner/Deputy Always Block SerialKiller, Pursuer, Deceiver
  Roles/Coven/Poisoner.cs
  Roles/Crewmate/Deputy.cs
  Roles/Neutral/Baker.cs
Labels: Fix bug

#1480 Again fix some exception
  Modules/CustomNetObject.cs
  Modules/GuessManager.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/GameSettingMenuPatch.cs
  Roles/Coven/Conjurer.cs
Labels: Fix bug

#1482 Fix Necromancer being able to change roles during necronomicon ability
  Resources/Lang/en_US.json
  Roles/Coven/Necromancer.cs
Labels: Fix bug

#1483 New Crowdin updates
  Resources/Lang/de_DE.json
  Resources/Lang/es_419.json
  Resources/Lang/es_ES.json
  Resources/Lang/fil_PH.json
  Resources/Lang/fr_FR.json
  Resources/Lang/it_IT.json
  Resources/Lang/ja_JP.json
  Resources/Lang/ko_KR.json
  Resources/Lang/nl_NL.json
  Resources/Lang/pt_BR.json
  Resources/Lang/pt_PT.json
  Resources/Lang/ru_RU.json
  Resources/Lang/zh_CN.json
  Resources/Lang/zh_TW.json
Labels: Add/Update Translation

#1487 Show Available Update
  Modules/ModUpdater.cs
  Patches/ClientPatch.cs
  Resources/Lang/en_US.json
  main.cs
Labels: Some change

#1472 Make Glitch As Desync Shapeshifter
  Modules/ExtendedPlayerControl.cs
  Patches/SabotageSystemPatch.cs
  Resources/Lang/en_US.json
  Roles/Neutral/Glitch.cs
Labels: Improve Role/Add-on

#1488 Add more Custom Buttons
  Resources/Images/Skills/CoPKill.png
  Resources/Images/Skills/Kill.png
  Resources/Images/Skills/RomanticKill.png
  Resources/Lang/en_US.json
  Roles/Crewmate/ChiefOfPolice.cs
  Roles/Neutral/Romantic.cs
Labels: Some change

#1486 Block guess attempts if guesser tries to guess a role that is not active
  Modules/GuessManager.cs
  Modules/OptionHolder.cs
  Resources/Lang/en_US.json
Labels: New Setting

#1468 Use SetHudActive In HudSpritePatch (For 2.3.0)
  Modules/Cloud.cs
  Patches/HudPatch.cs
  Patches/HudSpritePatch.cs
  Patches/IntroPatch.cs
  Patches/onGameStartedPatch.cs
Labels: Some change

#1454 Medic: change role type to Crewmate after set protect & Some changes in code
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Roles/Coven/Sacrifist.cs
  Roles/Crewmate/Medic.cs
  Roles/Neutral/Shocker.cs
  Roles/Neutral/Solsticer.cs
Labels: Improve Role/Add-on

#1453 Improve Task Manager
  Modules/ExtendedPlayerControl.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/Core/CustomRoleManager.cs
  Roles/Core/RoleBase.cs
  Roles/Crewmate/Benefactor.cs
  Roles/Crewmate/TaskManager.cs
  Roles/Neutral/Taskinator.cs
Labels: Improve Role/Add-on

#1449 Option: Show Short Names For Add-ons
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/HauntMenuMinigamePatch.cs
  Patches/HudPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerControlPatch.cs
  Resources/Lang/en_US.json
  Roles/AddOns/Common/Sleuth.cs
  Roles/Crewmate/Enigma.cs
  Roles/Crewmate/Retributionist.cs
  Roles/Double/Mini.cs
  Roles/Impostor/Nemesis.cs
  Roles/Neutral/Executioner.cs
  Roles/Neutral/Innocent.cs
  Roles/Neutral/Jester.cs
  Roles/Neutral/SoulCollector.cs
Labels: New Setting

#1447 Option: Spawn One Random Killing Fraction
  Modules/OptionHolder.cs
  Resources/Lang/en_US.json
  Roles/Core/AssignManager/RoleAssign.cs
Labels: New Setting

#1496 Fix Blackmailer not blackmailing players
  Roles/Impostor/Blackmailer.cs
Labels: Fix bug

#1497 Fix player count not overridden in assign roles
  Roles/Core/AssignManager/RoleAssign.cs
Labels: Fix bug

#1499 Fix Tiebreaker/TieMode.All Not Work With More 15 Players
  Patches/MeetingHudPatch.cs
Labels: Fix bug

#1471 Fix TNA's dying to roles they shouldnt
  Resources/Lang/en_US.json
  Roles/(Ghosts)/Impostor/Possessor.cs
  Roles/Coven/HexMaster.cs
  Roles/Coven/Poisoner.cs
  Roles/Coven/VoodooMaster.cs
  Roles/Crewmate/Bodyguard.cs
  Roles/Crewmate/Deceiver.cs
  Roles/Crewmate/Jailer.cs
  Roles/Impostor/AbyssBringer.cs
  Roles/Impostor/Deathpact.cs
  Roles/Impostor/DoubleAgent.cs
  Roles/Impostor/Fireworker.cs
  Roles/Impostor/Kamikaze.cs
  Roles/Impostor/Lightning.cs
  Roles/Impostor/Mastermind.cs
  Roles/Impostor/Penguin.cs
  Roles/Impostor/Puppeteer.cs
  Roles/Impostor/Vampire.cs
  Roles/Impostor/Witch.cs
  Roles/Impostor/YinYanger.cs
  Roles/Neutral/Agitater.cs
  Roles/Neutral/Arsonist.cs
  Roles/Neutral/Infectious.cs
  Roles/Neutral/Pelican.cs
  Roles/Neutral/Pirate.cs
  Roles/Neutral/Pursuer.cs
  Roles/Neutral/Quizmaster.cs
  Roles/Neutral/Revenant.cs
  Roles/Neutral/Revolutionist.cs
  Roles/Neutral/Shocker.cs
  Roles/Neutral/Shroud.cs
  Roles/Neutral/Virus.cs
Labels: Fix bug
